### ISSUE TITLE
Big Reactors config different from RR's

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#1]
In the RR configs, the following line was this :

D:powerProductionMultiplier=3.0

In the new unified configs, its :

D:powerProductionMultiplier=1.0

I'll leave it up to you whether this is a change needed :D

**Comment by Abouttabs** [comment]
For now we will test 2x and we will see later.

**Comment by Abouttabs** [comment]
Eh durp me, kenny set it to 3x :-D
