### ISSUE TITLE
Essence crafting, Prodject Red

### ISSUE THREAD

**Issue by Panthron** [RTRGitHub/RTRRedux#101]
the essence recipes for: Ruby, Sapphire, and Peridot, are tied to Custom NPC gems and Project Red gems cannot be crafted. 

explain:
using Essence of Ruby in a crafting table in the same configuration as a chest/furnace should yield ruby 6879:37
actual yield is Ruby 5131 from Custom NPC (currently disabled)

Item ID's as follows.
Project Red 
          Ruby 6879:31 using Essence of Ruby 6650:6 from magic crops
          Sapphire 6879:38 using Essence of Sapphire 6650:5 from magic crops
          Peridot 6879:39 using Essence of Peridot 6650:7 from magic crops

Suggested Fix:
          Add recipe using the crop essence in an Iron chestplate configuration to yield Project Red gems.

**Comment by Solidflip** [comment]
This item has been fixed, they now craft 4 of the ProjectRed gems
