### ISSUE TITLE
Erebus biomes in the mining age

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#106]
When we reset the mining age, could we try and configure erebus so it's biomes are not used?
Most of the biomes in the MA are erebus, which pushes out other mineable biomes like snow and desert.

**Comment by Abouttabs** [comment]
Unfortunately I believe that it might be multiverse, it is known for screwing biomes up.. We could upload pregened world when we reset it possibly, that would fix it.

**Comment by RTRGitHub** [comment]
^ worth a shot

**Comment by Solidflip** [comment]
I will try this this weekend when i reset it =) Ill close this, if there are still some there ill reopen.
