### ISSUE TITLE
Steves factory manager kicks on item search

### ISSUE THREAD

**Issue by Abouttabs** [RTRGitHub/RTRRedux#108]
Crashes (I suspect fluid registry here) https://github.com/Vswe/ModJam3/issues/68
this is my crashlog http://pastebin.com/8BqNqgGu. This is just to not forget...

**Comment by kenny608uk** [comment]
Yeah seems like it ..

**Comment by bradroeger** [comment]
I'm getting this as well and was just about to post this as new.

**Comment by Solidflip** [comment]
Previous pack version
