### ISSUE TITLE
[Request] Magical Crops config change

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#11]
Line 88 & 89 state:

```
I:"Change number between 1-100 for chance of getting second seed drop, 10 = 10%, 20 = 20%(default) and so on."=0
I:"Change to disable or enabled second seed drop, 1 = Enabled (Default), 0 = Disabled"=0
```

Can we please enable second seed drop, and then put the % at 5-10% to give some sort of incentive for farming these crops?

**Comment by Abouttabs** [comment]
I believe I remember I personally set it to 0, I believe that they are powerful enough as they are, but we will discuss this and we are always open for input from players...
