### ISSUE TITLE
Crashing when I logg/tp to base. Happens sometimes, not all the time

### ISSUE THREAD

**Issue by Danius95** [RTRGitHub/RTRRedux#115]
http://pastebin.com/D2TsTCu1

**Comment by Abouttabs** [comment]
Seems like quick fix for you should be removing fastcraft, also please tell me what precisely happens so I can have a closer look at it when I get home in 8 hours :-D

**Comment by Danius95** [comment]
Ye sorry lol. I was tired :P More info in the title :)

**Comment by Abouttabs** [comment]
Still, try removing fastcraft..

**Comment by Danius95** [comment]
Yepp. I did :D Gonna log in soon

**Comment by Solidflip** [comment]
previous pack issue
