### ISSUE TITLE
AE issues on restarts

### ISSUE THREAD

**Issue by Panthron** [RTRGitHub/RTRRedux#118]
The Security terminal and quantam bridges, both have to be broken and replaced following a restart of the server, if not done neither will work.

**Comment by Solidflip** [comment]
This happens when the chunk is unloaded and reloaded, The only fix i know is to have a 1 chunk ME system, or always chunk load it. Ill get with tabs/kenny see if we can think something up.

**Comment by Solidflip** [comment]
previous pack issue
