### ISSUE TITLE
Possible Lag contributor

### ISSUE THREAD

**Issue by Panthron** [RTRGitHub/RTRRedux#119]
I noticed within my large ME system that many of my P2P channels were resetting VERY often.
This was caused by the P2P cables/system I'm using not being separately powered using it's own energy acceptors/power storage.  Since adding this I no longer notice the channels resetting. Still too early to say that it IS the cause of the lag, however it seems to me that 32x16 channels being reset to a me system would be a little taxing on server resources.

**Comment by ghost** [comment]
May be unrelated but the last time I played we had issues with this at our base when it was initially loading.  All of the level emitters would reset, all p2p's reset, etc.

**Comment by Solidflip** [comment]
previous pack issue
