### ISSUE TITLE
(Dev_B_2.5.4) Crash everytime i use 'u' in NEI

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#122]
Crashlog : http://pastebin.com/guCWBXZn

**Comment by kenny608uk** [comment]
Try 2.5.3 fixed it for us

**Comment by ghost** [comment]
Not fixed in 2.5.3 for me either

**Comment by ghost** [comment]
heres mine http://pastebin.com/4JfveDG6

**Comment by Abouttabs** [comment]
Seems like broken scala library. Please try to completely delete the instance and re-download 2.5.3 again..

**Comment by ghost** [comment]
I deleted the instance and reinstalled.  It still occurs.

**Comment by kenny608uk** [comment]
Have you downgraded to 2.5.3? -k

**Comment by Volaunis** [comment]
I still get it on 2.5.3, complete pack reinstall.

**Comment by kenny608uk** [comment]
Will investigate -k

**Comment by kenny608uk** [comment]
Hmm, have a feeling that we need to remove/readd mods manually to possibly fix this

**Comment by kenny608uk** [comment]
Fixed in next version
