### ISSUE TITLE
[DEV_B_2.6.0]Crash when i log on to the server

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#127]
http://pastebin.com/xWjPBjgn

**Comment by kenny608uk** [comment]
What was the last thing you did before logging off?

**Comment by Volaunis** [comment]
I was digging my way up the side of the mesa near spawn, and was at the last block to get up on the top, and was waiting for it to become daytime.

**Comment by Solidflip** [comment]
Problem fixed in newest version.
