### ISSUE TITLE
Tinkers Glove crash in tinkers crafting table

### ISSUE THREAD

**Issue by Panthron** [RTRGitHub/RTRRedux#129]
http://pastebin.com/QDwx05H7

Crash occured while trying to place a tinker's glove in a crafting station 1511:0.
MC log is too long, but also crashes client when trying to add redstone to glove in tool forge, 
Glove is able to be placed in tool forge without incident

**Comment by Solidflip** [comment]
Ill look into it. For future refrence all i need is from Line 470 down. Thats the error report the rest is just minecraft logging things like it does. From first glance appears like a interation with thermal smeltery

**Comment by kenny608uk** [comment]
Probably just needs updating

Sent from my iPhone
-k

**Comment by Solidflip** [comment]
Its not a game defeating crash, we will update and see if it solves the issue. I cant find very many documentation on crashes with thermal smeltery (1 issue on his github) but a lot of people having the same crash on OpenEye.......

**Comment by Solidflip** [comment]
No crash since update reported, issue closed. Reopen if it happens again
