### ISSUE TITLE
[Mod Addition] MPSA

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#13]
MPSA - Modular Power Suit Addons

MPSA underwent a dev change between 1.5.2 and 1.6.4 where Andrew decided to drop out, and Eximius decided to pickup the mod.

The thread says that MPSA is still under experimental, but I think this would be a decent addition since we already have MPS installed. Wouldn't suggest rushing this into the pack, but definately something to keep an eye on imo.

http://www.minecraftforum.net/topic/2287651-experimental164-modular-powersuits-addons-mpsa-requires-modular-powersuits/

**Comment by kenny608uk** [comment]
Will be added in the next pack build, probably Tuesday the 4th

**Comment by Abouttabs** [comment]
MPSA was already tested and it works fine, It is safe to include
