### ISSUE TITLE
Unable to craft a Mundane Belt

### ISSUE THREAD

**Issue by Noatel** [RTRGitHub/RTRRedux#131]
The Mundane belt ( ID 4707:2 ) and the Basic Belt Base ( ID 7076 ) got the same recipe. When I try to craft the Mundane Belt it gives me the Basic Belt base.
http://gyazo.com/beb3eb8e338f3c7942368ec67c96b722

 I also tried to craft it in the Arcane worktable.
http://gyazo.com/7d415a95dee76203eff0d025aa9ba754
- N0at3l, Noah ( Not neil )

**Comment by Solidflip** [comment]
I will fix this tonight

**Comment by Solidflip** [comment]
FIXED
