### ISSUE TITLE
Do not place Portable Tank in Fluid Transposer

### ISSUE THREAD

**Issue by echo214** [RTRGitHub/RTRRedux#132]
Placing a Portable Tank into a Fluid Transposer will instantly crash the server the second the chunk containing the said Transposer is loaded.

**Comment by Abouttabs** [comment]
I will expand this, do not place anything but vanilla buckets or things that need it for crafting (if you're not sure double check with NEI). 

There is no point in putting a tank/different fluid storage in it, you can put fluiduct on export side and have the tank filed that way..

**Comment by Solidflip** [comment]
Will add to the "Do not do this" thread on the forums
