### ISSUE TITLE
random crash info full log

### ISSUE THREAD

**Issue by scoobydoo192** [RTRGitHub/RTRRedux#133]
http://paste.atlauncher.com/view/af4eb044

**Comment by Abouttabs** [comment]
Do you have crash log scoob? I see some derpiness with tooltips with forestry not getting fuel values properly, but actual crashlog would be helpful. 
Thank you

**Comment by scoobydoo192** [comment]
Its been fixed by solid it was echo's problem so no crash log for me

**Comment by Abouttabs** [comment]
Ok, good to hear as I couldn't see anything wrong..
