### ISSUE TITLE
Crash log with Enhanced charm of Dislocation

### ISSUE THREAD

**Issue by Panthron** [RTRGitHub/RTRRedux#135]
http://pastebin.com/sU4CjmT6

Happened once in Nether near nether portal and again in overworld near same, at Randompies' house.
Nether crash was while shift clicking to open the charm.
Overworld crash happened while trying to teleport to the end.

**Comment by Solidflip** [comment]
Has this happened since? According to the log it seems like an inter-dimensional issue, However ive used mine to switch dimensions without a crash...Fluke maybe?

**Comment by Solidflip** [comment]
I just did this, went from end to nether to overworld. Issue seems fixed....
