### ISSUE TITLE
crash from drinking mellon juice from backpack

### ISSUE THREAD

**Issue by scoobydoo192** [RTRGitHub/RTRRedux#137]
http://paste.atlauncher.com/view/94eada0e

drank some juice and it kicked me from the server i get back on and i have a haste buff but as far as i know its just supposed to feed you(on my minipack with this mod it didnt crash when drinking from it before)

**Comment by scoobydoo192** [comment]
no crash report avalible

**Comment by icha-senpai** [comment]
hai scooby i was wonder if you could give me more some more info....what kind of juice...what were your coordinates...what other items did you have in your inventory...would you mind retrying with all other thing out of your inventory like tools armor and items...so we can limit it to the juice and then i can further help from there....when you sign on again and i am on let me know and we shall test this...thxs very much...btw just incase the senpai thru you off its ichatv

**Comment by Solidflip** [comment]
Has this happened since? I will test in-game to see if it happens to me, hopefully we can get a crash log....

**Comment by Solidflip** [comment]
Tested and i didnt crash, as it seems to be a isolated issue, will reopen if it happens again
