### ISSUE TITLE
Unable to Burnt Quartz (ID: 1271:2) (Extra Utilities)

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#139]
Cant Burnt Quartz in a Redstone Furnace or Alloy Smelter. Alloy Smelter makes fused quartz with the block of quartz(id:155), and you cant even place the block of quartz in the redstone furnace.

Only way i found to burnt quartz....vanilla furnace. :(

**Comment by Volaunis** [comment]
Set the alloy smelter to not do alloys, and it'll make burnt quartz.
As for the restone furnace, i don't think it's ever been able to in 1.7, it couldn't on the last map either.

**Comment by Solidflip** [comment]
Issue closed. Not a bug. LEARN HOW TO USE THINGS CESS!!!
