### ISSUE TITLE
Internal Server Error when trying to use bucket on fluiduct

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#140]
See title

**Comment by Abouttabs** [comment]
Just a kick, or proper crash? I will need either crashlog, or console
log...

**Comment by Volaunis** [comment]
Just a kick, we can try again once we're both on, or go to my base and test, i have exposed fluid pipes there.

**Comment by Abouttabs** [comment]
Well do

**Comment by Solidflip** [comment]
Update? Ill test in game to see if it still happens

**Comment by Abouttabs** [comment]
there wasnt one, COFH freaks out when its updated...

**Comment by Solidflip** [comment]
I meant do we have an update on this issue... ill test in-game in a sec
