### ISSUE TITLE
Steve's Inventory Manager Eating CPU

### ISSUE THREAD

**Issue by ftheriachab** [RTRGitHub/RTRRedux#141]
I programmed a Steve's Inventory Manager to decompressed every cobble up to 8x and it timed out everyone on the server when I made the node connections.  I was able to login and after about a dozen time-outs I was able to break the Manager to fix the server.

**Comment by kenny608uk** [comment]
Yeah that would be the sheer volume of work you're making it do. ME systems have the same problems I've found
