### ISSUE TITLE
Deadlocking server when logging on in own dimension

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#142]
Whenever i log on after not having been on for a while, and noone else is on, it deadlock the server, timing out while loading the area around me. This appears to only happen when i log on while i'm in my age. Logging on later when there's people on (and presumably after someone has restarted the server) logging on works fine.

**Comment by Volaunis** [comment]
Should note that it _just_ happened to me, so you can go off of the github timestamp to determine when it occured on the server.

**Comment by kenny608uk** [comment]
Sounds like it's an issue with the age not being loaded properly
