### ISSUE TITLE
Ftheriachab constant timeout/crashes

### ISSUE THREAD

**Issue by ftheriachab** [RTRGitHub/RTRRedux#145]
Can login for a couple of seconds and only the chunk I'm in loads, then I timeout.  Restart client, uninstalled optifine, still an issue.  When I try on other occasions, my client just crashes. The crash report is below

http://pastebin.com/Fc9U2miR

**Comment by kenny608uk** [comment]
I _think_ I've fixed it. Please try logging in when the server comes back up.

Kenny

**Comment by ftheriachab** [comment]
I can login just fine :)

What was the problem?

**Comment by kenny608uk** [comment]
When runic dungeons is included in the client but not the server it causes a weird desync with certain things, I forgot to add it to the server when I updated. Glad it's fixed, can you close the issue for me?

Kenny
