### ISSUE TITLE
Diorite can't be veinmined

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#146]
See subject

**Comment by Volaunis** [comment]
Also, andesite, granite and basalt (botania) probably don't work either

**Comment by Volaunis** [comment]
As well as sand, dirt and MFR rubber tree trunks

**Comment by Solidflip** [comment]
Im currently waiting to see if Tabs has the old config file. If he doesnt then i will add all these in manually.

**Comment by Abouttabs** [comment]
Tabs found fuck all, sorry mate...
-tabs

**Comment by Solidflip** [comment]
All added except dirt. Im not sure we had that before but it sounds like a bad idea.
