### ISSUE TITLE
Game drops

### ISSUE THREAD

**Issue by movada** [RTRGitHub/RTRRedux#147]

**Comment by kenny608uk** [comment]
This provides no information or direction for us to look. Please provide a response with details such as where where/how this occurs

Sent from my iPhone
Kenny

**Comment by Abouttabs** [comment]
Also crashlog or forge log of crashlog doesn't generate. Without that we
can't do anything. When providing crashlog do not paste it here, put it to
pastebin or similar site...

**Comment by Solidflip** [comment]
She was going to but the log lost the info. Im waiting for her to give me a log today.

**Comment by movada** [comment]
http://pastebin.com/US90J2Tz

This is the crash log

**Comment by movada** [comment]
http://pastebin.com/Sa9yEyEz

**Comment by movada** [comment]
http://pastebin.com/2R8SpzgS

**Comment by Abouttabs** [comment]
When exactly does it happen? While loading, while logging in...? It seems like corrupted file anyway, try deleting the instance completely and redownloading it again (well unless the instance loads in which case I am wrong entirely and I am afraid well need more details, but if it crashes during loadup it seems like file corruption...)

**Comment by movada** [comment]
what was happening was while loading and almost done with would kick me back to the launcher, I did go in and delete all my Java.s and re-install just java 64bit since then i have turn the game on and off 5 times and each time it starts without a hitch now. Thank You so much for the help. If it does start acting up as if that was not the fix I will try the re-downloading option.

**Comment by Solidflip** [comment]
Issue resolved by updating resource pack. Error as due to a sound file corruption.
