### ISSUE TITLE
VeinMiner addition

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#149]
Draconic Staff of Power 5541

**Comment by Cpfuzzyz** [comment]
Was about to just post about this, I think it should be added too, since the pick can veinmine.

**Comment by UnsungCesspool** [comment]
Perhaps the admins can discuss just setting the config to "true" on the setting that "if your wielding the correct tool to harvest an item/block, its veinminable". Just a thought...they'll finger it out.

**Comment by Solidflip** [comment]
FIXED!!!!!!
