### ISSUE TITLE
Bedrock sucks down your equipment 

### ISSUE THREAD

**Issue by GenGrim** [RTRGitHub/RTRRedux#152]
i died in Minecraft down at the bedrock, when i got back to get my equipment from the grave my equipment got suckted down in to it and i cant recover it trew that ! i think its a glitch.

**Comment by Solidflip** [comment]
I havent been able to re-create this issue, however if you get with an admin or mod they should be able to restore your inventory from before the death.

Will close until the event can be reproduced
