### ISSUE TITLE
Runic dungeon /dungeonscore command

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#155]
Hello,

We are not allowed to run the /dungeonscore command due to permissions.

From the RD curse page: 
"The command '/dungeonscore' tells you how many dungeons you have completed"

**Comment by Abouttabs** [comment]
Will solve that

**Comment by Abouttabs** [comment]
I have sent a message to the mod author asking for perm nodes. Till then theres nothing I can do...

**Comment by Solidflip** [comment]
Problem unable to fix until permission nodes are added.

**Comment by Abouttabs** [comment]
Even though solid doesnt like to solve things (obviously, he just closes them... :D) I took care of it....
