### ISSUE TITLE
Disconnected from server when entered nether

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#158]
When i tried to enter the nether using my nether portal at my base, i was disconnected and i disconnect whenever i try to join the server after that. It happened around 10.05PM CET.
The message i get is either "java.io.IOException: An existing connection was forcibly closed by the remote host" or "A fatal error has occurred, this connection is terminated".
My base is around -1450, -50, and the nether portal on the nether should be in the appropriated location to match the overworld one.

Below is the log from my client. It doesn't seem to tell me anything :
http://pastebin.com/C2uYEpJF

**Comment by Solidflip** [comment]
The log isnt complete, for the crash i need the crash log. As to the constant crashing ill see what i can do. Make sure to get with a mod/admin in ts so we can fix this.

**Comment by Volaunis** [comment]
As i mentioned, it wasn't a crash, it was a disconnect.
However, it seems a server restart has fixed the issue as i can now log in fine.
