### ISSUE TITLE
Yellorium/Uranium ingots

### ISSUE THREAD

**Issue by theViTALiTY** [RTRGitHub/RTRRedux#159]
By default in BigReactors config, its enabled that yellorium dust sometimes smelts into uranium ingots, and that is making a problem for ME system if that stuff is automated. If the system is set to smelt 1 yellorite dust into 1 yellorium ingot, and instead it smelts it into uranium ingot, ME system will just hang because it didnt register uranium as yellorium ingot and therefor render the crafting cpu useless until the crafting operation is cancelled. 

This can be disabled in BigReactors config line #36 B:registerYelloriteSmeltToUranium=true, by setting it to false. But keep in mind not to set line #37 B:registerYelloriumAsUranium=true to false, so people who still have uranium left over can use it to power the reactor.

**Comment by Abouttabs** [comment]
Done, forgot to mention here

**Comment by theViTALiTY** [comment]
http://prntscr.com/7hthn2

U sure?

**Comment by Abouttabs** [comment]
its changed... I am positive...
in the server that is...
