### ISSUE TITLE
Runed Tablet

### ISSUE THREAD

**Issue by PiraatSchaap** [RTRGitHub/RTRRedux#160]
I went to the Eldritch World and found a room which should contain a Runed Tablet, but it didn't. The room is supposed to look like: http://i.imgur.com/YdUEdU6.png , which it does, but without the tablet.

Runed Tablet ID: 5129:2

**Comment by Abouttabs** [comment]
are you sure you wee the first one there? :smile:

**Comment by PiraatSchaap** [comment]
There were no indications if anyone else being there before me. No destroyed blocks, no empty boss room.

**Comment by Abouttabs** [comment]
Ok, tel one of the mods, or an admin when you're on, they'll give you one..

**Comment by Solidflip** [comment]
Item given by Dragon on 7/1/15. CLosing issue
