### ISSUE TITLE
Disconnect when DE Mob grinder kills Witchery Mob

### ISSUE THREAD

**Issue by PiraatSchaap** [RTRGitHub/RTRRedux#166]
So far I've only seen the issue happening when changing dimensions / getting killed. 
Message:
Connection Lost
A fatal error has occured, this connection is terminated

Console log: http://pastebin.com/QCeTvuyv

**Comment by Solidflip** [comment]
Related http://pastebin.com/tiaNPYRp

**Comment by Solidflip** [comment]
Seems to be related to this https://github.com/brandon3055/Draconic-Evolution/issues/72

**Comment by Solidflip** [comment]
Reported to Mod Author, waiting on response.

**Comment by Solidflip** [comment]
Need to bring to Witchery Attention as well, Will go to their IRC when i can and also post on the mc forums thread

**Comment by Solidflip** [comment]
Reported issue, will await answer for fix. Until then advised players not to use cursed earth with DE mob grinders for now. Will reopen when i receive a response.
