### ISSUE TITLE
Advanced solar panel bonus

### ISSUE THREAD

**Issue by PiraatSchaap** [RTRGitHub/RTRRedux#167]
Advanced Solar Panel are not getting the 50% bonus they're supposed to get when they're in a desert  biome. 

Tried it with a vanilla desert biome in SP as well.

**Comment by Solidflip** [comment]
Tested in-Game, the ones in deserts do give 50% more, but there is a visual glitch that shows it not doing so. I tested by having both output to an energy cell, the one in the desert ended up with around 45% more energy (chalk that up to user error).

So TL;DR, it does, its just a visual glitch
