### ISSUE TITLE
Its Gone

### ISSUE THREAD

**Issue by TheToplessGamer** [RTRGitHub/RTRRedux#168]
I had a cyan bag of holding in my inventory the i logged out for a few hours came back in and it was gone i tried relogging and filling my inventory with different item but its just not there it disappeared

**Comment by Solidflip** [comment]
Will look into this tonight

**Comment by Solidflip** [comment]
Unable to reproduce the issue, replaced the bag. Get with an Admin/Mod for further reimbursement.
