### ISSUE TITLE
Land claim block count

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#171]
Greetings,

The current land claim block count is a bit more than 1024. This is enough to cover a bit over 4 chunks.
Now, a lot of us have bases that are larger than that, and i at least would like to cover my entire base (which is, without the outer walls, 12 chunks). Therefore i would like the limit set up to 5k. I think that is a good number, and would allow me at least to cover my base.

**Comment by Abouttabs** [comment]
Additional claim blocks can be requested, added 5000 to your claim...

**Comment by Solidflip** [comment]
Id like to keep the original count lower, you do gain 100 per hour as you are on. Starting with a higher number encourages people to make sprawling bases and i dont want half the map claimed by a select few. As tabs said additional claim blocks can be requested and will be given out.

Issue closed as claim was adjusted, default claim block will stay the same
