### ISSUE TITLE
Mekanism Pressurized Tubes stop working after reset

### ISSUE THREAD

**Issue by PiraatSchaap** [RTRGitHub/RTRRedux#174]
The tubes will stop working after reset, and work just fine after replacing them 'till the next reset happens. Known to be this way so far with the Basic & Ultimate versions.

**Comment by Solidflip** [comment]
Issue is due to chunk loading, use a chunk loader to load the chunks surrounding the area and it should be good. Issue is fixed in newest version of Mekanism, we will have to wait until RR3 updates.
