### ISSUE TITLE
soulbound items in the end

### ISSUE THREAD

**Issue by mydogiswellhuge** [RTRGitHub/RTRRedux#176]
Second time i have died and items do not remain soulbound. Will retrieve them myself but its a bit of a pain in the finger poppin ass! p.s. no grave either. Died again and cant be assed going 1000blocks to get my stuffs. sigh....

**Comment by Solidflip** [comment]
When this occurs tell an admin or mod, they can reinsate your inv from the console. This bug has been reported to the EnderIO github still waiting on a response. Will close until that time, for now tell an admin or mod what time on what day it was and we can restore your items.
