### ISSUE TITLE
Yellorite + TiC Smeltery recipe

### ISSUE THREAD

**Issue by JustinS2** [RTRGitHub/RTRRedux#177]
When melting yellorite ore in the TiC smeltery you get ~288mb per ore, this is correct for most other ores as it equals two ingots. However, since yellorium requires 1000mb per ingot or 9000mb per block due to how Big Reactors treats liquid yellorium, this results in a vast reduction in the amount of processed ore

**Comment by Solidflip** [comment]
Recipe fixed, ingots now give 1000mB, Ore gives 2000mB, blocks of yellorium 9000mB.
