### ISSUE TITLE
thaumic energestics: essentia provider

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#179]
I have my essentia provider hooked up, powered , on a proper channel to the AE system. I have the proper essentia . But still it will not draw from the provider when the ritual is started. I think I have it correct I cannot find a flaw. 

game name Atrophy

**Comment by Solidflip** [comment]
You need the Infusion Provider to do rituals, the essentia provider is for another item.  Once you have the infusion provider then it will work fine =)
