### ISSUE TITLE
Taint and vitium essence 

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#180]
I need vitium essence, there is not a tainted biome for me to try tainted objects to get it. what do I do ? I have researched other ways to get it and can find none. I  simply need to scan and process some tainted objects.

**Comment by MrAtrophy** [comment]
found a taint biome

**Comment by Solidflip** [comment]
Was just gonna ut the coords 1300 450 ish. There should also be a magical forest nearby.
