### ISSUE TITLE
digital miner spot loader issue

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#181]
even thou I have a spot loader by my digital miner, when i leave the mining world it shuts off. has enough power, no other issues. 

game name atrophy

**Comment by MrAtrophy** [comment]
update dim anchors work spot loaders do not

**Comment by Solidflip** [comment]
Does the spot loader still load when in the other dimensions like the End or Nether? Or is this every dimension except the overworld?

**Comment by MrAtrophy** [comment]
unknown I have only noticed it in the mining world, I will do some testing

**Comment by Solidflip** [comment]
Awesome, test it in the mining world/Nether/overworld if you can and get back to me. I would test it myself but seeing as the issue can be fixed by using another loader ....

**Comment by MrAtrophy** [comment]
no longer an issue , please close

**Comment by Solidflip** [comment]
Issue closed on request of creator, issue no longer present.
