### ISSUE TITLE
Sanguimancy " delving into darkness" guide critical error

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#182]
found a fix for it but I have no Idea what to do with it , if this is on my end or the servers

https://github.com/TeamAmeriFrance/Guide-API/commit/d587ea248c4769dd9890cd8d9d4e33ca8fbf8238
- Atrophy

**Comment by Solidflip** [comment]
Requires update of Guide-API due to NBT being null. Will look into it.

**Comment by Solidflip** [comment]
Requires update of Guide-API, will have to wait until RR3 updates again to fix, reported to RR3,

**Comment by Solidflip** [comment]
have to wait for update, will place this in the things not to do on forums until fixed closing issue temporarily
