### ISSUE TITLE
Direcub10 crashlog

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#183]
Crashlog for crashing on opening map in mining world

http://pastebin.com/SJx2QDBc

**Comment by Solidflip** [comment]
The log is incomplete, i need the whole thing to get a better idea of the issue. Make sure to include the whole log with the stacktrace and all.

**Comment by Direcub10** [comment]
u ppl made a topic without me XD
http://pastebin.com/VxC1Q9k2

**Comment by Direcub10** [comment]
at this point idc i got my miner

**Comment by Solidflip** [comment]
issue resolved
