### ISSUE TITLE
Pride Shard not dropping

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#184]
pride shards should drop when defeating large mobs. I have spoken to Dog who has defeated the chaos dragon and other large mobs and none have dropped. 

-Atrophy

**Comment by Solidflip** [comment]
From their wiki:
"Pride Shards drop when a boss is killed in the Nether. This can be the Wither, or any boss added by another mod that has the standard boss health bar, as long as it is in the Nether."

**Comment by MrAtrophy** [comment]
got it

**Comment by Solidflip** [comment]
Also try using a pick enchanted with Corrupting on a thaumcraft shard ore. That should get you the forbidden shards.
