### ISSUE TITLE
Extra Cells

### ISSUE THREAD

**Issue by TheToplessGamer** [RTRGitHub/RTRRedux#186]
If you have cards in the Me fluid export/import bus and break it the cards don't drop they just disappear.

**Comment by Solidflip** [comment]
Will look into this tonight.

**Comment by Solidflip** [comment]
Topless, do you mean upgrade cards like the acceleration card? or another type of card?

**Comment by TheToplessGamer** [comment]
Acceleration

**Comment by Solidflip** [comment]
If you use a wrench it comes out with the cards still inside, If you break it with the incorrect tool it destroys the items. I believe this is functioning as intended but ill bring it up on the AE2 github, for now make sure to use the correct tool as that works as intended.
