### ISSUE TITLE
plserino client side config for veinminer

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#188]
so my client is set to tidal or the grave key but server overrides it to shift...i'd like it so if it didn't do that...cause i vein-miner stuff by accident

**Comment by Abouttabs** [comment]
Do you have the client side mod? It's not included by default and you need
it to override sneak...

**Comment by Solidflip** [comment]
He has the client side mod, and has the config set corectly. He is not using ATLauncher so im having him launch it in ATL to see if its a launcher issue.

**Comment by Solidflip** [comment]
Config setting is working for others on the server, narrows it down to a non-server issue, rather a client side. Will help investigate

**Comment by Solidflip** [comment]
Issue is resolved, relogging fixed it
