### ISSUE TITLE
My balls itch

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#189]
please help

**Comment by Solidflip** [comment]
Issue client side, not related to the server. Try to take a regular shower and wash with soap?

**Comment by Solidflip** [comment]
BTW tabs dont get angry...we were bored in TS

**Comment by Abouttabs** [comment]
Assigned person to come over and fix. 

Way to fix is to cut em off and solid will eat em...

**Comment by Solidflip** [comment]
Hey now, im on a diet!
