### ISSUE TITLE
I died for no reason

### ISSUE THREAD

**Issue by TheToplessGamer** [RTRGitHub/RTRRedux#193]
I logged on and dire asked my to go to his base so i did but my internet was lagging a lot so when i got there i decided to reset my minecraft. When i logged off dire said that i died but i didn't make any sense to me because before logging off i had full health. After my minecraft booted up again and i logged on to the server i got the death screen and when i respawned i had nothing in my inventory not even my soulbound items and as usually when that happens only my baubles were in my grave. This happened around 1pm GMT+1 im leaving the server with nothing in my inventory no extra hearts and no baubles. Could you please give me my inverntory. If you need anymore info or to tell me that you did it just say it here because i get emails from github as soon as something happens in a post that i make.

**Comment by Solidflip** [comment]
Issue resolved
