### ISSUE TITLE
need mod meeting 

### ISSUE THREAD

**Issue by dragonaslin** [RTRGitHub/RTRRedux#194]
dear higher powers,
need to hold a mod meeting to go over situations on curupted problems.which include finding,assesing,and elimination of the chunk and other problem solving things so that we dont have to bother you with simple things. ty for your time and patients on the subject.

```
                                                                                                                                  sincerly,
                                                                                                                                 dragonaslin
```

**Comment by Camtoe112** [comment]
Agreed, in the Mod Tower.

**Comment by Solidflip** [comment]
Please use the trello for things like this
