### ISSUE TITLE
Can't place saplings

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#195]
i can't place saplings in my last mil base it disappears and reappears in my inv

**Comment by Abouttabs** [comment]
Have you been using any mobspawning in that area?

**Comment by Solidflip** [comment]
What sapling? In a claim or not? What dimension? more details please

**Comment by Volaunis** [comment]
I'm having the same issue : 
Dim : last millenium
Sapling : Oak sapling
y-level : 100
No claim

I can place other blocks in the same spot, and if i try and place the sapling on a dirt block placed there, ie. y=101, it plants fine. 
I can also not place it at y=99.

**Comment by Abouttabs** [comment]
Is there same amount of light everywhere there?

**Comment by Volaunis** [comment]
There's a torch right next to it :
https://www.dropbox.com/s/wkg6xtf76bhjsvp/Screenshot%202015-09-04%2012.11.59.png?dl=0
That dirt block it's on in where i can't place it.

**Comment by Volaunis** [comment]
I think i just found out what the issue is. Saplings need 2 blocks of dirt beneath them, one will not suffice!

**Comment by Abouttabs** [comment]
Odd

**Comment by Volaunis** [comment]
lower block does not need to be dirt btw.

**Comment by Volaunis** [comment]
...and now i've managed to place saplings without there being a block below the dirt block...i'm confused...

**Comment by Abouttabs** [comment]
You and me both...

**Comment by Solidflip** [comment]
phantom blocks perhaps. Since no new issue comment/user has gone afs for a while issue closed. If necessary reopen with further info/need. Server will be replaced soon anyway
