### ISSUE TITLE
I murdered again 

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#197]
I accidentally killed kazandrajean 1:49 am pacific. I helped her get as much as i could back but she last everything.

anyway you can restore her items ?
- atrophy

**Comment by Abouttabs** [comment]
You murderer....

**Comment by Solidflip** [comment]
Please have Anna speak with a mod/admin and ill get those items back to them

**Comment by Solidflip** [comment]
No reply, issue closed as pack will be reset anyway
