### ISSUE TITLE
NO WAITING A MONTH (+12 hours for nagging) 

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#200]
GIVE ME NEW SERVER OR GIVE ME DEATH

**Comment by icha-senpai** [comment]
CLOSE IT CLOSE IT COME ON FLIP JUST DO IT...DO IT NOW...WHEN YOU CLOSE THIS YOU AGREE TO GIVE US THE NEW PACK TODAY

**Comment by Abouttabs** [comment]
When I close it I can promise you that nagging won't do any good, actually, you have just postponed server going live by 12 hours from the point when it's ready, good job mate, good job...

**Comment by icha-senpai** [comment]
http://puu.sh/klMWp/482e621548.jpg not upset about it cause i have been making this

**Comment by Solidflip** [comment]
Yeah...this isnt the use for github, Please refrain from using it apart from server related things like bugs/enhancements etc
