### ISSUE TITLE
crash log with new pack

### ISSUE THREAD

**Issue by dragonaslin** [RTRGitHub/RTRRedux#201]
http://pastebin.com/MG05jcT7

**Comment by Solidflip** [comment]
This is an issue with mob spawning and entity ids. To test which mod it is remove mods that spawn mobs 1 at a time to see when it fixes. I would try removing lycanites first, then move on to the others

Anyone else get this issue?

**Comment by dragonaslin** [comment]
http://pastebin.com/vqMAgss7

**Comment by dragonaslin** [comment]
http://pastebin.com/PwTETGts

**Comment by dragonaslin** [comment]
the problem is with evil craft

**Comment by scoobydoo192** [comment]
First launch same world crashed 
http://pastebin.com/ZyqBVnLF
http://pastebin.com/1d5zVxFg
Did two of the same world because sometimes mine craft crashes on a world start up for me but works fine afterwards

**Comment by scoobydoo192** [comment]
took out evil craft as suggested haven't crashed on start up.

**Comment by Solidflip** [comment]
Reported to the mod author, we will wait for a response to see whats up, Hopefully we can keep it

**Comment by scoobydoo192** [comment]
http://imgur.com/FxpzZg1

**Comment by Solidflip** [comment]
Thats a separate issue, new issue please

**Comment by Solidflip** [comment]
Might be related to max number of mobs allowed being reached, will test now by disabling a bunch of lycanites mobs to free up ids

**Comment by Solidflip** [comment]
Removed lycanites mobs, game still crashes on entity -128, will test removing all mobs spawned by evilcraft

**Comment by Solidflip** [comment]
removed evilcrafts mobs and it loaded fine, sat in world with mobs spawning around me for 5 mins without crash. Will upload config file to dev_A 1.0.0.1 when i can
