### ISSUE TITLE
New issue unable to get out of inventory

### ISSUE THREAD

**Issue by scoobydoo192** [RTRGitHub/RTRRedux#202]
http://imgur.com/FxpzZg1 here you go

**Comment by scoobydoo192** [comment]
i tried getting rid of all the key bindings that didn't work i turned off my keyboard to see if it was a key sticking for some reason that didn't work not sure what else i can do cause it just wont close if i hold the escape key it will stay closed and i can open up the books we auto get if im fast enough but one i've closed them that pops up once again

**Comment by Abouttabs** [comment]
Had that, did you add any client side mods? (not enough keys or so...)

**Comment by scoobydoo192** [comment]
nope only thing i've done is take out evil craft to fix crash on startup

**Comment by Solidflip** [comment]
I just played the pack for a few minutes, never ran into this issue. Might be config/keybinding related and i do not have not enough keys either. will upload my config shortly once evilcraft test is successful

**Comment by Solidflip** [comment]
Evilcraft test successful, will upload config file to Dev_A 1.0.0.1 to test this issue with my configs

**Comment by Solidflip** [comment]
Soup stated that he had this issue with Not Enough keys, then took it out and the problem vanished. Please re-try the pack WITHOUT NEK.

**Comment by scoobydoo192** [comment]
fixed :)

**Comment by Solidflip** [comment]
Awesome
