### ISSUE TITLE
My first testing crash....YAY

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#203]
When i opened the visual UI for my power tool from MPS this happened http://pastebin.com/GrR4iFUp

**Comment by Solidflip** [comment]
using 0.11.0.281, Only occurs with the powerfist, probably related to issue 324 on mps github

**Comment by Solidflip** [comment]
Please test on the newest version

**Comment by Direcub10** [comment]
its fixed

**Comment by Solidflip** [comment]
AWESOME!!!!
