### ISSUE TITLE
Tech Reborn is unstable af

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#204]
http://pastebin.com/GrR4iFUp tried to place a dragon egg energy cyphon

**Comment by Solidflip** [comment]
uhh wrong pastebin? This is related to your other report about mps

**Comment by Direcub10** [comment]
No that one is from some bugger named machine mouse http://pastebin.com/dXL9CgvK

**Comment by Direcub10** [comment]
Ur the one who gets to break topless' heart

**Comment by Solidflip** [comment]
Mmmmm, might be related to the need for ic2.... As we dont have Ic2 prob cant have this mod lol.

**Comment by Direcub10** [comment]
this isnt a bug its a hard dependacies @mislabeled

**Comment by Solidflip** [comment]
fail

**Comment by Direcub10** [comment]
how so?

**Comment by Solidflip** [comment]
you closed it when it wasnt solved, tabs yells at me for that

**Comment by Direcub10** [comment]
forget yellling im still waiting on the conversation about rotarycraft between u and tabs :D

**Comment by Solidflip** [comment]
So i failed as well i misread this:
TechReborn is a resurrection of GregTech 4 for modern Minecraft. It brings most of GT4’s features and behaviours to Minecraft, with lots of tweaks, and a few editions. It also aims to be more compatible with other mods than GregTech, _and has the ultimate goal of becoming a standalone mod, compatible with but not dependant on IC2._
so its not YET a standalone, requires IC2 so unfortunatley we wont have it yet

**Comment by Solidflip** [comment]
Mod removed
