### ISSUE TITLE
Iguana Tweaks

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#205]
It was taken out bc it disabled normal tools including things like the terra shatterer. U can config to the mod to whitelist specific picks or just remove this nerf entiirely by change a config from TRUE to FALSE which takes all of 5 seconds.

**Comment by Solidflip** [comment]
Indeed i could, however that coupled with the config change to remove it removing modifiers seems as though we are disabling much of the mod. IMO why have it then? for extra modifiers? Were trying to make this pack not so easy (but not crazy) so it doesnt seem to fit in right.
