### ISSUE TITLE
test server/ meteors

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#206]
highly recommend turning the frequency of meteors down and the size of them , concerned about damage to map over long term

**Comment by Abouttabs** [comment]
Meteors from which mod?

**Comment by MrAtrophy** [comment]
"meteors" is the name of the mod. 
the meteors are destructive and do accumulate, they hit around characters in a given distance set in the config. in about two hours of testing I heard about 8. I am just concerned about the long term.

**Comment by Solidflip** [comment]
I have reduced the amount from 20/100 to 5/100. Let me know if this is low enough

**Comment by Solidflip** [comment]
Havent had a meteor crash around me a a couple hours now, good job solid

**Comment by Solidflip** [comment]
Thanks flip, issue closed

**Comment by dragonaslin** [comment]
your awsome you work very hard

**Comment by Solidflip** [comment]
I got something that's hard ifyaknowwhatimean
