### ISSUE TITLE
Fruit

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#207]
the fruit of grisillia wont work. ill eat it but it wont give me lamb chops

**Comment by Solidflip** [comment]
Probably related to hunger overhaul let me check it out

**Comment by Solidflip** [comment]
Well i was wrong, this is intended. You now must have a source of mana on you to use the fruit. This was recently added. Please test with the newest restart of the server.

**Comment by Solidflip** [comment]
Just tested and it works with the mana tablet.
