### ISSUE TITLE
Mouse dissappearing

### ISSUE THREAD

**Issue by scoobydoo192** [RTRGitHub/RTRRedux#208]
my mouse is gone in Journey map and in escape menu but its there in the inventory tad annoying moving the mouse around and waiting to see if its highlighting the thing i need.

**Comment by Solidflip** [comment]
THats weird? ill need a picture to see whats going on but i suspect this is on your side as no one else has had that issue

**Comment by scoobydoo192** [comment]
http://imgur.com/lylTiuz
http://imgur.com/eYN1iGx

**Comment by Solidflip** [comment]
Ill need to see what optional mods you added, or try re-installing. Im afriad this is an issue on your side but i want to get it fixed anyway.

**Comment by Solidflip** [comment]
Nope now im having it as well

**Comment by Solidflip** [comment]
Figured it out, DragonAPI update checker makes this issue occur, Just close the dialogue boxes in the top left corner and itll be back to normal

**Comment by Solidflip** [comment]
Issue fixed, updates will only occur to Ops, not regular members. Ops can simply close them
