### ISSUE TITLE
Atomic Science Plasma

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#21]
Upon server restart, its happened twice today, the plasma in my fusion reactor stops flowing. The plasma inside the actual reactor remains still. 

My way to fix this, have been to break a piece of electromagnetic glass and allow some of the water source blocks to leak into the chambers. The problem with this, is usually the plasma will spawn where i destroyed the glass, and above...causing a few fluid conduits and funnels to be destroyed in the process.

I honestly dont know what could fix this.

**Comment by Abouttabs** [comment]
My guess would be that it needs block update. Try applying redstone signal to one of the outer blocks first, that might cause the required block update.. Also I assume that it causes energy to stop being generated right? Well if that is the case and redstone signal helps you could make automated (it should be possible among comparator and BC gate, computers have issues with starting up upon restart..) that would shoot a rs signal when no power is being outputed... Just a guess, will look into it today and will see what can I find...
