### ISSUE TITLE
rotarycraft music box is bad

### ISSUE THREAD

**Issue by dragonaslin** [RTRGitHub/RTRRedux#211]
10:33:51 PM CONSOLE: WARN]: java.io.FileNotFoundException: .\world\RotaryCraft\musicbox@81,63,198.rcmusic (The system cannot find the path specified)
10:33:51 PM CONSOLE: WARN]: at java.io.FileInputStream.open0(Native Method)
10:33:51 PM CONSOLE: WARN]: at java.io.FileInputStream.open(Unknown Source)
10:33:51 PM CONSOLE: WARN]: at java.io.FileInputStream.<init>(Unknown Source)
10:33:51 PM CONSOLE: WARN]: at java.io.FileInputStream.<init>(Unknown Source)
10:33:51 PM CONSOLE: WARN]: at Reika.DragonAPI.IO.ReikaFileReader.getReader(ReikaFileReader.java:67)
10:33:51 PM CONSOLE: WARN]: at Reika.RotaryCraft.TileEntities.Decorative.TileEntityMusicBox.hasSavedFile(TileEntityMusicBox.java:290)
10:33:51 PM CONSOLE: WARN]: at Reika.RotaryCraft.TileEntities.Decorative.TileEntityMusicBox.onFirstTick(TileEntityMusicBox.java:104)
10:33:51 PM CONSOLE: WARN]: at Reika.DragonAPI.Base.TileEntityBase.updateTileEntity(TileEntityBase.java:568)
10:33:51 PM CONSOLE: WARN]: at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:453)
10:33:51 PM CONSOLE: WARN]: at net.minecraft.world.World.func_72939_s(World.java:2513)
10:33:51 PM CONSOLE: WARN]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
10:33:51 PM CONSOLE: WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
10:33:51 PM CONSOLE: WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
10:33:51 PM CONSOLE: WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
10:33:51 PM CONSOLE: WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
10:33:51 PM CONSOLE: WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by Solidflip** [comment]
I was in there when it threw this error, please include the whole thing, including the "item at blah blah blah is throwing error" stuff, And use pastebin for code

**Comment by dragonaslin** [comment]
i cant i crashed and lost everything butill add y whole consol

**Comment by Solidflip** [comment]
You crashed from this block? or something else? If you crashed from something else, just replace the music box to get the error again

I didnt crash when i was there btw, the item just throws an error (not enough to get rid of mod) <- thats for a certain someone

**Comment by dragonaslin** [comment]
music box for rotarycraft by spawn is throwing error messages      http://pastebin.com/S0FU2Rek

**Comment by Solidflip** [comment]
Might be fixed in the newest version, i will test that after i generate this new world. Though changelog doesnt say so

**Comment by Solidflip** [comment]
Issue not fixed but reported to Reika

**Comment by Solidflip** [comment]
Item removed from the world and made un-placeable. Issue solved for now until the code is rewritten by Reika
