### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by TheToplessGamer** [RTRGitHub/RTRRedux#217]
i was in my vanilla creative inventory and i accidentally mashed 2 keys and boop a wild crash appeared http://pastebin.com/Wb9yCMje

**Comment by Solidflip** [comment]
appears a problem with the guis, is this issue reproduceable? Might just be one of those things that rarely happens

**Comment by TheToplessGamer** [comment]
That what i told Scooby but she still told me to put it up but ill try to reproduce it tomorrow after I get some proper sleep

**Comment by Solidflip** [comment]
Mk, its always good to put up crash logs, this just happens to be one of those things that is just weird. But id rather have a log reported than not

**Comment by Solidflip** [comment]
Will close for now, if it happens again please reopen
