### ISSUE TITLE
Garden stuff

### ISSUE THREAD

**Issue by scoobydoo192** [RTRGitHub/RTRRedux#218]
Bloodwood post came out as oak post bloodwood fence also came out as oak unable to get the blood wood for some reason.

**Comment by Solidflip** [comment]
whats the item id for this item?

**Comment by scoobydoo192** [comment]
Mod garden trees 
Bloodwood post 2270:62384 
Bloodwood post fence 2271:62384

**Comment by scoobydoo192** [comment]
http://imgur.com/Fzb7Auy

**Comment by Abouttabs** [comment]
Ore dictionary strikes once again...

**Comment by Solidflip** [comment]
Reported to mod author will reopen when response is received
