### ISSUE TITLE
Hyrdolicraft crash

### ISSUE THREAD

**Issue by scoobydoo192** [RTRGitHub/RTRRedux#219]
http://pastebin.com/PQ7HHxgG was placing pipes

**Comment by Solidflip** [comment]
http://pastebin.com/Bmxt2R3u server side, ill look into this in the morning

**Comment by scoobydoo192** [comment]
Beleive it was the medium pressure valve 6777:1 item id

**Comment by Solidflip** [comment]
Appears related to issue https://github.com/K-4U/Hydraulicraft/issues/154. Will post log there to check, unfortunately it appears no fix incoming for a bit so ill have to remove the item or something

**Comment by Solidflip** [comment]
Blocks shouldnt be placed together (as in this doesnt make sense for the mod) so we will need to inform people not to do this. Will reopen when a fix comes out from hydraulicraft
