### ISSUE TITLE
Hydraulicraft copper ore drops apatite ore

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#225]
As seen in subject(tm)!

**Comment by Solidflip** [comment]
Which apatite ore? Whats the item ids?

**Comment by Volaunis** [comment]
Hydraulicraft copper ore : 2436
Forestry Apatite pre : 911

**Comment by Solidflip** [comment]
Reported to mod author, will await response

**Comment by Solidflip** [comment]
Will reopen when receive response from mod author
