### ISSUE TITLE
banned item?

### ISSUE THREAD

**Issue by KazandraJean** [RTRGitHub/RTRRedux#229]
item code 4745 in pams harvestcraft's grass gardens are popping up a banned item message. can we add those back in.

**Comment by KazandraJean** [comment]
pardon 5745

**Comment by KazandraJean** [comment]
also 5747 and 5744 are doing the same. all three are dropping from the grass garden looks like wheat, barley and bamboo

**Comment by Solidflip** [comment]
when i banned the items the ids must have changed ill fix this tomorrow

**Comment by Solidflip** [comment]
Fixed
