### ISSUE TITLE
sleeping above glitch

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#230]
at about 4:25 am central I (atrophy) fell through the world when sleeping. this seems like a conflict more than a clitch

**Comment by MrAtrophy** [comment]
looking at ATG there are two configs that need to be changed to make a playable map .

Multiplier for height generation  and Flat modifier to height generation. I think lowing both of these config values will produce a map with smaller peaks with and over all average height being much lower.  I hope I am wrong about all of this honestly.  because I do like the lay out of the map, I just wish it wasn't so high in most places

**Comment by MrAtrophy** [comment]
Multiplier for height generation  of .8 and Flat modifier to height generation of 0.05 seems to produce mountains in the 150's - 180's and produces much more flat land an small hills.  numbers lower than that seems to produce a pretty flat and low variety map. trying to help, still hoping I am wrong or there is a way to resolve the conflict with sleeping above 120.

**Comment by Solidflip** [comment]
The title says sleeping above, sleeping above what? Sleeping above a certain y level or?

**Comment by Abouttabs** [comment]
Restored the inventory

**Comment by Solidflip** [comment]
issue with vanilla minecraft that has been around forever, nothing i can do for this. Just dont sleep above y 120+
