### ISSUE TITLE
Coke oven

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#233]
the coke oven texture is fucked

**Comment by Direcub10** [comment]
http://imgur.com/fMRVwMD

**Comment by Solidflip** [comment]
Are you using optifine or not?

**Comment by Direcub10** [comment]
i regret nothing (yes)

**Comment by Solidflip** [comment]
Try without optifine

**Comment by Direcub10** [comment]
still waiting eh?

**Comment by Solidflip** [comment]
Issue related to optifine, runs fine without
