### ISSUE TITLE
tinkers silk touch isnt working

### ISSUE THREAD

**Issue by dragonaslin** [RTRGitHub/RTRRedux#234]
wont allow you to take it out of the crafting station and or dissaperes

**Comment by Solidflip** [comment]
will test in game in a min

**Comment by Solidflip** [comment]
Just tested in the server, it works. Make sure you have a silky jewel and a modifier available

**Comment by Solidflip** [comment]
Will need to change recipe with minetweaker

**Comment by Volaunis** [comment]
I beleive the issue with this was the desync between client and server configs. I have crafted it fine when using gold ingots for the silky cloth instead of nuggets.

**Comment by Solidflip** [comment]
Isue fixed, recipe should work now
