### ISSUE TITLE
blood bug

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#237]
putting an empty bucket into a fluid transposer on toggle:fill will result in infinte blood pretty sure it's a bug

**Comment by Solidflip** [comment]
Youre pumping blood into the transposer and putting it into a bucket? Is the bucket infinite or does the transposer not use blood to fill it?

**Comment by frogger35** [comment]
If you take a empty fluid transposer. Set it to fill its internal tank then put an empty bucket in. The transposed glitches out and gives you a blood bucket and fills its internal tank with 1 bucket of blood

**Comment by Solidflip** [comment]
Ahh i see, can you give me the item ids for the blood and blood bucket?

**Comment by frogger35** [comment]
Blood is 2016 blood bucket is 5645

**Comment by Solidflip** [comment]
Issue has been fixed, i removed all recipes in which you extract from an empty bucket (there were a few from evilcraft for some reason
