### ISSUE TITLE
Enderdragon destroys blocks and graves

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#238]
Basically the Ender Dragon killed me, destroyed the end stone my grave was on, destroyed the grave and all the items in it.

**Comment by Solidflip** [comment]
This is due to the dragon being able to destroy pretty much everything, Ill create a bedrock room for people to spawn in

**Comment by Souperhero** [comment]
I create a bedrock spawn at the /warp end. Still be prepared to get annihilated however.

**Comment by Solidflip** [comment]
TY soupy poo
