### ISSUE TITLE
Diamond Seed (Magical Crops)

### ISSUE THREAD

**Issue by CalenMC** [RTRGitHub/RTRRedux#24]
I made a diamond seed, which cost me 36 diamonds (and 4 extreme essences).
I planted it and the first harvest yielded 1 diamond essence.
You need 8 diamond essences to craft one diamond.

36 diamonds used to craft first seed.
288 (288/8=36 essences needed to get the initial investment back.

I'm assuming MFR planter/harvester combo works on this. And it might have a 3% chance to drop a bonus seed on harvest?
But even then, it still seems exceptionally harsh.

True, once I get a few 'procs', it'll significantly improve. But the initial startup time is not quite funny.

**Comment by Abouttabs** [comment]
We have doubled the output of crafting (2 seeds instead of one..) and bumped up the chance to get second seed to 10%..
