### ISSUE TITLE
Graves Not Saving Modular Armor and Tinkers Tools

### ISSUE THREAD

**Issue by PlasmaticPi** [RTRGitHub/RTRRedux#240]
While exploring the nether at 3:10am central time I was two shot from behind by a zombie pigmen. When I made it back to where I died I broke open my grave and all that came out was my baubles and my title scroll. The rest of my inventory, including a full set of modular armor, power fist, reusable safari net, and tinkers tools were lost as well as various other things not of importance. This is the second time this has happened, the first being when I went into the end to try and get some enderpearls and was one shot by the ender dragon as I was running away from him. When one of the mods helped me get to my grave all that had come out was the rings and he had to try and use commands to get my stuff back, though only some came back ad the rest he had to manually spawn in. I heard someone mention that sometimes items with high amounts of meta data stop the grave from being able to save the data, which seems plausible. This needs to be checked into before it happens to someone else, and if that hypothesis is correct people need to be warned about it so they can try and steer away from the modular armor.

**Comment by Solidflip** [comment]
Issue has been reported to openblocks, do you still need the items refunded?

**Comment by Solidflip** [comment]
Issue closed until response from ob

**Comment by Solidflip** [comment]
issue resolved, all items should drop now regardless of pvp or not
