### ISSUE TITLE
Unstable ingots not working properly

### ISSUE THREAD

**Issue by torsteig** [RTRGitHub/RTRRedux#241]
Unstable ingots do not turn reddish and stays in graves after death. The / by diamond explosion also destroys items (If this is not intended I lost a fair bit of my gear). 

The ingots were crafted in bunch (shift clicked).

**Comment by Solidflip** [comment]
Do the ingots explode once you open the grave?

**Comment by torsteig** [comment]
The ingots explode upon pickup from the graves yea.

**Comment by Solidflip** [comment]
Mk so they are working as intended, they dont explode when in the grave probably as they arent registering "being alive" if you know what i mean. Also the explosion destroying items is working as intended. I will look into the grave issue but as for now this isnt an issue as much as a weird death.
