### ISSUE TITLE
master ritual stone ---Blood magic

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#243]
When you go to activate a master ritual stone it goes poof and disappears the ritual says it's activated and all the text and particles show up but it doesn't actually activate the ritual. What's up with this? we don't know. The master ritual stone is the central block in the multi structure rituals so it going poof is bad. The other ritual stones stay except for the master.

Master ritual stone ID: 1110.

**Comment by Solidflip** [comment]
Ritual doesnt work after stone disappears, blood is used up.

**Comment by Solidflip** [comment]
By any chance, is this inside a claim? If so try outside one

**Comment by frogger35** [comment]
tried it outside a claim, in a single player world, in a different dimension same thing happens

**Comment by Solidflip** [comment]
Will investigate tonight when i get on

**Comment by Solidflip** [comment]
Issue reported to blood magic github, will await answer

**Comment by frogger35** [comment]
went into single player removed sanguimacy and blood magic worked

**Comment by Abouttabs** [comment]
Solved in version 1.0.5
