### ISSUE TITLE
unstable ingots

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#244]
Unstable ingots don't go away after you die from picking them up they also stay in your grave inventory
this results in constant death

Side note: Can't craft the unstable axe

**Comment by Solidflip** [comment]
related to #241 . ingots explode once the grave is opened thereby killing the player again.

**Comment by Solidflip** [comment]
Issue has been reported to openblocks. Will await their response. Until then just break the grave from a distance.

**Comment by Solidflip** [comment]
Also what do you mean you cant craft the axe? no recipe or?

**Comment by frogger35** [comment]
there is a recipe but it can't be crafted in a normal crafting bench haven't tried other ways of crafting but i believe it's cause of the ingot issue. Haven't tried stable ingots either

**Comment by Solidflip** [comment]
AS in you cant take the item out of the crafting grid? Try with the stable ingots if you can

**Comment by frogger35** [comment]
item doesn't show up in product slot of the crafting grid when items layed out in 3x3

**Comment by frogger35** [comment]
stable ingots worked

**Comment by Solidflip** [comment]
Will fix tonight

**Comment by Solidflip** [comment]
Axe was able to be made with the materials fine, if stable ingots work fine then just use those for now
