### ISSUE TITLE
Mining World

### ISSUE THREAD

**Issue by Avenessa** [RTRGitHub/RTRRedux#245]
Warped to mining world using /warp mining. Took screen shot, returned immediately to over world.
![2015-10-13_16 02 51](https://cloud.githubusercontent.com/assets/15100314/10445988/90a66ebe-71c5-11e5-8c83-5fc0389e2ac0.png)

**Comment by Solidflip** [comment]
Someone spawned a mega sapling, ill fix this tonight

**Comment by Solidflip** [comment]
Issue resolved
