### ISSUE TITLE
Tinkers' Bedrock axe

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#246]
Recipe in the Blast furnace doesn't work to make the parts

Went to test it anyways, bedrock tools (not bedrockium) break after 1 use, despite infinite durability

**Comment by Solidflip** [comment]
youll have to show me this ingame dude, ive never played rotarycraft much

**Comment by Camtoe112** [comment]
Sounds good, whenever you're available. Its not urgent by any means at all.

**Comment by Solidflip** [comment]
Just crafted the regular one in the blast furnace just fine, bedrock tool did not break after one use.

**Comment by Direcub10** [comment]
i think he means teh tinkers ones solid we tested the rotarycraft oness..... u make the pars in the blast furnace  as with with 4 bedrock dust and the HSLA steel equivalent part

**Comment by Direcub10** [comment]
I just made all the parts for the pick except the head bc it wont smelt in the blast furnace....im fairly pist that i did rotarycraft for nothing

**Comment by Solidflip** [comment]
its pissed btw, And i will investigate

**Comment by Direcub10** [comment]
Thanx m8

**Comment by Solidflip** [comment]
Found out the problem, these tools have been disabeled by Reika himself, Refer to issue 218 on https://github.com/ReikaKalseki/Reika_Mods_Issues. Also before you ask, no there is not a config option i checked.

**Comment by Solidflip** [comment]
By these tools i also mean the mattock and other tools for which rotarycraft adds a substitute
