### ISSUE TITLE
Loot Bags Being Nerfed Is a Bad Idea

### ISSUE THREAD

**Issue by PlasmaticPi** [RTRGitHub/RTRRedux#247]
I recently heard from mods and admins on the server that loot bags are going to be nerfed. It has been said that the people making this decision are people who have not even played on the server much, if at all. Knowing this, I am hear to complain that they should not be nerfed for any reason. The stuff you get out of them usually sucks and you have to go through tons of them to get anything good. And if they are being nerfed because of the issue that happened with the sacred rubber tree, then just ban sacred rubber tree saplings. Either way, there is no reason to nerf them because they are underpowered as it is and if you don't believe me go on the server and spawn in 100 of them to open yourself and see all the junk you get out of them. Or just ask people actually playing on the server about the issue and they will agree with me.

**Comment by Solidflip** [comment]
This was a proposed change by me (BTW i do play on the server). I stated that i needed to look into it to see if the drop rate was equal to the amount of bags gotten by the mob farms. In no way did i insinuate that i would change them without research first.

After looking at the drops given by the bags i have decided not to change the drop rate as they are pretty terrible.

**Comment by Solidflip** [comment]
Issue closed as proposed change has been decided against.
