### ISSUE TITLE
Add minetweaker support for TYNKYN saplings.

### ISSUE THREAD

**Issue by torsteig** [RTRGitHub/RTRRedux#248]
Would it be possible to use minetweaker(recently added) to add compatability for TYNKYN saplings for the MFR harvester/planter and enderIO farming station? Currently they are not registered as plantable.

http://minetweaker3.powerofbytes.com/wiki/Mods:MFR_Support (MFR howto)
(I have not found any minetweaker examples for enderio farming station)

Hippo

**Comment by Solidflip** [comment]
Will look into this

**Comment by Solidflip** [comment]
Support added for the three saplings
