### ISSUE TITLE
Blackout curtains gives wrong amount

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#249]
As the title says, i only get 1 blackout curtain per 6 wool, instead of either 12 or 16 (can't remember exaclty how many it is). I assume this was an oversight when changing the recipe in minetweaker.

**Comment by Volaunis** [comment]
ftpwiki says it's 12 per, btw.

**Comment by Solidflip** [comment]
Yup, my bad, will fix when i get home sunday

**Comment by Solidflip** [comment]
Fixed
