### ISSUE TITLE
Power output multiplier for big reactors..

### ISSUE THREAD

**Issue by Abouttabs** [RTRGitHub/RTRRedux#25]
We might want to bring multiplier for power output of big reactors down a little (In monster its 1.6 we have 3..)

**Comment by UnsungCesspool** [comment]
So with my reactor, 7x7x7 w/ Liquid Ender only...@ 3x im producing 6000RF/t which is equal to 75  TE dynamos. With a power multiplier nerf to 1.6, 6000RF/t goes down to 3100-3200RF/t, which is about equal to 40 TE Dynamos.

Thats quite a substantial nerf, and doing so would force people back to "normal" conventional means of power generation (dyanamos, engines, steam, generators, etc.). I mean, as i've said before, everyone wants to be a little bit OP. Thats what makes this game fun. To me, nerfing this multiplier -that much- would put big reactors in the same category as atomic science, in the "why both" category as there are better alternatives.

Ill be honest, I would rather fork out the materials for 75 magmatic dynamos than the steel/hardened glass needed for a 7x7x7 again as imo, its cheaper. 

Edit: Heres a few more numbers.
@2x Multi: 3900RF/t
@2.45 Multi: 4800RF/t

**Comment by Abouttabs** [comment]
That was not saying hey lets drop it 1,6 I was just comparising our setup to FTBs...
Was just saying hey lets look into this as it might be more powerful than it should..

**Comment by UnsungCesspool** [comment]
The power multiplier, imo, could use a slight nerf but please keep in mind that any nerf may or may not impact people's opinion on using the mod. For example, I think im the only one using Atomic Science Reactor turbines as of right now, after the nerfs to them in the universal configs. Even so, im thinking of scrapping the Atomic Science fusion reactor for something more productive.
