### ISSUE TITLE
Veinminer

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#250]
Can't vein mine Nether quartz ore with a Wyvern or tinkers pick.

**Comment by Solidflip** [comment]
Can they mine other ores? or are these tools unable to vein mine?

**Comment by Camtoe112** [comment]
Seems to just be this nether quartz ore only, for me

On October 18, 2015, at 7:08 PM, Solidflip notifications@github.com wrote:

Can they mine other ores? or are these tools unable to vein mine?

**Comment by Solidflip** [comment]
Just tested with both wyvern and a tinkers pick, both worked. Make sure you are using the correct key?

**Comment by Solidflip** [comment]
Make sure youre not using the wyvern as 3x3 and itll work
