### ISSUE TITLE
Rotarycraft Recipe conflict - wood gear and oak wood lattice

### ISSUE THREAD

**Issue by MrChunks** [RTRGitHub/RTRRedux#251]
The Rotarycraft recipe for "Wood Gear" is conflicting with "Oak Wood Latice" from Garden Stuff mod

The recipe is really basic: http://ftbwiki.org/Wood_Gear_(RotaryCraft)

**Comment by Solidflip** [comment]
Will fix tonight

**Comment by Solidflip** [comment]
Bit of a weird fix, but itll work
