### ISSUE TITLE
Soul Bound and Gravestones Bug

### ISSUE THREAD

**Issue by Icehornet** [RTRGitHub/RTRRedux#255]
An issue has occurred where soul bound items are not being saved to the player on death, nor going into the gravestones from extra utilities.

**Comment by Icehornet** [comment]
Addition - This issue seems to only happen during PvP

**Comment by Camtoe112** [comment]
A suggestion, avoid PvP.

**Comment by Solidflip** [comment]
When you are able to, attempt this again, i might have fixed it. (test with only crap like dirt in your inv though)

**Comment by Solidflip** [comment]
Issue fixed, tested during mob arena event
