### ISSUE TITLE
Magical wood Extra Utilities

### ISSUE THREAD

**Issue by torsteig** [RTRGitHub/RTRRedux#262]
It seems like the magical wood recipe produces one magical wood with any book whatsoever. I've tried using Flim Flam IV, which should give 14 magical wood, it gave 1. I made 4 lvl 30 enchants using the Auto-Enchanter from MFR, still gave me 1 magical wood. 

I believe that this is unintended behavior. Is there an easy fix for this?

Hippo

**Comment by Solidflip** [comment]
Issue related to Forge messing with the ore dict. This was related to an issue with reactorcraft, but was fixed in the last version. Im going to update the mods and see if this issue is resolved. Otherwise, just use the lvl 1 enchants though that will be annoying for crafting.
