### ISSUE TITLE
Crash with blst furnace

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#264]
I was looking for the bedrock head recipe in the blast furnace and on the 56th page i crash when i click into it

**Comment by dragonaslin** [comment]
need a crash log bro

**Comment by Direcub10** [comment]
I had it on my clipboard....wow what a blank out http://pastebin.com/6gqh93cU

**Comment by Solidflip** [comment]
This is a crash with rendering a certain fletching, and is related to NEI/Tinkers. What were you trying to do? just look up bedrock and youll see the head. This will require a mod update to fix, and even then it isnt promised.

**Comment by Solidflip** [comment]
TConstruct updated, i went through the recipes just fine, issue resolved.
