### ISSUE TITLE
Thaumcraft golemancers bell crashes client

### ISSUE THREAD

**Issue by dragonaslin** [RTRGitHub/RTRRedux#265]

**Comment by dragonaslin** [comment]
when crafting

**Comment by Solidflip** [comment]
Could you please provide the logs on the client when this happens?

**Comment by Abouttabs** [comment]
I have dealt with it before and is known issue with thaumic horizons, just
ask mod or admin in game to spawn it in please...

**Comment by torsteig** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2361575-thaumic-horizons-v1-1-6-thaumcraft-4-addon?comment=215 

Comment with the same issue.

**Comment by Direcub10** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2361575-thaumic-horizons-v1-1-6-thaumcraft-4-addon?page=12
Seems like forge is having problems with letting TH overide the bell

**Comment by Solidflip** [comment]
Will attempt to update forge tonight to see if that fixes the issue.

**Comment by dragonaslin** [comment]
still crashes and pastebin is broken at this time but will do

**Comment by dragonaslin** [comment]
http://pastebin.com/mTNLLQFc

**Comment by Abouttabs** [comment]
When exactly does that happen? Also please submit crash log if one is
created rather than console log if possible next time, it has way less
unnecessary stuff in it. Thank you

**Comment by Solidflip** [comment]
Yeah please provide the crash log itself if one generates. If it does not and this issue only occurs upon logging in, Please fire up MC, then before you log in clear the console and give us that after you crash. That way i dont have to read your pre-init and init stages =P
