### ISSUE TITLE
Crash with Magneticraft Infinite water

### ISSUE THREAD

**Issue by torsteig** [RTRGitHub/RTRRedux#268]
Right clicking on a Infinite water block from Magneticraft causes a CTD. Unhandled exception.

http://pastebin.com/MXN0w66p

**Comment by Solidflip** [comment]
This is a known issue in magneticraft, It should be fixed in the next version. Will close this until it updates. The beta version was releaed today so according to the mod authors pattern of releases it should only be a few days
