### ISSUE TITLE
Draconic Armor banItem

### ISSUE THREAD

**Issue by torsteig** [RTRGitHub/RTRRedux#269]
When crafting draconic armor, it is removed from the inventory when handled, because of pending recipe changes. Afaik, the recipe has already been tweaked. Is the current recipe the final?

Hippo

**Comment by Solidflip** [comment]
mmmm thats it, ill fix that asap and get those items back to you

**Comment by Solidflip** [comment]
Items have been removed from the ban list, Pleas get with a mod or admin to get the items refunded =)
