### ISSUE TITLE
opengl error 1281

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#270]
when using lexica botania there is a repeating opengl error 1281 , verified by another player using it.

**Comment by Solidflip** [comment]
gonna need logs yo

**Comment by MrAtrophy** [comment]
no crash , no logs,  just spam in the chat when you have a botania book open.

**Comment by Solidflip** [comment]
In game chat? or console chat?

**Comment by MrAtrophy** [comment]
in game chat

**Comment by Solidflip** [comment]
Ok please take a screenshot of the text so i know whats going on

**Comment by Solidflip** [comment]
issue no longer present, will re-address if it pops up again
