### ISSUE TITLE
Pseudo-Inverson Sigil not crafting stable unstable ingots

### ISSUE THREAD

**Issue by torsteig** [RTRGitHub/RTRRedux#271]
As per title, when crafting unstable ingots using a pseudo-inversion sigil, I get unstable ingots that explode, instead of the stable ones as it should produce. 

Hippo/iPPoe

**Comment by Solidflip** [comment]
Issue has been fixed, The mobius ingot now requires 2 iron side be side to be crafted. http://i.imgur.com/3xHCJtA.png?1 shows an example
