### ISSUE TITLE
Purifier from evilcraft

### ISSUE THREAD

**Issue by madbrainsurgeon** [RTRGitHub/RTRRedux#275]
Purifier from evilcraft not working put armor piece in put blook in put blood in and booom nothing happened

**Comment by dragonaslin** [comment]
i just tried it and it worked. did you make sure it was full all the way with blood and put the armor piece in first before you clicked the blook on top of it?

**Comment by madbrainsurgeon** [comment]
yep did that even picked it up and placed it down again, will try again
today

**Comment by madbrainsurgeon** [comment]
nope still not working for me
