### ISSUE TITLE
Railcraft rails

### ISSUE THREAD

**Issue by madbrainsurgeon** [RTRGitHub/RTRRedux#276]
Are rails actually makeable as the nei recipe takes you round in circles

**Comment by dragonaslin** [comment]
what ones

**Comment by dragonaslin** [comment]
the wooden ones are made with creosote oil and wooden slabs, anything using a steel rail, you will have to either find track in mines and or make the track using aura craft.

**Comment by dragonaslin** [comment]
The creosote is made with coke oven by the way

**Comment by dragonaslin** [comment]
The wooden ones are made with creosote and wood slabs, and the ceosote is made from coke oven.

If the steel rails is what your after the standard steel rails have a recipe that is made with steel and in a rolling machine shown here http://imgur.com/id2Vhcx .
