### ISSUE TITLE
Turtles

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#278]
Cannot craft specialty turtles.

Diamond Pickaxe + Advanced turtle =/= Mining turtle

etc.

**Comment by Solidflip** [comment]
This isnt as big an issue if you know computercraft. Turtles can equip items (thats what a mining turtle is, a turtle with a pick equiped) Normally you do this through crafting but it can be done in another way.

First name your turtle (label set <name>)
Then place the item in the first slot of its inv (in our case a pickaxe)
then run command equip <slot> <side>
http://imgur.com/QZdfxUi
then hit enter (all must be lowercase, its upper in the pic but thats wrong) and your turtle will equip the item.
http://imgur.com/G4DRK1l

you can also run unequip to take the item off if say you no longer need a mining turtle but want a farmer instead.
