### ISSUE TITLE
Repeating Server Crash

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#280]
I set an Agricraft Seed Analyser on top of a hopper which was pushing seeds into a Agricraft Seed Storage.
The server crashed as the first seed that was running though the hopper.
Accidently had a Chunkloader activated so the server was reloading an crashing until all 21 Seeds were gone.
Replacing the Seed Storage with a normal Chest solved the problem. 

This is causing the issue:
https://github.com/InfinityRaider/AgriCraft/issues/448

Replacing the Seed Storage with a normal Chest solved the problem.

**Comment by dragonaslin** [comment]
The problem was actually with the hopper and is actually fixed withthe next update

**Comment by Solidflip** [comment]
issue fixed
