### ISSUE TITLE
Spawn claims

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#283]
Can we unclaim all chunks at spawn and set it as a zone instead, that way people can use doors/trade o mats, etc at spawn, with out being able to grief it?

Thanks beb

**Comment by Solidflip** [comment]
i will add a recipe for the un-craftable tools rather than uncliming chunks

**Comment by Solidflip** [comment]
Soup could you post the tools that need to be craftable?

**Comment by Camtoe112** [comment]
Stone Sword: 272

**Comment by Solidflip** [comment]
will fix sunday

**Comment by Solidflip** [comment]
Issue fixed, stone sword are now craftable, thanks dragon
