### ISSUE TITLE
crashing when logging in (this is for a friend) 

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#284]
http://pastebin.com/VaryGj6f

EnderIO: Found the following problem(s) with your installation: "An unsupported old RF API is installed (1.7.10R1.0.0 from funky-locomotion-1.7.10-beta-7.jar). Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

if thats the issue how do i fix it for him and wouldnt we all have that issue?

**Comment by Solidflip** [comment]
player was not whitelisted, issue fixed
