### ISSUE TITLE
MFR planter and Biomes o Plenty saplings

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#285]
the MFR planter will not recognize and plant biomes o plenty saplings, I was trying fir and it would not work

**Comment by Solidflip** [comment]
I will add the trees in the morning. COuld you post what trees you need?

**Comment by MrAtrophy** [comment]
i was trying the fir tree thats the one i can test the quickest to see if it config change worked

**Comment by Solidflip** [comment]
Issue fixed by dragon
