### ISSUE TITLE
Security station

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#286]
The recipe for the security station needs an ME chest. In order to make a chest u need a quantum core. This is to prevent ppl from using ME until end game. however, this is a ridicoulous recipe for someone who jsut want their wireless terminal to work. i suggest we change the recipe for the station to need a basic chest so that u dont need 2 stacks of iridium to secure ur me system

**Comment by Solidflip** [comment]
All recipes that work will be kept. This recipe is used to gate AE behind the ability to have a good amount of resources. You could find another way to secure your base, such as password computers etc.
