### ISSUE TITLE
Chunkloading Issues with Ender IO

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#287]
I just searched for the reason why sometimes my Ender io Power Monitor isnt updating when i m not on the server / away from my base. 
I found some issues who can affect the server performance.

Typical Case:
All my chunkloaders are turned off. My two Ender IO capaciators are half full. I leave the server.
When i come back the capaciators are full.
So two things went wrong:
- The Power monitor should have switched on and drain the energy into my quarry.
- It was chunkloaded.

I think one of this could cause it:

Conduits loading neighboring chunks even if not doing work
https://github.com/SleepyTrousers/EnderIO/issues/2673

It says "Code Complete", but I m not sure, if it this bugs are fixed in our curren version:

Wireless Charger forcing chunks to stay loaded when powered
https://github.com/SleepyTrousers/EnderIO/issues/2671

Power Monitor not updating when offline on a server
https://github.com/SleepyTrousers/EnderIO/issues/2055

**Comment by Solidflip** [comment]
ok, is there some issue on the server you need help with? Or is this just an FYI?

**Comment by Abouttabs** [comment]
Ok, something might work only when player is nearby, I think it could be
me, so it might be sending the power, but it could be stuck because quarry
can't deposit those items cause me is offline? I remember this issue from
back in the 1.4.7 where my boilers used to go dry because me wasn't paying
mats into fermenters when loaded with something not using fake player

**Comment by EndEnemy** [comment]
It's just FYI, i m not using these machines anymore untill i m sure its fixed.

**Comment by Solidflip** [comment]
Ok sorry tabs and end, im not following the problem here. Is the problem that when your base isnt chunkloaded your quarry which is chunkloaded stops? 

Also tabs...i didnt understand that comment at all dude lol

**Comment by Solidflip** [comment]
Will keep an eye on the lag and see if it is generated in these circumstances. As it stands none is noticeable. No issue present at base, simply an FYI about possible cause for lag
