### ISSUE TITLE
Forcibly disconnected from server ever so often

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#288]
Hello,

Within the last 2-3 days, i have been getting random disconnects.
The message in the log is : http://pastebin.com/2pexW847
I just now had it happen again at 02:40 CET.
Any idea what's causing the server to kick me off?
It's apparently completely random what i'm doing, and where i am.

**Comment by Solidflip** [comment]
Sorry i was on vaca, is this still an issue? If so ill need the full log please.

**Comment by Solidflip** [comment]
issue no longer present, reopen if it occurs again

**Comment by Abouttabs** [comment]
rTr was targeted in DDOS attacks over Christmas break, might have been
that..
