### ISSUE TITLE
minecraft.righttorebel.net points to the wrong IP address

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#289]
It points to 74.91.126.213, at least currently.

**Comment by Volaunis** [comment]
Further investigation indicates that the minecraft subdomain is gone, so it just resolves to whatever righttorebel.net points to.

**Comment by Solidflip** [comment]
for now use the ip, we will resolve this asap

**Comment by Solidflip** [comment]
Paf submitted

**Comment by Solidflip** [comment]
DNs has been fixed, could take about 24 hours to work correctly
