### ISSUE TITLE
Add mattlock as veinminer tool

### ISSUE THREAD

**Issue by Stadniuk** [RTRGitHub/RTRRedux#29]
So we can use it to chop down trees (ID: 14316)

**Comment by UnsungCesspool** [comment]
I disagree with adding the mattock as a veinmining tool. If it was, there would be no point to the shovel, or the hatchet. I think the trade off comes with the fact that you have 3 tools in one with the mattock.

**Comment by Stadniuk** [comment]
I think that's a good point. Still we can add it only as an axe, and not as a shovel, it wouldn't impact the gameplay

**Comment by Stadniuk** [comment]
Plus, just realized you can shift-click with your barehand and still works, so there is no much point on not adding the veinminer, if you can do it with the hand

**Comment by kenny608uk** [comment]
That shouldn't be possible stad and regardless won't make a difference with ores etc. I'll check the config later regarding the fist.
Apart from that I agree with cesspool regarding it.

**Comment by Stadniuk** [comment]
note, it was not with the had, it was with a fence in the hand (bug?)... 
In the other hand, it can be done: "add item as an axe"
