### ISSUE TITLE
server shutdown...

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#292]
11:30am...the server shut off...it wasnt a normal reset cause that happened half hour before this

**Comment by icha-senpai** [comment]
it came back up

**Comment by Abouttabs** [comment]
It was crash due to itemduct, if it happens again we'll have to remove
offending block from world via mcedit... Also from the log it seems like it
was trying to send stuff into unloaded chunk

**Comment by icha-senpai** [comment]
ok cool thxs for the quick response...if it happens again ill report back
