### ISSUE TITLE
Spirit spawn rate

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#293]
In witchery theres a dream dim that spawns things that you can only get in the dream. Among these
things are spirits. Ive searched perhaps 500+ chunks trying to find 1 of the 30 i need for what im doing. Can you please increase the spawn rate in the config

**Comment by dragonaslin** [comment]
are you looking for the spectral dust

**Comment by Direcub10** [comment]
np spectral dust drops rarely from skeletons and the like. u get  a subdued spirit when u kill a spirit
and i need 30 if these to make 6 spectral STONEs

**Comment by Direcub10** [comment]
http://imgur.com/iXUd8Bd these are what im looking for

**Comment by Direcub10** [comment]
bump

**Comment by Solidflip** [comment]
will update this issue in the morn

**Comment by Solidflip** [comment]
will be changed when the dims are reset

**Comment by Solidflip** [comment]
Spirirt spawn rate has been doubled
