### ISSUE TITLE
My baba yaga disappeared

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#296]
I got a boss mob from witchery to spawn(which is intensely difficult and annoying to do for this boss). Me and finepoints went to spawn to fight her and GDWgaming watched us. when we got to about 2/5
health we both step back to regen and she started to walks a little to the side and disappears. no particles nothing. like she despawned. the main reason why i want to kill her is bc she drop a rllt nice hat from witchery called Baba yaga's hat. her disappearing is not supposed to happen. If it would not be to much trouble could one of the admins spawn another for us or better yet just give me the hat since me and fine fought her and woulda killed her if she hadnt dissapeeared

**Comment by FinePoints** [comment]
Right! It was a epic battle that could not be finished! :(

**Comment by Solidflip** [comment]
This was due to cofh killall, tomorrow i will spawn it for you.

**Comment by Direcub10** [comment]
Dragon got it
