### ISSUE TITLE
Thaumic Warden

### ISSUE THREAD

**Issue by FinePoints** [RTRGitHub/RTRRedux#297]
It's been within the week someone put a Thaumic Warden on my elevator.-173 -154 If this could be fixed that be awesome!

**Comment by Direcub10** [comment]
um..........thaumic warden is a mod m8 u mean a ward from the ward focus,,,,,,,

**Comment by Abouttabs** [comment]
Just ask mod or admin in game, they can punch it, but kudos for using
tickets properly

**Comment by Solidflip** [comment]
ikssue fixed
