### ISSUE TITLE
Spirits dont seem to spawn at all

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#299]
after flip doubled to spirit spawn rate i went back to the spirit world and looked for about an hour and still didnt find any. i dont think its a problem with their spawn frequency but instead they arent spawning at all. idk why or whats stopping them but i need like 30 and maybe a little more to progress in witchery. Itd be nice if one of the admins could just give me some until we figure this out

**Comment by Solidflip** [comment]
Will investigate

**Comment by Solidflip** [comment]
spawnrate increased from 1 to 5. reopen if this problem persists
