### ISSUE TITLE
Ore Generation

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#3]
Can we set up the configs so only one mod version's basic ores generate? IE. Copper, Tin, Iron, Silver, Gold, etc.

Having multiple mods producing different basic ores is counter-productive, especially when each ore can have a different hardness. IE. TE's Silver needs an Iron Pick. Metallurgy's Silver needs only a Stone Pick.

I think by streamlining this ore generation would be very help ful.

P.S...I say go with TE's ore generation

-Cess

**Comment by kenny608uk** [comment]
Honestly while this is a problem, disabling all but one mod versions of basic ores is a _bit_ risky, as we may end up with problems where recipes dont recognise them.

**Comment by Abouttabs** [comment]
And giving the derpines of ore generation we would need to set up completely custom ore generating rules,  and even then its risky. Also mystcraft can be all like screw your rules anyway...

**Comment by UnsungCesspool** [comment]
To answer you Kenny, that may not be neccesarily true. Each mod has different ways of grinding said ore to double it. When doing so, 9/10 times that machine, from some random mod, will turn the dust of a basic ore to its own version.

And not true on Mystcraft. Mystcraft can follow said rules. For instance. I believe RR uses purely TE's version of ores...

**Comment by kenny608uk** [comment]
Since apparently the oregen is still occuring despite being disabled I'm going to put this down to metallurgys derpy oregen changes.
