### ISSUE TITLE
Soup's idea for more creative recipes

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#302]
Soup said made a topic or creative things we want  a recipe for so mine is that i want the creative wand make it so that it needs the max amount of vis possible without it being unmakeable (max discounts ect.) and make it cost 3 ichor wands and 2 dragon hearts with creative mana pools in the corners

if any one else has an idea pls post below

**Comment by Solidflip** [comment]
im not to sure about this....but if you guys can send me a grid of the items you suggest, ill add it to the game if we can balance it.
[item, item, item]
[item, item, item]
[item, item item]

**Comment by Direcub10** [comment]
creative mana pool, dragon heart, creative mana pool
ichor wand, ichor wand, ichor wand,
creative mana, dragon heart, creative mana

**Comment by Solidflip** [comment]
I will do some testing later, either add a recipe or i might just enable the normal way you get this.

**Comment by frogger35** [comment]
with this can we also get more items in liquid form? Examples being awakened draconium, terrasteel, electrical steel, and vibrant alloy

**Comment by Direcub10** [comment]
it seems he plans to make a tank for each fluid in the game )_)

**Comment by torsteig** [comment]
ExtraTic has some of the metals in fluid form already, but there is  no known way of melting them down atm. Vazkii (botania) does not like the thought of molten mana metals, and might have put some code to catch Minetweaker scripts doing this.

https://www.reddit.com/r/feedthebeast/comments/3ct5yh/molten_terrasteel_infinity_162/ct8f4e2 (minetweaker recipes for different metals)

**Comment by Direcub10** [comment]
aww but i like molten terra steel :D

**Comment by Solidflip** [comment]
yyyeeeeeaaaahhh, im not doing the MT to make more liquids so you can have all the end-game mats for free.. Will reopen this issue once i find a recipe worth making this wand

**Comment by EndEnemy** [comment]
So I made some scripts. Anyone want to test them? :P


[RtR_Tweaks.txt](https://github.com/RTRGitHub/RTRRedux/files/86358/RtR_Tweaks.txt)

**Comment by EndEnemy** [comment]
I made some scripts. Does anyone want to test?

[RtR_Tweaks.txt](https://github.com/RTRGitHub/RTRRedux/files/86361/RtR_Tweaks.txt)

Edit: I added recipes for:
- Tinkers Creative Tool Modifier
- Dragon Heart
- Thaumcraft Ochalcum Wand & Staff
- JABBA Creative Upgrade (Barrel)

Just rename the .txt data to .zs and add it to 
AppData\Roaming\FTBInfinity\minecraft\modpack\expert\scripts

**Comment by Solidflip** [comment]
could you put those in item names so i dont have to load a game to see them?

**Comment by EndEnemy** [comment]
Updated:
[RtR_Tweaks.txt](https://github.com/RTRGitHub/RTRRedux/files/87077/RtR_Tweaks.txt)

This code should be better to read
(I also added the variables to the script)

Dragon Heart:
    [ChargedDrac, ChargedDrac, ChargedDrac],
    [ChargedDrac, ResurrectionSto, ChargedDrac], 
    [ChargedDrac, ChargedDrac, ChargedDrac]

CreativeToolModifer:
    [GreenHeartCan, GreenHeartCan, GreenHeartCan], 
    [GreenHeartCan, DraconicEvolution:awakenedCore, GreenHeartCan], 
    [GreenHeartCan, GreenHeartCan, GreenHeartCan]

Orichalcum Wand:
    [ForbiddenMagic:EldritchOrb, 64kEssentiaStor, ThaumicExploration:necroStaffCore], 
    [TConstruct:creativeModifier, VoidStaffCore, 64kEssentiaStor], 
    [DreamwoodStaffCore, TConstruct:creativeModifier, CreativeMana]

Orichalcum Staff
    [ForbiddenMagic:EldritchOrb, 64kEssentiaStor, ThaumicExploration:necroStaffCore], 
    [TConstruct:creativeModifier, VoidStaffCore, 64kEssentiaStor], 
    [DreamwoodStaffCore, TConstruct:creativeModifier, CreativeTank]

Creative Barrel Upgrade: (i m not sure about this at time)

4 CreativeManaPools
288 of each ForbiddenMagic Shard (maybe more?)
4 GaiaHeads (maybe more?)
4 Diffrent Forestry Woods (the recipe just looks cooler)
Infinity Bee

**Comment by EndEnemy** [comment]
I would update the Creative Barrel Upgrade to maybe 1k of each Forbidden Magic Shard and 16 gaia heads, anymore suggestions to make this recipe a real pain?

**Comment by Solidflip** [comment]
Some of these will be given out as rewards, others were waiting on mods to add the bosses that will give those (forbidden magic will handle the ichorium wither that gives you the wand)
