### ISSUE TITLE
Afk kicking

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#303]
Whenever i sit at my thaumcraft research table and try to finish this research i keep getting kicked the moment the i go "afk". Can you change this so it's a 10 minute cool down period before i get kicked?Kinda hard to do any research when I can't stay in the game long enough to drag more then a few vis down onto the scroll. Thanks!

**Comment by EndEnemy** [comment]
Yes. A little warning one min before it kicks you would be cool.

**Comment by dragonaslin** [comment]
its been set to 10 min
