### ISSUE TITLE
nano suit recipe error

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#307]
the crystal called for id # 4189 cannot be made

**Comment by frogger35** [comment]
When i NEI the crystal it shows me crystal id # 4189:26 which can be made. Dunno if this is an error for you alone but it seems to work just fine for me.

**Comment by Solidflip** [comment]
frogger is correct, make sure to create the correct crystal and it should work

**Comment by MrAtrophy** [comment]
they correct crystal cannot be cheated in , the recipe calls for a crystal than cannot be made

**Comment by dragonaslin** [comment]
I just made draconic armor that uses nano suit to make it so I think it's all you bro
