### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#312]
Looks like something where eliteman logs on is crashing the server.
Just happened at 16:35 CET.

**Comment by Abouttabs** [comment]
doesn't seem block related, might be corrupt player data or just a derp, its tied to enderstorage so chickenbones......

**Comment by Solidflip** [comment]
Logs plz

**Comment by Solidflip** [comment]
Will reopen when/if this happens again and we get logs
