### ISSUE TITLE
I fucking hate witchery bosses

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#314]
i had death and he spawned naturally when he spawned he just started jumping around then he tp's somewhere and disappeared me and fine points looked all over my base and couldn't find him

**Comment by Direcub10** [comment]
and before someone says it he didnt despawn

**Comment by Direcub10** [comment]
0000000000000000000000000000000000000000000000000000000000

**Comment by Solidflip** [comment]
make a room where you can contain him dude
