### ISSUE TITLE
Bee-related Botania flowers broken after update

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#315]
The new botania did away with mana petals, but FTB apparently didn't fix ther minetweaked recipes for the bee-related Botania flowers (Hibeescus, Hiveacynth and Beegonia). Previously they used mana petals in their recipe, but those have been removed from Botania and replaced with Mana Powder, so now it's showing Fire in their place. Presumably FTB will fix this at some point, but in the meantime, perhaps the recipes could be changed on our side to use the Mana Powder?

**Comment by Solidflip** [comment]
This isnt a minetweaker issue, Botania 1.8 conflicts with magic bees as MB isnt very updated. I can fix this still, but its a botania/magic bees issue

**Comment by Solidflip** [comment]
hibeescus finished, the other flowers are fine

**Comment by Solidflip** [comment]
flower recipes for the last 2 dont work as they have the incorrect wording. im fixing now

**Comment by Solidflip** [comment]
recipes added. However they do not show correctly in the Lexica Botania. I could fix this, however i would need the entry tags for the three flowers, the command minetweaker has to do this does not work, i tried guessing but that failed as well.

**Comment by EndEnemy** [comment]
This fix should work for all three flowers:
[rTr_fix_botania.txt](https://github.com/RTRGitHub/RTRRedux/files/95215/rTr_fix_botania.txt)

the fire is replaced by mana powder, everything else is default

**Comment by icha-senpai** [comment]
yea i asked end to fix the recipes the way they should be cause u can't put a comb in an apothecary...End tried and i verified

**Comment by icha-senpai** [comment]
the recipes work....as for the lexica botania thing well thats why we have nei

**Comment by icha-senpai** [comment]
http://puu.sh/mAZrM/ef109d017f.zs  there is the file as a script just put it where the other ones go and it should work

**Comment by Solidflip** [comment]
comb removed, recipes should work as intended.
