### ISSUE TITLE
Death killing my soul

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#318]
ive killed death atleast 12 times and gotten 5 set of robe 2 hand 1 hood and 1 horse skull, the rest of the times ive gotten nothing bc he didnt drop shit. is there any way i can trade in one of the parts i have for his shoes (the one item he refuses to drop) because im tired of summoning. Ive summoned him atleast 5 time legit as u can ask end, fine, and lucid. Imo ive earned his shoes

**Comment by Direcub10** [comment]
This is not a complaint about anything despawning or the such

**Comment by Direcub10** [comment]
nvm got it from killing him agian

**Comment by Solidflip** [comment]
Dire, mob drops are not a bug. If a mob doesnt drop a certain item, you kill them again especially if they have a drop table bud.
