### ISSUE TITLE
laptop busted

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#319]
Well one of the wires on my laptop nlbroke so now it doesn't work. I won't be able to place it for like 6 months so until then bye. PS:I didn't put this up on the forum BC I couldn't get it to log me in. }:(

**Comment by Abouttabs** [comment]
That sucks man,

What wire broke on you? Maybe it could be fixed without full replacement?

**Comment by Solidflip** [comment]
Try to pop into ts on your phone to see if we can help buddy

**Comment by Direcub10** [comment]
Idk how to get ts on my phone and idk what wire it its internal won't boot and doesn't even have a light on thrle side when I try to charge it

**Comment by Abouttabs** [comment]
Well try opening it gently and check the connections of wires (I assume
it's out warranty), or you could get it checked by technician maybe?
Shouldn't be too expensive just to get it checked... It seems like a loose
wire maybe....

**Comment by Direcub10** [comment]
Can't get the ta app without paying 1.99 u insane? :V

**Comment by Solidflip** [comment]
it costs $$ now? hmm. could try sending us a pic maybe?

**Comment by xXlucidXx** [comment]
Hey dire, what were you doing with it the day it broke?

**Comment by Direcub10** [comment]
Was on the server actually bringing it to a technician during the week to hopefully get it fixed why do u ask

**Comment by icha-senpai** [comment]
did u make sure it was plugged into the wall? :P

**Comment by Direcub10** [comment]
I did why don't u come test the socket with ur dick :p

**Comment by Direcub10** [comment]
BTW u guys can close this if u want I put it BC I couldn't get into the forum

**Comment by icha-senpai** [comment]
i love you dire...i hope you get ur  laptop fixed soon and can rejoin us

**Comment by xXlucidXx** [comment]
Dire, behave okay? and were you lifting it or moving it all, any weird sounds or vibrations

**Comment by Direcub10** [comment]
Nope.

**Comment by kenny608uk** [comment]
Deleted inappropriate comment and closed.
