### ISSUE TITLE
Mekanism metals disappeared

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#32]
With the update yesterday, all mekanism metals for the most part had disappeared. I did notice my ME system has tons more room, but never suspected the issue.

I know for me, i lost a lot of ingots. 8K+ of each copper & tin, 10k+ Osmium ingots (Strange that the 9 osmium blocks i had remained O.o), and at least 1k steel.

Very strange indeed, I suspect id changes in the mekanism update >.<

**Comment by Abouttabs** [comment]
You suspect correctly.
He merged the IDs in odd ways...
