### ISSUE TITLE
dimensional transceiver and tesseracts

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#321]
disable public channels please otherwise im going to start temp banning people stealing power and items from others without permission, then ill ask you to fully ban them

**Comment by Camtoe112** [comment]
Who's taking what?

**Comment by Camtoe112** [comment]
Also, they're configurable to be private.

**Comment by Solidflip** [comment]
Icha, These items have the ability to have private channels use those to prevent others from using your power. Tesseracts and dimensional tranceivers can hold many private lines.
