### ISSUE TITLE
cant bypass claims when in creative

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#323]
could you please fix thanks much love

**Comment by Solidflip** [comment]
issue submitted to FTB utilities to find out permission nodes to allow non opped players in the mod group to bypass claims. Will await answer

**Comment by icha-senpai** [comment]
ok cool thxs

**Comment by Solidflip** [comment]
Note to self see https://github.com/RTRGitHub/RTRRedux/issues/328

**Comment by Solidflip** [comment]
requires ftbu to update, will reopen when that happens
