### ISSUE TITLE
Commands that mods and I might need

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#325]
/tp <player> <player>

/tpl <player> that teleports me to there last known postion when they arent on

the clock player logger thing

/febutcher [radius] [type] [x, y, z] 

hostile only cause there might be an abundant amount and we may be told to use it 

GetCommandBook
/getcommandbook or /cmb or /gcmb
fe.commands.getcommandbook
Gives you a book with all the commands you are allowed to use. 

that way we can always know what we can do 

Time
/time [dimID, none for all] <(freeze/lock/set/add)> <(<number>/day/night)>
fe.commands.time
Manipulate time by either freezing it or locking it to the current part of the cycle or set it or add to it. 

in case dire cant get his night machine or if theres to many people on but not enough beds or access to beds but majority wants day

Weather
/weather [DimID, none for all] <(rain/storm)> [(on/off)]
fe.commands.weather
Manipulates the weather by allowing you to turn on or permanently turn off rain or storm.

Cause who likes rain

also all the opis commands

and ftb utilitiy commands

**Comment by Solidflip** [comment]
will add these once i get the permission nodes for the bypass claims.

**Comment by Direcub10** [comment]
Aww so considerate icha :D

**Comment by Solidflip** [comment]
commands given, i will give opis once i have the bypass claims later
