### ISSUE TITLE
Mods and admins need the ability to set more then one home

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#328]
if that's possible

**Comment by Solidflip** [comment]
change ftbu json config to allow more than 1 home. will do later tonight

**Comment by Solidflip** [comment]
will have to wait on the permission nodes for this one as well

**Comment by Camtoe112** [comment]
Use the way points from journey map?

**Comment by icha-senpai** [comment]
until you update and lose your way points and map...i carried over all my journey map stuff from the before the update and lost my map so thats not always a 100 percent fix...but its still a good idea for while i have my current map

maybe for mods and admins we can have our main base be /warp Icha, /warp Soildflip, and so on and then we can have a more personal private area as home...like how soup started over and flip has his creative build and dragon has his new area...those could be the set home areas...

**Comment by Solidflip** [comment]
i will allow mods to have personal warps, will add to the perms
