### ISSUE TITLE
Mining world Reset

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#329]
i was wondering if we could do a reset soon and I've had some feature requests

 if possible like villages as nice as the rftools huts are...there useless with the dimlets they give us  and maybe different biomes...I've heard althos talk about a magical forest...

but if you wanna go back to to the normal flat land thats cool too

**Comment by Solidflip** [comment]
Will post about mining world reset on forums. Will give 3-5 days depending on my mood

**Comment by Solidflip** [comment]
http://righttorebel.net/forums/showthread.php?14269-Dimension-Resets-1-28-16

Thursday 28th
