### ISSUE TITLE
New world area needs to be pregen'd DON"T FORGET FLIP

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#330]
you said two hours from now thats 2 am pst...i want a message here when i wake up saying its done Mister-i-forget-everything-please-put-it-on-the-github-guy

**Comment by icha-senpai** [comment]
cause the tps gets down to 4 when people decide to explore

**Comment by Solidflip** [comment]
yup, on it. 1 hour 45 mins

**Comment by Solidflip** [comment]
began pregen on time, took waaay too long, decided to segment it. Will complete left/bottom then right/top tonight

**Comment by Solidflip** [comment]
Left
-188 -375 to -375 375

bottom
-375 -188 to 375 -375

right
188 -375 to 375 375

top
-375 375 to 375 188

**Comment by icha-senpai** [comment]
awesome...you know if u need to be somewhere and need someone to baby sit it i can watch if u share screens on skype while u sleep or something

**Comment by Solidflip** [comment]
and have you sift through my porn? i dont think so

**Comment by icha-senpai** [comment]
not computer share... screen share all i can do is watch i cant look thru stuff...u did it that one day where we watched u fix recipes

**Comment by Solidflip** [comment]
i know, its called a joke

**Comment by Direcub10** [comment]
Too bad it was so shit no one got it

**Comment by icha-senpai** [comment]
Don't forget to finish the pregen...i think this has alot to do with our random issues cause people are exploring...
