### ISSUE TITLE
Can we do more events?

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#331]
Can we do more events and promote it with the events thread?http://righttorebel.net/forums/showthread.php?8588-Community-Events

it doesn't have to be weekly events maybe bi weekly
if we do weekly have Monday or Friday( or whatever day is our most active average day trivia and then like a build contest or pvp contest the next week

but like a set schedule with trivia for sure two weeks out of the month...like i could look into building something like Jeopardy!  or Family Feud... if soup cant do it...that way having a designated trivia area we can get people who wanna participate an area to compete in...there is those cool auditoriums in spawn that look like an opera stage we could use as a stage for trivia

**Comment by Solidflip** [comment]
http://righttorebel.net/forums/showthread.php?8588-Community-Events&p=54349#post54349
