### ISSUE TITLE
So can you explain this to me with the reactor chambers?

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#334]
just before the restart at 4pm est http://puu.sh/mKJWI/72caa9a72e.png

after the server restart at 4:07 pm est http://puu.sh/mKKgH/a20625f95f.png 

almost an hour later at 5 pm est http://puu.sh/mKO9h/ad4a025093.png

**Comment by Direcub10** [comment]
Some doesn't know what their doing wit their bombs?

**Comment by Solidflip** [comment]
opis only profiles the loaded chunks as far as i understand, Therefore unloaded areas wont add to their count. Also this isnt a github issue, put questions like this about the modding features on the staff chat on whatsapp
