### ISSUE TITLE
my animals keep disappearing

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#335]
I have a farm in the last millenium with 32 chickens and 9 cows for my mana production (cake flower).
Every animal has his own 1x1 cage and I've changed the area to be chunkloaded by personal anchors. 
The animals in the farm disappeared/got killed four times in the last two weeks. 
I'm really tired of spawning them again and again...

**Comment by Abouttabs** [comment]
Entities are known to fall through the world at load of chunk, void worlds
are more prone to it for some reason....

**Comment by torsteig** [comment]
Temp fix: flight module from rf tools on an environment controller?

**Comment by Camtoe112** [comment]
If entities are causing substantial server lag, they'll be removed.

**Comment by Solidflip** [comment]
This is due to the chunk loading issue tabs referenced. I would build a platform under them i guess. Not much i can do about them loading before the world as thats basic mc
