### ISSUE TITLE
Ink mixer

### ISSUE THREAD

**Issue by Volaunis** [RTRGitHub/RTRRedux#336]
Is it intentional that the ink mixer from mystcraft is enabled?
First off, it does _not_ allow you to make ages, you need the book binder for that, and that's disabled.
It does however allow the creation of linking books, which work like they've always done, in that they can only link from another dimension than the one they're linked to, and they get left behind (either in the bookstand or on the ground.
Also the recipe for the ink mixer has ben expert'ed, uses 4 different mod's type of teleportation in its recipe.

**Comment by Solidflip** [comment]
this is intentional
