### ISSUE TITLE
Can we make a full push to discord from whatsapp for staff stuff?

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#338]
you can get discord on your phones or tablets...most of us are on discord already but not all of us use it...i'd like for us to use that instead...you can make private staff channels for admins and then have one for old admins and other people who might need to be in the loop and what not...

**Comment by Solidflip** [comment]
personally i like whatsapp better, but ill check to see if discord has a app for the phone. If it does i can totally switch. Ill make sure in the future to use both
