### ISSUE TITLE
no ore in mining world

### ISSUE THREAD

**Issue by scoobydoo192** [RTRGitHub/RTRRedux#341]
http://i.imgur.com/4NHtSu9.png

**Comment by icha-senpai** [comment]
its at the world border that soup set up and it might be the pregened area he did http://puu.sh/mRh41/9a7f4ade21.jpg

**Comment by icha-senpai** [comment]
yea and the world border for the mining world is stupid small

**Comment by icha-senpai** [comment]
yup can confirm its the pregen'd area cause on my map there's the area from last night that i generated and i flew around the new border and theres no ore in the new pregen'd area

**Comment by icha-senpai** [comment]
http://puu.sh/mRhXo/f4207d5fa4.jpg and http://puu.sh/mRhZ2/564622398c.jpg

those are the border and the areas with no ore are pregen'd

**Comment by Solidflip** [comment]
will reset and regen
