### ISSUE TITLE
Last Millenium portal bugs

### ISSUE THREAD

**Issue by SirFell** [RTRGitHub/RTRRedux#342]
Bug №1: Entering Last Millenium

When entering Last Millenium I end up teleported to my very own platform in Last Millenium dim. Before moving to Cauldron server i was getting teleported to spawn platform.

Bug №2: Exiting Last Millenium

When exiting Last Millenium I end up teleported exactly 7km away from place where Last Millenium portal is. Before moving to Cauldron server i was getting teleported to spawn portal.

-SirFell

**Comment by Solidflip** [comment]
i think i may know how to fix this, but ill need you on to do so

**Comment by EndEnemy** [comment]
Same here.
Its also happening if u port back from the mining world.

**Comment by Solidflip** [comment]
End, hit me up when you are online

**Comment by Solidflip** [comment]
no response from creator for almost 2 weeks, ends using a different portal. Will close issue until such time as someone has it again
