### ISSUE TITLE
Perms

### ISSUE THREAD

**Issue by icha-senpai** [RTRGitHub/RTRRedux#343]
lagg perms

prism perms

Instructions:   Allows you to change that the player sees in his client. This doesn't affect monster spawning.
If you use an @ prefix to the time, the players time will be locked, and won't change gradually.
Permissions:  
essentials.ptime    Allow access to the /ptime command.
essentials.ptime.others Allows you to change the time of another online player.

Instructions:   Allows you to see and change the time on the server, either for a specific world or for all worlds.
If you use any of the specific aliases like 'day', the command will default to that time, ie '/day' will set the time to day.
Permissions:  
essentials.time Allow access to the /time command.
essentials.time.set User is allowed to change the time of the world.

Instructions:   Typing the command will echo your current position to the chat window.
Permissions:  
essentials.getpos   Allow access to the /getpos command.
essentials.getpos.others    Allow user to get the position of another player.

Instructions:   This command allows you to toggle the visability of other players direct messages and mail.
Permissions:  
essentials.socialspy    Allow access to the /socialspy command.
essentials.socialspy.others Allows you to toggle the social spy status of others.
essentials.chat.spy 
Instructions:   Using this command will remove all of the entities specified in the world or in a given radius.
Permissions:  
essentials.remove   Allow access to the /remove command.

instructions:   This command allows you to ban a player for a specified amount of time.
<time> Should given in "years(y) months(mo) weeks(w) days(d) hours(h) minutes(m) seconds(s}".
You may omit blank parameters. For example: "2d 5h 30m".
Permissions:  
essentials.tempban  Allow access to the /tempban command.
essentials.tempban.exempt   Prevents a specified group or player from being tempbanned
essentials.tempban.offline  Allows temp-banning of players who are offline. This may allow you to ban exempt players.
essentials.tempban.unlimited    Allows bypassing config file max ban time limit.
essentials.ban.notify   Players with this permission will receive a notification when a ban is set.

Instructions:   When you type this command, become invisible ingame, and also hidden from most ingame commands.
To teleport to a vanished player you will need to use tpo or tpohere to force a teleport.
Permissions:  
essentials.vanish   Allow access to the /vanish command.
essentials.vanish.see   Allows you to see a vanished player.
essentials.vanish.interact  Allows the player to use commands which interact with a vanished player.
essentials.vanish.effect    People with this effect will get the potion effect applied while vanished.
essentials.vanish.others    Allows you to toggle vanish on others
essentials.vanish.pvp   Allows players who are vanished to attack other players.

Instructions:   This command allows the manipulation of the weather on your current world.
If you use any of the specific aliases like 'sun', the command will default to that weather, ie '/sun' will switch the weather to sunny.
Permissions:  
essentials.weather  Allow access to the /weather command.

Instructions:   Provide a set of <x> <y> <z> coordinates to teleport directly to that location.
The Y coordinate is your vertical (up/down) location."</z></y></x>
If used in console, place the player name before the coordinates.
Permissions:  
essentials.tppos    Allow access to the /tppos command.

Instructions:   Typing the command will teleport you a location in another world assuming the world/map is loaded on the server.
Permissions:  
essentials.world    Allow access to the /world command.
essentials.worlds.<worldname>   Allows players access to a specific world.

Instructions:   When you type this command, become invisible ingame, and also hidden from most ingame commands.
To teleport to a vanished player you will need to use tpo or tpohere to force a teleport.
Permissions:  
essentials.vanish   Allow access to the /vanish command.
essentials.vanish.see   Allows you to see a vanished player.
essentials.vanish.interact  Allows the player to use commands which interact with a vanished player.
essentials.vanish.effect    People with this effect will get the potion effect applied while vanished.
essentials.vanish.others    Allows you to toggle vanish on others
essentials.vanish.pvp   Allows players who are vanished to attack other players.

Instructions:   This command makes another player perform a command (or speak) as if they typed it in the chat box themselves.
Permissions:  
essentials.sudo Allow access to the /sudo command.
essentials.sudo.exempt  Prevents the holder from being sudo'ed by another user.

Instructions:   This command will kick the specified player off the server.
Permissions:  
essentials.kick Allow access to the /kick command.
essentials.kick.exempt  Prevents the player from being kicked.
essentials.kick.notify  User sees a notification when a user is kicked.

Instructions:   Places LIVE TNT near or on the block your crosshair is on.
Permissions:  
essentials.antioch  Allow access to the /antioch command.

Instructions:   This command will kick all other players off the server.
Permissions:  
essentials.kickall  Allow access to the /kickall command.

Instructions:   This command allows you to drop a 'nuke' on players on the server.
If you don't pass a players name, everyone on the server will be effected.
Permissions:  
essentials.nuke Allow access to the /nuke command.

**Comment by icha-senpai** [comment]
Instructions:   The command will add an enchantment to the item the user is currently holding.
Using the command without an enchantment name will return a list of available enchantments.
Permissions:  
essentials.enchant  Allows access to the /enchant command.
essentials.enchantments.[enchantmentname]   Allows access to each enchantment type.
essentials.enchantments.allowunsafe If enabled in the config, this permission allows unsafe enchantments.

Instructions:   Without further permissions this command allows players to view their own exp information. 
The additional permissions extend this to allow the changing of their own or others exp, or simply viewing another players exp.
If you wish to give/set a set level of exp rather than raw exp, prefix the amount with 'L'.
Permissions:  
essentials.exp  Allow access to the /exp command.
essentials.exp.set  Allows players to set their own exp.
essentials.exp.set.others   Allows players to change others exp (if they also have essentials.exp.set).
essentials.exp.give Allows players to give themselves exp.
essentials.exp.give.others  Allows players to give others exp (if they also have essentials.exp.give).
essentials.exp.others   Allows players to see another players exp.

Instructions:   This command allows you modify the effects/charges on a stack of fireworks. While holding the stack you'd like to modify, use the command to either clear or add an effect.

Full Meta Syntax:
color:<color[,color,..]>
fade:<color[,color,..]>] 
shape:<star|ball|large|creeper|burst>
effect:<trail|twinkle>[,<trail|twinkle>]

Examples:
/firework color:red
/firework color:red shape:star effect:trail
/firework color:red,blue,green fade:yellow
Permissions:  
essentials.firework Allow access to the /firework command.
essentials.firework.fire    Allows a user to 'spawn' a copy of the firework held in their hands.

Instructions:   When you type this command, your client will be informed it is allowed to use creative mode fly.
To start flying simply use the same controls (double tab jump).
Permissions:  
essentials.fly  Allow access to the /fly command.
essentials.fly.others   Allows you to toggle fly for other players.
essentials.fly.safelogin    Players with this command will automatically switch to fly mode if they login whilst floating in the air.

Instructions:   This command allows a player to gift another player with the defined amount of the specified item.
The amount will default to the value in the config.yml.

Item Meta:
<enchant>:<level>
name:<Item Name>
lore:<Item description>

player:<Player name> - Used on skulls

book:<book.txt chapter> - Used on written books to allow custom content
author:<book author> - Used on written books
title:<book title> - Used on written books

color:<red>,<green>,<blue> - Used on leather armor

power:<firework power> - Used on fireworks
color:<color[,color,..]>
fade:<color[,color,..]>]
shape:<star|ball|large|creeper|burst>
effect:<trail|twinkle>[,<trail|twinkle>]

Examples:
/give KHobbits 397:3 1 player:Notch
/give KHobbits dspade 1 digspeed:3 name:Dwarf lore:Diggy|Diggy|Hole
Permissions:  
essentials.give Allow access to the /give command.
essentials.itemspawn.exempt Allows spawning of items on the spawn blacklist.
essentials.itemspawn.item-all   If permission-based-item-spawn: Spawn all items
essentials.itemspawn.item-<itemname>    If permission-based-item-spawn: Spawn <itemname>
essentials.itemspawn.item-[itemid]  If permission-based-item-spawn: Spawn [itemid]
essentials.oversizedstacks  Allows spawning of stacks above normal max stack size
essentials.enchantments.allowunsafe If enabled in the config, this permission allows unsafe enchantments.
essentials.enchantments.[enchantmentname]   Allows access to each enchantment type.
essentials.itemspawn.meta-title Allow 'title' meta to be used in item spawning.
essentials.itemspawn.meta-author    Allow 'author' meta to be used in item spawning.
essentials.itemspawn.meta-lore  Allow 'lore' meta to be used in item spawning.
essentials.itemspawn.meta-book  Allows spawning of books with pre-filled content from books.txt
essentials.itemspawn.meta-head  Allows spawning of mob heads.
essentials.itemspawn.meta-chapter-[chapter] Allows spawning of specific books only, from book.txt.
essentials.itemspawn.meta-firework  Allow specific meta for fireworks.

Instructions:   This command toggles 'god' status.
In god mode you are invulnerable to all damage types.
Permissions:  
essentials.god  Allow access to the /god command.
essentials.god.others   Allows you to god other players
essentials.god.pvp  Allows you to attack other players while in god mode.

Instructions:   Allows you to heal yourself or a specified player to full health.
Permissions:  
essentials.heal Allow access to the /heal command.
essentials.heal.cooldown.bypass Bypass the heal cooldown
essentials.heal.others  Allows healing another player

Instructions:   This command allows a player to spawn the defined amount of the specified item.
The amount will default to the value in the config.yml.

Item Meta:
<enchant>:<level>
name:<Item Name>
lore:<Item description>

player:<Player name> - Used on skulls

book:<book.txt chapter> - Used on written books to allow custom content
author:<book author> - Used on written books
title:<book title> - Used on written books

color:<red>,<green>,<blue> - Used on leather armor

power:<firework power> - Used on fireworks
color:<color[,color,..]>
fade:<color[,color,..]>]
shape:<star|ball|large|creeper|burst>
effect:<trail|twinkle>[,<trail|twinkle>]

Examples:
/i dirt
/i 397:3 1 player:Notch
/i dspade 1 digspeed:3 name:Dwarf lore:Diggy|Diggy|Hole
Permissions:  
essentials.item Allow access to the /item command.
essentials.itemspawn.exempt Allows spawning of items on the spawn blacklist.
essentials.itemspawn.item-all   If permission-based-item-spawn: Spawn all items.
essentials.itemspawn.item-[itemname]    If permission-based-item-spawn: Spawn [itemname]
essentials.itemspawn.item-[itemid]  If permission-based-item-spawn: Spawn [itemid]
essentials.oversizedstacks  Allows spawning of stacks above normal max stack size
essentials.enchantments.allowunsafe If enabled in the config, this permission allows unsafe enchantments.
essentials.enchantments.[enchantmentname]   Allows access to each enchantment type.
essentials.itemspawn.meta-title Allow 'title' meta to be used in item spawning.
essentials.itemspawn.meta-author    Allow 'author' meta to be used in item spawning.
essentials.itemspawn.meta-lore  Allow 'lore' meta to be used in item spawning.
essentials.itemspawn.meta-book  Allows spawning of books with pre-filled content from books.txt
essentials.itemspawn.meta-head  Allows spawning of mob heads.
essentials.itemspawn.meta-chapter-[chapter] Allows spawning of specific books only, from book.txt
essentials.itemspawn.meta-firework  Allow specific meta for fireworks.

**Comment by icha-senpai** [comment]
Instructions:   This command allows you to create a 'home' at your current location.
You can create additional homes by adding a 'name' after the command.
Additionally, you can create a new 'home' for another player by prefixing the home name with <username>: (if you have the necessary permission).
Permissions:  
essentials.sethome  Allow access to the /sethome command.
essentials.sethome.others   Allows you to change another users home location.
essentials.sethome.multiple Allows player to have multiple homes, or create named homes. Required for 2+ homes.
essentials.sethome.multiple.unlimited   Removes the cap on the number of homes people are allowed (if they have multiple homes).
essentials.sethome.multiple.[set name]  Raise the multiple home limit to a setting defined in the config file.
essentials.sethome.bed  Allows the player to right click a bed during daytime to update their 'bed' home.

**Comment by Solidflip** [comment]
dude,,,,lol

**Comment by icha-senpai** [comment]
well u can decide which ones u want to give me i just gave u a list of the ones i thought useful and fun

**Comment by Camtoe112** [comment]
Jesus

**Comment by Solidflip** [comment]
permissions granted, check discord for breakdown
