### ISSUE TITLE
Using the /warp feature is stripping my armor

### ISSUE THREAD

**Issue by AlthosSilver** [RTRGitHub/RTRRedux#344]
No matter where i go. If I go to the nether, end or mining world, its removing my armor, which makes it dangerous because that removes my ability to fly

**Comment by icha-senpai** [comment]
and if you have a full inventory makes you lose your armour

**Comment by Solidflip** [comment]
i just /warped to all the warps wearing flux infused and it was still on....What armor are you using?

**Comment by AlthosSilver** [comment]
I have a draconic chestplate and wyvern helm, leg and boot

**Comment by Solidflip** [comment]
ill test again tonight

**Comment by icha-senpai** [comment]
every time i warp i lose my armour as well and half my hunger

**Comment by Solidflip** [comment]
I still dont get this, even when non opped... Ill need to do it with one of you guys to see it happen

**Comment by Solidflip** [comment]
issue seems sporatic, please send me your console logs when this happens.

**Comment by Solidflip** [comment]
Seems to be related to certain types of armour, If this is still an issue could you post the type of armour you have?

Type of armour:
Is it enchanted?:
Anything special about the armour?:

**Comment by Camtoe112** [comment]
Also, try warping there now.

**Comment by EndEnemy** [comment]
Ok pretty sure its the "Soulbound" Enchantment.
I have a Dark Armor from Ender IO with a Dark Soularium Jetplane.
Its also happening to my Terrasteel Armor form Botania.
All enchanted with Soulbound.
Tried it with Leather Leggins, enchanted with Soulbound and some other leggins enchanted with something else.
Only the soulbound one jump into the inventory with /back.
I also realised that all Soulbound Items get "sorted" in the inventory when /back.

**Comment by Solidflip** [comment]
have you tried it without soulbound on the same items?

**Comment by EndEnemy** [comment]
Only on leather leggins. The soulbound one jumpes into the inventory if u /back in another dim.
The other leather leggins was enchanted with protection and didnt jump into the inventory.

**Comment by Solidflip** [comment]
issue reported to EnderIO, for now disenchant these items. Your grave should hold them for you when you die.

Will reopen when i get a response from EnderIO
