### ISSUE TITLE
Animals/Items Despawning 

### ISSUE THREAD

**Issue by Madraver** [RTRGitHub/RTRRedux#345]
When I leave the server at night, and log in the next day (3-4pm) I find that any animals I had for farming (with mfr rancher) and any items I had on the ground (certus quartz seeds which should not despawn?) vanish completely. Not sure what is causing this, but if possible would love something to be done about it :)

**Comment by Solidflip** [comment]
issue has been addressed and should not occur

**Comment by Madraver** [comment]
Issue is still occuring.
