### ISSUE TITLE
Intricate Circuit Boards 

### ISSUE THREAD

**Issue by AlthosSilver** [RTRGitHub/RTRRedux#346]
separating and not registering in AE system as valid components for crafting

**Comment by Solidflip** [comment]
they're seperating? Do you mean they wont stack? Have you tried the crafting recipe outside of AE?

**Comment by AlthosSilver** [comment]
They are crafted via a carpenter. Somehow 200+, using the same idea, come up as a different stack in the AE system and the system wont recognize them for crafting purposes, in this case, Ultimate Hybrid Solar Panels

**Comment by Solidflip** [comment]
so what i understand is that when you hit the ? to put in the recipe it puts in everything else besides the circuit boards?

**Comment by Direcub10** [comment]
I think he means the as system won't autocraft with them BC each one is apparently unique for some on godly reason. He's prob trying to autocraft the solar panel

**Comment by Abouttabs** [comment]
Buildcraft uses nbt for many of it's items, AE does not know how to work with that, it doesn't even use ore dict on autocratic AFAIK... There's nothing to be done, if they clog your AE you could try to use filling cabinets for em....

**Comment by Solidflip** [comment]
yeah if its for autocrafting then you will need to put the exact version without edits in the pattern, if you mean when you hit the ? in the crafting terminal, that you will have to do by hand

**Comment by Direcub10** [comment]
A workaround would be eclxporting the items in and use a level emitter stop it b4 u have 4k

**Comment by Solidflip** [comment]
issue dormant, no response from creator. Will be reopened at creators will. issue could be resolved with the use of ender io pipes exporting 1 of the item from a chest into the autocrafting system if its autocrafting issue. If its the ? issue, nothing can be done there
