### ISSUE TITLE
Personal Anchor/ME Bug

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#348]
The ME System isnt working when the player is in the last millenium.

You can't access the ME-System that is loaded by a personal anchor.
It restarts when u come back to the base.
It turns off when u go back the dimension.
The import chest runs full. (EnderChest with an Import Bus).
Items on the ground does despawn normally.

**Comment by Direcub10** [comment]
Did u put ender pearls in it and put it NEXT to the system? They don't load a big area also if the over world part is loaded why is it working when u unload thevlastcmil side

**Comment by Solidflip** [comment]
Personal anchors will only load a chunk if the chunk has already been loaded. Therefore you need to visit it once, then it will keep it loaded until the next restart. Unfortunately this is working as the mod intended. You will need to find a way to load that one chunk.
