### ISSUE TITLE
Ender IO Weather Obelisk Bug

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#349]
Ther Weather Obelisk is derpy.
Its kind of confused about the actual weather.

When its raining u cant turn it to sunny because he thinks it is actually sunny.
When its sunny u can turn weather to sunny, but not to raining. Its making the particles uses the cake and the energy.

Sorry for still finding new bugs o_o

In love, ur Beta-Tester End

**Comment by Solidflip** [comment]
very weird, issue reported to Ender IO, will reopen when they respond, Til then item replaced with the draconic weather controller
