### ISSUE TITLE
Cache emptied contents upon being moved

### ISSUE THREAD

**Issue by Madraver** [RTRGitHub/RTRRedux#350]
I had a hardened cache containing ~18500 'Supreme Pizza'. I broke the cache with a pickaxe and saw in my inventory (holding shift for more info) that the cache contained the same ~18500 'Supreme Pizzas'. I then changed dimensions to the mining world_ (via the rftools teleporter at spawn)_ and went to set up a quarry. _(where i was intending to use the pizza for power in a culinary generator. this amount of pizza will generate roughly 2.1 Billion RF) _ and when I placed down the cache it revealed to contain nothing. Tried to recreate the issue with kenny but to no success. This is a huge problem for me as that amount of pizza took a huge infrastructure and a very long time to create  I would like to get the pizzas refunded somehow since this is a very frustrating glitch that has made me lose a lot of work :/ I assume (and hope) there is a world file or something from a recent save that you can look at to prove that I did infact have a cache containing 18000+ supreme pizza, and that I'm not just using this as a way to get free pizza. 
Thanks. - Mad

**Comment by icha-senpai** [comment]
madraver i recreated this bug and can infact confirm that this is a bug with the normal pizzas the other two types of pizzas dont do this i can refund you your current pizzas but the issue will happen again so instead i will refund you the same amount with supreme pizzas

**Comment by icha-senpai** [comment]
actually it just happened with the other two types of pizza as well so i will test something out and find a more suitable way to give you the amount of pizzas and make sure u don't lose them when going cross demension

**Comment by icha-senpai** [comment]
correction i am unable to refund the items but flip will handle the refunding of the items

**Comment by Solidflip** [comment]
So i attempted to reproduce this issue, i tried multiple times with the different pizzas, nothing. This may have been caused when you used a tinkers pickaxe to pick up a machine. 

As in IC2 some machines should be picked up with only a wrench or a normal pickaxe (ie; the ones from TE) I will refund this this one time, however should this happen in the future it wont be refunded as you could have used a wrench as the mod wants you to and avoided this altogether.
