### ISSUE TITLE
Someone stole some of my things.

### ISSUE THREAD

**Issue by Orbitus2001** [RTRGitHub/RTRRedux#351]
I was processing some of my stuff that I have been holding on to for a while.  I went down in my base to move a couple ender chests and saw that some of my machines were configured wrong.  2 Pulverizers and 1 Redstone furnace was missing the augments out of them and they were basics.  When I made all 3 of them, I used resonant machine frames to make all 16 machines I made for auto processing.  So not only did they take my augments, they took the machines and replaced them with the cheap versions.  They also took 3 blocks of enderium.  I had 178 when I moved, and had 175 when I was checking everything after finding out that my machines weren't my machines. 

After that happened I wanted to remove all of my friends from my friends list to prevent it from happening again but apparently they have to be online to be removed from my friends list.  I don't know if that can be changed or not but I would like to know if that can be if possible.

**Comment by Abouttabs** [comment]
seems more like a derp in saving or something as its in a separate chunk of the rest of the machines + Prism didnt say anything... Refunded items

**Comment by Orbitus2001** [comment]
Thank you.
