### ISSUE TITLE
[Suggestion] Add a recipe for the egg-bee

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#352]
I did the whole Infinty Bee breeding to find out:
The Leporine Queen is only craftable during eastern.

Its not working with the advanced mutatron from GenDustry either.

Since chicken have a really short lifetime, is it possible to add a recipe for it?

Maybe:
[Egg]                 [Chicken Soul]      [Egg]
[Chicken Soul]  [PowerModule]      [Chicken Soul]   =  [Laporine Queen]
[Egg]                 [Chicken Soul]      [Egg]

*Chicken Soul from Draconic Evolution
*Power Module from GenDustry

If you give me the ok, I can write the needed script.

End.

**Comment by Volaunis** [comment]
Alternately, changing the config for Gendustry to allow it to be bred using the advanced mutatron : https://github.com/bdew/gendustry/issues/105

**Comment by EndEnemy** [comment]
This would be even smoother. I like :+1:

**Comment by Solidflip** [comment]
craftable while eastern?

**Comment by Solidflip** [comment]
you mean during easter?

**Comment by Orbitus2001** [comment]
Yeah he means during Easter.  I tried crafting it as well.

**Comment by EndEnemy** [comment]
jajaja _writing skills_ 
i'm sorry

**Comment by Solidflip** [comment]
Bees added to the mutatatron

Thanks for the offer btw end =)

http://puu.sh/nbwIM/786245a5e7.jpg
