### ISSUE TITLE
Much Pain, Very Ass, So FTB

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#362]
the color aplicater from AE2 changes the colors of your cables for orginazion purposes. While it needs an AE chest to put paint in it, which i have made the stuff for, the applicater itself needs an energy acceoter aswell bc the normal recipe has an AE2 energy cell in it, This tools offers no way t bypass the AE2 gate and therefre should not be so stupidly exspensive. can we pls do something like swap the AE cell for a thermal exspansion one or something

**Comment by Solidflip** [comment]
Submit your thoughts on the new recipe, if it fits the pack, i will change it

**Comment by Direcub10** [comment]
swap the h resonant one from TE

**Comment by Solidflip** [comment]
will take under advisement, look for an update tonight
