### ISSUE TITLE
The unimmortal vampire

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#363]
before i start pls understand this si a very worrying issue. Idk if it was an update or something to the pack(this isnt being caused by witchery, the mod hasnt updated in months so it couldnt have changed)
but i can die. i started to notcie this when the number of things that could one shit dramatically increased. i tried to fight 4 withers at once and they killed me. that shouldnt happen. it is almost an intended feature of vampirism to be able to fight the wither armorless. so i asked lucid to test this and he could now one shot me with the draconic staff, which he couldnt do b4. i even got him to reset and then set my vamp level to 10. idk how u would go about fixing this but i rlly would apprciate it if u fixed this

**Comment by Solidflip** [comment]
this still an issue?

**Comment by Direcub10** [comment]
yes
\

**Comment by Solidflip** [comment]
change to the mod causes this. DE is very very powerful. i suggest supplementing your vampirism with poppets or something
