### ISSUE TITLE
Enhanced Building Guide

### ISSUE THREAD

**Issue by scoobydoo192** [RTRGitHub/RTRRedux#364]
The Enhanced Building Guide isn't working right on our server I'm supposed to be able to click it and it will place block one by one in the guide as long as there's not something there already tested in single player it works there not sure why it doesn't on server :(

**Comment by Solidflip** [comment]
Is this in a claim?

**Comment by scoobydoo192** [comment]
yep i was trying it out at my place

**Comment by Solidflip** [comment]
will retest after update/reset
