### ISSUE TITLE
Unstable Tools Tinkers' Construct

### ISSUE THREAD

**Issue by TGuigz** [RTRGitHub/RTRRedux#365]
Unable to craft unstable tools via tinker smeltery and casting table. It use to work in older versions of extra utilities but not in the recent versions that ftb infinity evolved uses. [https://github.com/rwtema/extrautilities/issues/731](url) Talks all about it. I also posted the fix for it under that link. I just added the recipes in manually and tested it in single player.

**Comment by Direcub10** [comment]
havent been working for the last couple maps. give a mod the amount of ingots needed for the parts and they spawn it in for u.

**Comment by TGuigz** [comment]
Or they could simply fix the issue as a whole by making a txt file in the scripts folder for the server. With the following code. Then renaming it to something like unstableTinkers.zs the .zs is important. The code is

mods.tconstruct.Casting.addTableRecipe(TConstruct:toughRod:314, liquid:molten.unstableingots \* 432, TConstruct:metalPattern:14, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:toolRod:314, liquid:molten.unstableingots \* 72, TConstruct:metalPattern:1, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:pickaxeHead:314, liquid:molten.unstableingots \* 144, TConstruct:metalPattern:2, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:shovelHead:314, liquid:molten.unstableingots \* 144, TConstruct:metalPattern:3, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:hatchetHead:314, liquid:molten.unstableingots \* 144, TConstruct:metalPattern:4, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:swordBlade:314, liquid:molten.unstableingots \* 144, TConstruct:metalPattern:5, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:wideGuard:314, liquid:molten.unstableingots \* 72, TConstruct:metalPattern:6, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:handGuard:314, liquid:molten.unstableingots \* 72, TConstruct:metalPattern:7, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:crossbar:314, liquid:molten.unstableingots \* 72, TConstruct:metalPattern:8, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:binding:314, liquid:molten.unstableingots \* 72, TConstruct:metalPattern:9, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:frypanHead:314, liquid:molten.unstableingots \* 144, TConstruct:metalPattern:10, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:signHead:314, liquid:molten.unstableingots \* 144, TConstruct:metalPattern:11, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:knifeBlade:314, liquid:molten.unstableingots \* 72, TConstruct:metalPattern:12, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:chiselHead:314, liquid:molten.unstableingots \* 72, TConstruct:metalPattern:13, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:toughBinding:314, liquid:molten.unstableingots \* 432, TConstruct:metalPattern:15, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:heavyPlate:314, liquid:molten.unstableingots \* 1152, TConstruct:metalPattern:16, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:broadAxeHead:314, liquid:molten.unstableingots \* 1152, TConstruct:metalPattern:17, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:scytheBlade:314, liquid:molten.unstableingots \* 1152, TConstruct:metalPattern:18, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:excavatorHead:314, liquid:molten.unstableingots \* 1152, TConstruct:metalPattern:19, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:largeSwordBlade:314, liquid:molten.unstableingots \* 1152, TConstruct:metalPattern:20, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:hammerHead:314, liquid:molten.unstableingots \* 1152, TConstruct:metalPattern:21, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:fullGuard:314, liquid:molten.unstableingots \* 432, TConstruct:metalPattern:22, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:ShurikenPart:314, liquid:molten.unstableingots \* 72, TConstruct:Cast, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:CrossbowLimbPart:314, liquid:molten.unstableingots \* 576, TConstruct:Cast:1, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:CrossbowBodyPart:314, liquid:molten.unstableingots \* 720, TConstruct:Cast:2, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:BowLimbPart:314, liquid:molten.unstableingots \* 216, TConstruct:Cast:3, false, 50); mods.tconstruct.Casting.addTableRecipe(TConstruct:arrowhead:314, liquid:molten.unstableingots \* 144, TConstruct:metalPattern:25, false, 50);

**Comment by Solidflip** [comment]
yup, the only way to change this is via minetweaker, i saw that post as well. Changes will be instituted tonight
