### ISSUE TITLE
Hiveacynth not craftable

### ISSUE THREAD

**Issue by Luckdemon** [RTRGitHub/RTRRedux#370]
Botania's Hiveacynth is not craftable. http://puu.sh/nLWyr/1a8e2824b8.jpg
Shows properly on NEI, Botania's book, and in the apothecary as shown.

**Comment by Direcub10** [comment]
Don't let flip pick the recipe O)O

**Comment by dragonaslin** [comment]
fixed and tested

**Comment by Luckdemon** [comment]
Not fixed.
