### ISSUE TITLE
Forestry backpacks have stopped picking up ore/stone/cobble, etc.

### ISSUE THREAD

**Issue by Xalorous** [RTRGitHub/RTRRedux#375]
There are reddit posts describing this, and folks have had success moving (deleting) backpacks.cfg and letting the game regenerate that file.

I have tried this on client side and it works, the file is automatically regenerated when I start FTB:IE.

Can we please try this on server side?

**Comment by Solidflip** [comment]
http://puu.sh/nOo8x/19e255d3ef.png
fixed

**Comment by Xalorous** [comment]
Nice, thanks.  Works for me too.
