### ISSUE TITLE
Personal Anchors don't work

### ISSUE THREAD

**Issue by Luckdemon** [RTRGitHub/RTRRedux#378]
Ender chest in overworld with pipe connecting to 2nd chest to empty contents, as soon as I leave the overworld and attempt to use the ender chest it does not empty. Personal anchor is in the same chunk as the ender chest.

**Comment by dragonaslin** [comment]
did you fill it with ender pearls?

**Comment by Luckdemon** [comment]
Yes, with enderpearls, and the timer said 12:00 hours. The timer never started counting down though.

**Comment by Solidflip** [comment]
Did you visit the chunk it was in? you have to do that first for it to load

**Comment by Luckdemon** [comment]
Yes, it is in my base.

**Comment by Solidflip** [comment]
ill have to check this out ingame

**Comment by Luckdemon** [comment]
Issue appears to have fixed itself after removing and replacing the offending anchors multiple times.
