### ISSUE TITLE
Works crashes in mining age

### ISSUE THREAD

**Issue by Saffirastorm** [RTRGitHub/RTRRedux#38]
http://pastebin.com/pSUBadvJ9Q7A3T
http://pastebin.com/fA9Q7A3T

**Comment by Abouttabs** [comment]
As much as I can read from it it is Mystcraft freaking out because it "expects" different biome (why wa the paste removed since yesterday?). As for the "crash1" one I don't know really.. its kinda generic..
-Tabs
