### ISSUE TITLE
Applied Energistics Wrenches Consumed

### ISSUE THREAD

**Issue by Luckdemon** [RTRGitHub/RTRRedux#380]
The applied energistics wrench is the gateway to get into applied energistics. It is not consumed in normal crafting recipes, but when used in autocrafting, it does consume the wrench. Specifically it was autocrafted through an ME Crafting system to make an energy cell.

Googled it and could not find a cause or reasonable solution. Would advise people not autocraft with their wrenches or risk losing them also.

Solution to this instance: Refund Certus Quartz Wrench

**Comment by Solidflip** [comment]
item refunded by Dragon,
