### ISSUE TITLE
Flame Imp killed on server save/hostile mob kill

### ISSUE THREAD

**Issue by Luckdemon** [RTRGitHub/RTRRedux#381]
The server saving/hostile mob killing has killed my summoned Flame Imp from witchery. The imp is used in witchery trades to get souls that unlock more magic wand spells. The imp can only trade for the souls every few minutes. 
Please blacklist this monster from being killed by the server save, thank you.
I don't know the exact monster name or ID but it is from Witchery and called a Flame Imp.
In the meantime, the current solution is to store it in a safari net/soul vial/golden lasso in between uses.

**Comment by Solidflip** [comment]
unfortunately im unable to find a way to blacklist, have you tried a jailers safari net?

**Comment by Luckdemon** [comment]
Flame Imps cannot be captured in safari nets to avoid auto spawning them.

**Comment by Direcub10** [comment]
this is the same problem i had with witchery last map. Emoniph doesnt want his mobs autospawned (however stupidly complicated such a system to farm them would be) so they are uncapturable with safari nets. However, for lucks case the imp can be caught in a golden lasso and his timer will still be working. You could just trade with him, capture him, wait for a save, and by that point he'll be ready to go again. For the bosses however, there's no way around that except timing your fights like i was told to last map

**Comment by Direcub10** [comment]
I did the above and had all the spells in the same day including torment. i recommend grabbing some help for that fight btw

**Comment by Luckdemon** [comment]
Torment was easy, finished that. But the imp needs to remain in world, I believe, to use imp magic. In this case it won't be possible with them being killed every 30 minutes.

**Comment by Direcub10** [comment]
true, but isn't just pvp based magic anyway :D?

**Comment by Solidflip** [comment]
As there is no way to blacklist mobs (and i would have to whitelist all the others) this issue is moot. I would prioritize keeping lag off the server to having the slight inconvenience in having to respawn a mob.

**Comment by Luckdemon** [comment]
Agreed.
