### ISSUE TITLE
No access to a few commands

### ISSUE THREAD

**Issue by Luckdemon** [RTRGitHub/RTRRedux#383]
Commands that should be available to players:
/cofh friend gui
(it opens the cofh gui for adding friends who can use restricted access thermal expansion blocks)
and possibly
/warps (the command to list warps)

**Comment by Luckdemon** [comment]
As a note: yes cofh only has one permission node as of the last time I checked, but players need special extra permissions to use the killall and more administrative cofh commands, so giving people access to cofh friend gui won't let people killall.

**Comment by Luckdemon** [comment]
As a 2nd note: If cofh commands are still disabled, and cannot be enabled properly people can manually edit their cofh friend list client-side. The exact format is unknown to me, but you could add me or someone else as a friend and check for the exact format. The cofh friend list is stored locally under config\cofh\core\friends.cfg

EDIT -> THIS DOESN'T APPEAR TO ACTUALLY WORK

**Comment by Solidflip** [comment]
Unfortunately to give access to this command it would give access to other COFH commands. While you need to be opped for killall to work, people constantly complaining cofh tps isnt at exactly 20 100% of the time, would get annoying. 

For now you can edit the friends.cfg file directly to add friends. 

It would look like this:

# Configuration file

Your UUID {
    I:friend1=1
    I:friend2=1
    I:friend3=1
}
