### ISSUE TITLE
Personal Anchors don't work in the nether

### ISSUE THREAD

**Issue by Luckdemon** [RTRGitHub/RTRRedux#384]
As stated in title, slap down a machine and a personal anchor. If the machine does not chunkload itself (i.e. not an ender-quarry), it will not continue to operate once players leave the area. Yes the personal anchor is turned on, and running, it does consume ender pearls and it is lit up green instead of red.

**Comment by Solidflip** [comment]
Did you visit the place in the timespan? The personal anchor doesnt "load" chunks, it "keeps" them loaded. YOu have to visit it to first load it

**Comment by Luckdemon** [comment]
Yes it was loaded first and checked on after every reboot. Seems to only work with other people in the nether, will perform more tests.

**Comment by Luckdemon** [comment]
Confirmed on my end: Anchor does not function even with other players in the nether, but out of player range.

**Comment by Camtoe112** [comment]
Ill throw an admin anchor at the spawn point in the nether.
