### ISSUE TITLE
Spirits not spawning in spirit world

### ISSUE THREAD

**Issue by Luckdemon** [RTRGitHub/RTRRedux#386]
The mob "spirit" from witchery do not spawn in the spirit world as they should. After looking around for over an hour, including standing still 10+ minutes waiting for them to spawn around me, none were found.
Things I tried
- Standing still to allow spawns
- Exploring to find new spawns
- Looking in caves and sky as well as surface
- Moving to a vanilla biome and waiting (plains)
- Killing all mobs on minimap to promote new spawns

Link to spirit page on witchery wiki: https://sites.google.com/site/witcherymod/spirit

**Comment by Solidflip** [comment]
Yeah this happened last time someone went to this world.....

will investigate

**Comment by Direcub10** [comment]
increasing ths pawn rate didnt help btw solid, i just stole the ones u spawned in the starting area
