### ISSUE TITLE
Lost gear

### ISSUE THREAD

**Issue by Scttydsntknw85** [RTRGitHub/RTRRedux#388]
approx 22:30 (mountain time) I accidently slept at the top of my hang glide tower which is at x:-618 z:674 Y:136. I fell out of the world and all my stuff is gone.

items i remember having:
from tinkers construct:
iron pickaxe
iron shovel
iron axe
iron rapier
iron hammer
iron excavator
iron lumber axe
a ring of magentization
two buckets
various blocks 
and that is all i remember i had a bag of holding but i was informed that it will not be returned.

**Comment by Direcub10** [comment]
since when do they not refund BOHs?

**Comment by Camtoe112** [comment]
A moderator, either Luckdemon or Atrophy will refund you. Remember not to
sleep above Y level 128ish.

**Comment by Scttydsntknw85** [comment]
Atrophy refunded me!
