### ISSUE TITLE
Sleeping % not working in the skyblock world

### ISSUE THREAD

**Issue by Luckdemon** [RTRGitHub/RTRRedux#389]
Dimension 4 (the skyblock dimension) is not following the sleep percentage set in Morpheus to let people less than 100% sleep and make it daytime.
Morpheus config issue perhaps?

**Comment by Solidflip** [comment]
ya got me bro. works in the overworld....

**Comment by Direcub10** [comment]
i thought the skyblock world was where we all play and therefore the overworld

**Comment by Solidflip** [comment]
nope. Will fix with update
