### ISSUE TITLE
Nether portals can't be lit

### ISSUE THREAD

**Issue by Luckdemon** [RTRGitHub/RTRRedux#390]
As stated in title, lit nether portals do not form a portal.

**Comment by Volaunis** [comment]
It's possible that this is intentional. I've seen other modpacks where access to the nether was blocked in this way.

**Comment by Luckdemon** [comment]
The nether is void and empty anyways, not a real problem except for nether monsters' drops

**Comment by Solidflip** [comment]
nether portal is at spawn. Achievement fixed
