### ISSUE TITLE
Some hives not craftable

### ISSUE THREAD

**Issue by Luckdemon** [RTRGitHub/RTRRedux#393]
http://forum.feed-the-beast.com/threads/1-0-4-rock-hive-missing-recipe.150972/
https://bitbucket.org/Erasmus_Crowley/ex-nihilo/issues/8/hive-generation-extra-bees-and-magic-bees

Rock hive has no recipe in-game to craft it.

**Comment by Solidflip** [comment]
mods.thermalexpansion.Transposer.addFillRecipe(10000, exnihilo:bee_trap_treated, ExtraBees:hive:1, liquid:stone.seared \* 8000);

Probably just do that eh? stolen from that thread lol

ill do this in the morning

**Comment by Solidflip** [comment]
issue fixed!
http://puu.sh/ojwuh/c535e08576.jpg
