### ISSUE TITLE
'Most Likely' button in logistics request table results in disconnection

### ISSUE THREAD

**Issue by Xalorous** [RTRGitHub/RTRRedux#395]
logistics request table
used nei to select bspace module recipe
selected 'Most Likely' and crashed

**Here's the ACTUAL log.**
[crash.txt](https://github.com/RTRGitHub/RTRRedux/files/223024/crash.txt)

**Comment by Solidflip** [comment]
reported to mod author. Will uipdate as we go along

Link:
https://github.com/RS485/LogisticsPipes/issues/975
