### ISSUE TITLE
cofh commands

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#396]
can't use /cofh friend add or /cofh friend gui. These are needed, if I'm correct, to manage private tesseracts and private strongboxes

**Comment by Solidflip** [comment]
yeah i would have to give yall more permissions for /cofh than id like to achieve this. including /cofh tps. Instead of having people bitch about "tps is 19, fix it" im going to deny this

Make more tesseracts or have 1 person make them all.. sorry mate

**Comment by frogger35** [comment]
http://teamcofh.com/docs/cofh-core/features/commands/****

says friend has a permission of -1. im assuming that makes it so we can use it while tps has a permission of 0 making it so we can't use it.

**Comment by Solidflip** [comment]
but all these have the same permission node. If i give you /cofh friend, you get access to /cofh tps etc

The only one you dont get is /cofh killall because that requires op to kill things. Ive looked into it in the past, until they add more permission nodes, i cant do it
