### ISSUE TITLE
Crash when using Arcane crafting terminal

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#397]
Ill randomly crash whenever i try to craft something in the arcane crafting terminal. There seems to be no pattern in terms of what im crafting. the closed thing i could find in it was this https://github.com/Nividica/ThaumicEnergistics/issues/274 but im not using veiw cells in any part of my base
Pastebin: 
http://pastebin.com/0y6wS4xa

**Comment by dragonaslin** [comment]
problem will be fixed with next update

**Comment by Nividica** [comment]
A work-around until you can update is to place empty view cells in all of the view cell slots. Since they are empty they have no effect, and since they are there the terminal shouldn't cause a null crash.
