### ISSUE TITLE
crash to desktop on "/is go"

### ISSUE THREAD

**Issue by Xalorous** [RTRGitHub/RTRRedux#399]
minecraft log:
http://paste.feed-the-beast.com/view/f948074b

crashlog:
[crash-2016-04-19_19.21.47-client.txt](https://github.com/RTRGitHub/RTRRedux/files/227065/crash-2016-04-19_19.21.47-client.txt)

**Comment by Solidflip** [comment]
Are you able to get to your island by using /home?

**Comment by Xalorous** [comment]
I don't have home set.  But I was able to log back in and the movement from
/is go was complete.

**Comment by Abouttabs** [comment]
Any texture packs? optifine? I see issues with ex nihilo barrel being
rendered and fastcraft not liking it...

**Comment by Xalorous** [comment]
I'm using soartex invictus.  The only time this happened was when people were talking about it and blaming logistics pipes.

**Comment by Solidflip** [comment]
If it happens again i need a log. Clear your console, do the command and send me the console. Preferably in a pastebin
