### ISSUE TITLE
Ars Magicka Profile Reset

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#4]
Logged in today, and it seems all progress on my profile in relation to ars magicka was reset.

**Comment by UnsungCesspool** [comment]
Edit. Everything in the Occulus is still there, but I have lost all entries in my arcane compendium.

**Comment by Abouttabs** [comment]
so it didn't strip out your talents and skill points?

**Comment by UnsungCesspool** [comment]
Talents, skill points, and levels still remain. It reset all the unlocks i had in the compendium...the discoveries, basically.

**Comment by UnsungCesspool** [comment]
So apparently compendium data is stored client side. FML for reinstalling the modpack. :(
