### ISSUE TITLE
Witchery infusion won't unlock powers

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#400]
Whenever i try to infuse myself with one of the witchery superpowers, it just kills me instead. Im using the death protection poppets as intended and have kept it on me during the whole process. The poppet is definatly bound to me. it eats the soul of the world and destroys the poppet so this is destroying alot of resources. Ive followed this step by step https://sites.google.com/site/witcherymod/infusion-of-otherwhere-step-by-step

**Comment by Direcub10** [comment]
So many magicc deaths )_)

**Comment by Direcub10** [comment]
its all the infusions dragon

**Comment by Solidflip** [comment]
Good luck dragon =P i couldnt get this to work lol

**Comment by Direcub10** [comment]
just did it in single player is works

**Comment by Direcub10** [comment]
So, i tried doing it on the server with the golden laurel crown....it worked and it didnt break my crown so ya thats kewl

**Comment by dragonaslin** [comment]
so then that will hav to work till fixed
