### ISSUE TITLE
Draconic Evolution resurrected dragon sound is played in all worlds

### ISSUE THREAD

**Issue by Xalorous** [RTRGitHub/RTRRedux#401]
It doesn't make sense.

It is as annoying AF.

This thread mentions code that may fix it:
https://bukkit.org/threads/prevent-enderdragon-sound-from-being-played-on-all-worlds.162218/

I'd like to turn it off client side but I don't knwo which sound.

**Comment by Direcub10** [comment]
its a vanilla thing. just wait until frogger start grinding them to get all 3 of use draconic gear

**Comment by Solidflip** [comment]
Do you mean the death of it? I dont see that as such an issue. They should warn you its happening.

**Comment by Xalorous** [comment]
It's twice as loud as any other sound.  It plays everywhere.  IDGAF if someone is killing the dragon.  I should not have to mute the game because someone is farming the end dragon.

I think I found a solution for me.  I deleted the sound from my client.  I _think_ I got the one used by all FTB packs.

end.ogg is the sound file for anyone else looking to remove it.
