### ISSUE TITLE
Crafting Tinkers Arrows

### ISSUE THREAD

**Issue by Orbitus2001** [RTRGitHub/RTRRedux#402]
Was trying to craft some tinkers arrows for a bow and it wouldn't accept anything other than a wood tool rod.  Was trying a Shiny/Platinum arrow head, manyullyn tool rod, and slime leaf fletching.

**Comment by Direcub10** [comment]
u cant use metal tool rods. u can use blaze and wood as far as im aware

**Comment by Solidflip** [comment]
This is working as intended and not a bug. Its update to Tinkers. You can now use, i believe, Bone, Blaze rod, Stick and possibly sugar cane
