### ISSUE TITLE
primordial pearl ?

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#404]
the thaumcraft portal leads to a black world where most forms of flight do not work. so how does one get the primordial pearl which one usually gets from the boss in that dimension ?

**Comment by MrAtrophy** [comment]
ok so the outlands is fucked, there is one maze and it has been emptied , no boss. I am thinking if someone can open the portal in front of a mod or admin we hand them one pearl. they can be duplicated but with a tier 6 blood alter.   how does that sound ?

**Comment by Direcub10** [comment]
Delete the dimension

**Comment by Solidflip** [comment]
dimension will be reset tomorrow

**Comment by torsteig** [comment]
After Dragonaslin reset the dimension, I still spawned outside the dungeon, and had to break my way in. When Atrophy tried to go into his own, he spawned in the same dungeon that I did.

**Comment by Solidflip** [comment]
atrohpy's suggestion implemented
