### ISSUE TITLE
Spirit World And baubles

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#406]
so i went to the spirit world to see if it was a void. theres a nightmare that chaases u around while ur there. when u die ur supposed to wake up where u drank the potion with all ur shit. when i woke up i had lla my items except for my baubles. they are all replaceable except for my ring of aesir and way i can get a refund?

**Comment by dragonaslin** [comment]
its another witchery bug unfortunatly that is waiting to be fixed. Big suprise.when you get on i will refund and for now take baubles off when you go.
