### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by CalvinJJ** [RTRGitHub/RTRRedux#407]
Had a crash to desktop when I was scanning things with the lens from thaumcraft. Now whenever I try and join the server it crashes. Tried reinstalling the mod pack, java, nothing works.

Minecraft.log: http://paste.feed-the-beast.com/view/567f1c8d

Crash log:
[crash-2016-04-25_19.53.51-client.txt](https://github.com/RTRGitHub/RTRRedux/files/235810/crash-2016-04-25_19.53.51-client.txt)

**Comment by Abouttabs** [comment]
Someone please try to take the scanner from his hands, it's freaking out
about rendering something from enderIO (probably block of ender..)

**Comment by CalvinJJ** [comment]
I'm hoping/assuming there's a way to do that server side... it crashes before I even have control, so I can't throw it or anything.

**Comment by Abouttabs** [comment]
anyone that can either force tp you, or acess your inventory...

**Comment by Solidflip** [comment]
Poke a mod/admin in ts to move you when you next try to login
