### ISSUE TITLE
use core golem issue

### ISSUE THREAD

**Issue by MrAtrophy** [RTRGitHub/RTRRedux#408]
golem with use core can normally plant trees, it looks like the island permissions is not letting him plant or break blocks. 

I think I need to some how give the golem permission to do this,. I do not know how.

**Comment by Solidflip** [comment]
do other golems work?

**Comment by MrAtrophy** [comment]
the chopper works and the picker upper . but placing blocks seems to be the hang up

**Comment by dragonaslin** [comment]
does the golem grab the sapling out of the chest?

**Comment by MrAtrophy** [comment]
yes, then tries to plant it , you can hear it planting over and over , but never actually planting

**Comment by Direcub10** [comment]
edit the island perms

**Comment by MrAtrophy** [comment]
editing the island permissions worked, but I would prefer to give the golems permission rather than changing the whole islands settings.

**Comment by dragonaslin** [comment]
thats good
