### ISSUE TITLE
idle timer

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#420]
Please bump to 5 or 10 minutes. Being kicked for reading a book in game after 1 minute kinda sucks. Cheers

**Comment by frogger35** [comment]
:D issue 420

**Comment by Solidflip** [comment]
youre a goober lol

Timer is set to 8 mins. Please test and get back to me

**Comment by frogger35** [comment]
yeah dragon resets it

**Comment by Solidflip** [comment]
good
