### ISSUE TITLE
Fluxed Crystal Crafting Not Giving Right Crystals

### ISSUE THREAD

**Issue by Orbitus2001** [RTRGitHub/RTRRedux#425]
I crafted the Obsidian fluxed crystal seed and I infused 32 obsidian with a universal seed and it gave me a leather seed instead of the Obsidian seed.  Luck gave me the obsidian seeds for the 2 leather ones that I made but if I or anyone else want to make another Obsidian seed it doesn't work properly.  Same with the Certus Quartz seeds.  I received the blaze seeds for that one when I crafted it.

**Comment by Luckdemon** [comment]
Fluxed crystals has several known issues with it at the moment, there is an update to fix a few of them in the next pack update. I would stay tuned and see if the next update fixes these issues.

**Comment by Solidflip** [comment]
Which seeds are bugged?

**Comment by Orbitus2001** [comment]
So far from what I have crafted, Obsidian and Certus Quartz seeds.  Obsidian gave me leather seeds and certus seeds gave me blaze seeds.  I made a leather seed and got a leather seed from it.

**Comment by Orbitus2001** [comment]
Found another one.  I was making yellorium seeds and the recipe said it needs 1 yellorium to infuse the seed.  It didn't work.  So I put 32 yellorium like the other seeds and got a gold seed, so another seed that is bugged.

**Comment by Orbitus2001** [comment]
Got another one, was going going for soul sand seeds and got redstone seeds.

**Comment by Orbitus2001** [comment]
And another one, was making lead seeds and got gold seeds.

**Comment by Solidflip** [comment]
will be fixed in next update reported to pack author
