### ISSUE TITLE
Chests randomly emptied.

### ISSUE THREAD

**Issue by Xalorous** [RTRGitHub/RTRRedux#426]
Contents of multiple chests disappeared.

This happened previously on IE:E pack.  This feels like a glitch, not an incident of griefing, since the items that were lost were complete contents of several chests, not just the items someone would value.

The bees and pams gardens hurt the most, because I ranged around exploring to find those, and I'm not sure I left any bees within 1000 blocks of my house.

I lost the following:
Average 2 stacks of common ores:
- Iron
- Gold
- Silver
- Lead
- Tin
- Copper
- Osmium
- Tritanium

Stack of:
- Aluminum

Average half stack:
- dilithium
- shiny

Wood and Saplings:
- 6 stacks birch
- 2 stacks birch saplings
- 1 stack rubber wood
- 1 stack rubber droplet thingies
- 1/4 stack rubber saplings
- 1 stack eucalyptus
- 1/4 stack eucalyptus sapling
- 1/2 stack tiger wood
- 4 tiger wood saplings
- 1/2 stack purple wood (I dunno the name)
- 4 saplings from teh purple wood

Pams:
- 1/4 stack each of the gardens (except the desert one.  I only had 2 of those)

Bees:
1 chest full of assorted 'mundane' princesses and drones.  Since I had a double chest full, and only half are gone, I don't know how to figure out which ones were lost.

Misc:
- 2 each AE2 inscriber plate (except silicon which I had 1)
- 1/2 stack skystone
- 2 skystone chests
- 1 stack of clay
- 4 stacks of gravel
- 2 stacks of sand
- 10 stacks of cobble
- 5 stacks of stone
- 1 ender pouch
- thaumcraft goggles

Ferret stuff:
Rae refunded my big ticket items (Res. Jet Pack and diamond dolly) that I remembered.
I need my hqm book reset so I can redo the quests

**Comment by Solidflip** [comment]
items returned
