### ISSUE TITLE
Rouguelike Dungeon n' MyWorldGen quest

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#427]
The Laudanum the quest wants is not the same as the laudaunm renamed potion you get from the dungeons. Therefor making the quest unobtainable. I might be trying to submit the wrong potion but I believe I am doing it right. The potion it wants is of id 373:8201 renamed to Laudanum. There is no laundanum potion in NEI.

**Comment by Luckdemon** [comment]
Known issue with modpack, to be fixed in a future update.

**Comment by Solidflip** [comment]
issue reported to modpack author, expect fix in next update
