### ISSUE TITLE
What to update (we didnt want to do it today..)

### ISSUE THREAD

**Issue by Abouttabs** [RTRGitHub/RTRRedux#43]
http://projectredwiki.com/wiki/Version_archive#Downloads -all
http://www.railcraft.info/releases 
http://stevescarts2.wikispaces.com/Download
http://minecraft.curseforge.com/mc-mods/veinminer/files/
http://minecraft.curseforge.com/mc-mods/waila/
http://www.curse.com/mc-mods/minecraft/witchery
radio stations
http://www.openperipheral.info/

**Comment by Stadniuk** [comment]
Everything done except for Project Red (pain in the arse)
