### ISSUE TITLE
fancy workbench

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#430]
In the quest book section 9, Quest:No Writer's Block 2nd chapter, a fancy workbench is the requested item for the quest. I know it was banned for a reason. Any way for it be unbanned for crafting but banned from placing? If not is there a way we can get it from the mods or admins in exchange for the material requirement?

**Comment by Solidflip** [comment]
seek an admin for the quest requirement, might work that way, Unfortunately we cant unban due to its bugged nature
