### ISSUE TITLE
Bugged quest/crafting recipe.

### ISSUE THREAD

**Issue by Orbitus2001** [RTRGitHub/RTRRedux#433]
Was trying to craft a weather obelisk and the "weather crystal" part of it says it just needs a diamond in the crafting window to craft it.  I tried that and all it gives is 9 diamond nuggets.  I looked up the standard Ender IO recipe which is a diamond, a cake, a bucket of water, and a bucket of lava and that didn't work either.  I need the crystal to craft the obelisk.

**Comment by frogger35** [comment]
Can confirm. Weather crystal can't be made from what NEI says and the recipe found here on the [Ender IO wiki](http://wiki.enderio.com/Weather_Crystal) doesn't work either.

**Comment by dragonaslin** [comment]
will have another go at it later for now get reazar to trade you some for diamonds

**Comment by Solidflip** [comment]
will be fixed in update reported to pack author
