### ISSUE TITLE
Banned Elemental Fire Blocking TTKami Unlock

### ISSUE THREAD

**Issue by Blueberypie** [RTRGitHub/RTRRedux#434]
I just finished every research in thaumcraft (when i use blank research notes they turn back into knowledge fragments) and the Ichor research is still unavailable. It appeared earlier today and I clicked to research but it gave a chat mesage saying "you dont have the required knowledge". After I logged off the research was not there anymore.

**Comment by dragonaslin** [comment]
the only thing that should be banned there is the air imbued fire

**Comment by Solidflip** [comment]
conflict with the Configs server to client. Change lines 46/47 to false in the Thaumic Tinkerer config client side, Then reconnect to the server and you should be fine.
