### ISSUE TITLE
Kurtlemop can't log in still

### ISSUE THREAD

**Issue by Kurtlemop** [RTRGitHub/RTRRedux#435]
After the end event, I was morphed into a wisp and flying around. Solid shot me with his rocket launcher and I died. After reviving at spawn, I typed /back to get back to my body, but instead got disconnected from the server. Trying to rejoin gives the "Fatal Error has occured, this connection is terminated" message. I've restarted my client, and even deleted the Ferret business folder and redownloaded it, but its still throwing the same error message. This is a link to the most recent Console log when it happened. http://pastebin.com/DhnwGPpL

**Comment by Solidflip** [comment]
missing some of the log dude. But i think it might be due to your location from your previous logs. Have you done Thaumcraft or anything like that? If not deleting your nbt should fix you.

**Comment by dragonaslin** [comment]
fixed and solid no more rockets
