### ISSUE TITLE
Mining world Birds

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#436]
Birds are spawning at the mining world spawn. Entitiy count using f3 was well over 100. It takes a much greater time to load into the mining world because of those birds. I have timed out twice due to them. Any way to stop those birds or all mobs from spawning so close to spawn in such massive quantities?

**Comment by Solidflip** [comment]
will create a worldguard zone with no spawns in a bit

**Comment by dragonaslin** [comment]
put up a world gaurd no birds.
