### ISSUE TITLE
ae2 facade fix

### ISSUE THREAD

**Issue by MonoToast** [RTRGitHub/RTRRedux#438]
the numbers are the line numbers in the config file for the ae2
C:\FTB_Launcher\TheFerretBusiness\minecraft\config\AppliedEnergistics2\facade.cfg
sandstone
8434
8435
8436
stone
8498
stonebrick
8499
8500
8501
8502

**Comment by Solidflip** [comment]
Ok buddy this tells me nothing. Whats wrong? What is this fix supposed to do? ETC.ETC>

**Comment by frogger35** [comment]
In the facade.cfg for AE2 these specific items are set to false to be crafted into facades. We don't know why( haven't really dived into this issue). Mono would like these specific blocks to be turned to true for aesthetic reasons.

**Comment by dragonaslin** [comment]
all the ones asked are now true upon next restart

**Comment by MonoToast** [comment]
thanks
