### ISSUE TITLE
mekenism installer upgrade 

### ISSUE THREAD

**Issue by MonoToast** [RTRGitHub/RTRRedux#439]
the basic advance and elite factory installer item id 5509 5509:1 5509:2 are turning any meknism  machine that i put them on in to smelter factory of that tier

**Comment by dragonaslin** [comment]
if solid is on ask him about it he is the mekanism wisperer. If not i will look at it tonight. Sry for the wait.

**Comment by Solidflip** [comment]
This didnt happen to me because i just craft them into factories with the crafting recipe.

**Comment by MonoToast** [comment]
do you put them in that crafting square the basic machine and the advanced factory installers to turn in to the next tier of that factory 

what i had though is the ae2 make the upgrade hope that i could upgrade them that way so i dont have to make a recipe for all of the machines this way i could just make the base machine hit with the upgrade and ta da but instead it turns in to a smelter did not know if this was a glicht or if there is a better way to do it
thanks thou

**Comment by Direcub10** [comment]
i did it and they stayed as their respective machines

**Comment by Solidflip** [comment]
shits broke yo....reported to mod author. In the mean time just use the crafting recipe

**Comment by MonoToast** [comment]
k i going to report that to the mod author thanks
