### ISSUE TITLE
Sniper Scope

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#440]
Sniper scope from matter overdrive can't be crafted. EndEnemy and myself both tried to make them. I don't know if they are disabled or what. There is a conflict of ID's between crafted glass panes and the ones required for the recipe. The crafted panes ID is 102, the panes ID required for recipe is 102:13.

**Comment by MonoToast** [comment]
i build a sniper scope have on my ion sniper

**Comment by Solidflip** [comment]
yeah issue fixed yo
