### ISSUE TITLE
Sleeping Bag: Fall out of the world

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#441]
I tried to sleep with a Sleeping Bag and fell out of the world.
I also got problems with normal vanilla beds: When i try to sleep i get void demage.
Got this issue since i live above 150 blocks.

looks like this old issue from 1.4.6:
https://bugs.mojang.com/browse/MC-3599

Would be wonderful if an admin/moderator could help me searching for my grave below bedrock.
My death point is at
x 4744 
y -180 
z -972

End.

**Comment by dragonaslin** [comment]
ya i can help and its been a problem for a while so make a bed lower in your base
