### ISSUE TITLE
Personal Chunk loading

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#442]
I know this is a really crappy topic but we need some sort of chunk loading that loads for more than when we are on. Three times I have activated my fusion reactor only to dc from a ticking screen or a time out and now my fusion reactor has reset.  This resetting is a huge issue since it take awhile to produce all the necessary fuels for the reaction. Now it doesn't need to load forever after we are off but for maybe an hour or two would be amazing. Heck 30 minutes of loading would be great! That's more then enough time to recover from a crash and get back in the game without progress being reset cause of chunk loading errors. Our current way of loading chunks is awesome. I like how the server is free with resources and we can play without crazy contraptions taking all the resources of the server. That said I don't believe 30 extra minutes of a crazy contraption running will adversely effect the server  when the owner logs off for the night. Sure someone could build a lag machine that destroys the server resources but our amazing mod and admin team will deliver swift justice to that individual. So in conclusion to this wall of text, Just a little extra chunk loading after one of us log off would be so very helpful in not having progress reset.

**Comment by Direcub10** [comment]
I didnt know frogger's vocabulary had the capacity for that much suck up-ing

**Comment by dragonaslin** [comment]
the thing is, if i let  you then everyone can and if we have a bunch of people having everything chunk loaded and creating lagg for the people who are on,its not fair to them. Also if it starts to lag i would go around shuttig things off anyway.

**Comment by dragonaslin** [comment]
but ill look into 30 min

**Comment by dragonaslin** [comment]
with the dimentional anchors you cant toggle it. sry
