### ISSUE TITLE
Inventory Lost

### ISSUE THREAD

**Issue by FinePoints** [RTRGitHub/RTRRedux#443]
Dire PVP'ed me while I was morphed as a chicken.  I go back to get my gravestone and all I got was some red clay.  Any help with my ruffled feathers that were lost would be awesome. I don't need any more red cly. You can have that.

**Comment by Direcub10** [comment]
i hope theres no hard boiled feelings

**Comment by dragonaslin** [comment]
ya i can if ya tell me what you lost
