### ISSUE TITLE
COFH friend command

### ISSUE THREAD

**Issue by VicenteRD** [RTRGitHub/RTRRedux#451]
Hey, we do not have access to cofh friend command, and I feel like it's needed, since that way we can have restricted access to our Thermal Expansion machines - mostly Tesseracts.
With the latter case, you have 3 setup options:
Public channels, in which anyone is able to use them and thus take items/fluids/energy from them.
Private channels, in which only you can do that.
Restricted mode, which is essentially using private channels, but your friends are able to access the Tesseract and modify it.

For the restricted mode, you have to tell Thermal Expansion who your friends are, and that is done via cofh friend command.

Info: http://teamcofh.com/docs/cofh-core/features/commands/

Seems COFH doesn't handle permission nodes very well, so I'm unable to tell how it's done, but according to that page, we just need level -1 permission, giving us access to 'version', 'help', 'syntax' and 'friend', which seems fine.

**Comment by Solidflip** [comment]
https://github.com/RTRGitHub/RTRRedux/issues/396

tried it before, cant do it. it doesnt do anything when i give people the permission node.
