### ISSUE TITLE
Autorank Disabled?

### ISSUE THREAD

**Issue by altoidsyn** [RTRGitHub/RTRRedux#453]
Just wanted to ask why Autorank is disabled. It seems like part of playing it building up your rank and if AR is disabled, is it still tracking time played? (Which I know is different from the one reported in FTB Utilities.)

**Comment by Solidflip** [comment]
It sholdnt be disabled? You should be ranking up based on in-game time

**Comment by Solidflip** [comment]
Mmmm conflict with McMMO, removing it to see if it fixes

**Comment by Solidflip** [comment]
issue resolved. Thank you altoid

**Comment by altoidsyn** [comment]
Issue has resurfaced. AR is down again
