### ISSUE TITLE
Very Minor Issue: Luminizer at spawn bridge protected

### ISSUE THREAD

**Issue by altoidsyn** [RTRGitHub/RTRRedux#454]
There is a fast travel Luminizer from Botania on the right side of the spawn bridge that you can't actually use until you leave the spawn area (The message telling you you're leaving spawn seems to be the cut off, about halfway across the bridge) it's a minor issue, but someone has put a sign next to it telling people to use it and it doesn't work.

**Comment by dragonaslin** [comment]
ok ty

**Comment by Solidflip** [comment]
issue fixed. Wg region interact
