### ISSUE TITLE
Forestry Backpacks

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#457]
Are not function as they should.

Ores and Ingots don't automatically go into the bag. See item ID 4990

Maybe config needs adjusting?

**Comment by Solidflip** [comment]
will delete config when server restarts

**Comment by dragonaslin** [comment]
deleted config and waiting for restart to see if that helped

**Comment by dragonaslin** [comment]
still not working.will have to look further into it.
