### ISSUE TITLE
Veinminer hammer ASAP

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#458]
Remove hammers from veinminer ASAP, constantly timing people out of the server.

**Comment by dragonaslin** [comment]
its not even in list so now i changed that you have to use the vanilla tools

**Comment by Camtoe112** [comment]
We're gonna wanna fix that back to use tinker tools. Maybe just make it possible to not make stone veinminable.

**Comment by dragonaslin** [comment]
thats not possible there is either all blocks or have to manually add every tool with blocks allowed. so will have to make it so you cant use tinkers to vein mine
