### ISSUE TITLE
Carpenter blocks issue with protection 

### ISSUE THREAD

**Issue by MonoToast** [RTRGitHub/RTRRedux#460]
here is where the config is 
FTB_Launcher\FTBInfinity\minecraft\config\CarpentersBlocks.cfg
the line with config is line number 45
what is happening is halke places a carpenter block when this happens i can not do any thing to it but break and place it back down the config to change will say this B:"Enable Ownership"=false

**Comment by MonoToast** [comment]
it will say true my bad

**Comment by MonoToast** [comment]
plz change to what i have thanks

**Comment by dragonaslin** [comment]
was changed and will take effect next restart
