### ISSUE TITLE
Recipe change 

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#472]
Replace all recipes that require a dragon egg with a nether star instead.

Oblivion Frame
Sun Dial

**Comment by dragonaslin** [comment]
will do tommorow sry brain hurts

**Comment by dragonaslin** [comment]
working on it now

**Comment by dragonaslin** [comment]
got sundial frame isnt working

**Comment by Direcub10** [comment]
@witcheryAltar?
