### ISSUE TITLE
Increase for player chunks

### ISSUE THREAD

**Issue by Raezar** [RTRGitHub/RTRRedux#474]
I have had people ask about an increase in claimed chuncks.  I think we should add them as a rank reward for time played as follows:
10-Peasant
25-Commoner
35-Farmer
45-Squire
55-Initiate
65-Knight
75-Baron
85-Count
95-Viscount
105-Duke
115-Prince
125-Archduke
135-Viceroy
150-Knights Commander

**Comment by Camtoe112** [comment]
I like it, let's see if we can get this working.

**Comment by dragonaslin** [comment]
will look into it
