### ISSUE TITLE
Rider from runic dungeons

### ISSUE THREAD

**Issue by SniperPro55** [RTRGitHub/RTRRedux#478]
the server RIP's when you have someone on your head then you try to ride someone else ID:7022/7023

**Comment by Direcub10** [comment]
why use wip items........

**Comment by dragonaslin** [comment]
so whats the problem... you cant ride on someones head?

**Comment by SniperPro55** [comment]
we were playing with it but when someone was on my head from stack mode, then trying to ride another player/ the server closed

**Comment by dragonaslin** [comment]
Its bugged and is banned for crashing
