### ISSUE TITLE
Recepe change required

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#481]
http://imgur.com/a/FwCfc

Makes more difficult to obtain.

Players have been getting irritated that people are changing the time and weather back and forth.

This could be implemented to avoid getting rid of it, while making it more difficult to obtain.

**Comment by Camtoe112** [comment]
...maybe this too. I need to edit it to make it harder.

http://imgur.com/a/E9IjA

**Comment by dragonaslin** [comment]
isnt it pointless at this time since the people that are complaining about it already have the sun dial?

**Comment by dragonaslin** [comment]
and ill look at the energy cell when i get bac from supper

**Comment by Solidflip** [comment]
issue is a moot point. item removed
