### ISSUE TITLE
Count/Viscount permissions

### ISSUE THREAD

**Issue by VicenteRD** [RTRGitHub/RTRRedux#486]
Viscounts lose permission to do /top (Count rank perk),
and Counts somehow have access to /back, which is a Prince rank perk...

**Comment by VicenteRD** [comment]
Addendum: I also can't set more than 1 home and i can't do /delhome
(I'm a viscount)

**Comment by Solidflip** [comment]
permissions fixed, sorry dude

**Comment by VicenteRD** [comment]
All good, thanks!
