### ISSUE TITLE
Request to add items to VeinMiner

### ISSUE THREAD

**Issue by Kyle-A-Cooley** [RTRGitHub/RTRRedux#490]
**Axe-**
MineFactoryReloaded:rubberwood.log

**Shovel-**
TConstruct:GravelOre
TConstruct:GravelOre/1
TConstruct:GravelOre/2
TConstruct:GravelOre/3
TConstruct:GravelOre/4
TConstruct:GravelOre/5

**Comment by Solidflip** [comment]
done
