### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by SniperPro55** [RTRGitHub/RTRRedux#492]
Certain listed abilities not availalbe to appropriate rank
example: Currently Duke rank and unable to use the /top rank that is available at Viscount; along with listed abilities as shown on the Viscount and Regent Panels of [DoubleJump] & [SpeedBoost]
![screenshot_4](https://cloud.githubusercontent.com/assets/1764786/18037080/a9ebaad0-6d49-11e6-8466-d24db657fcad.png)

**Comment by Solidflip** [comment]
fixed the /top

Soup will fix the other part when he returns as its his thing.....Friday
