### ISSUE TITLE
Request to add tools to veinminer

### ISSUE THREAD

**Issue by Kyle-A-Cooley** [RTRGitHub/RTRRedux#497]
Request to add hammer to pick axe category, excavator to shovel, and mattock to their respective categories.

Also would be nice to have IC2 rubber trees in there as well. thanks!

**Comment by dragonaslin** [comment]
i cant do that. especially the hammer and excavator because the 3 by 3 it does and added with veinminer crashes server and is why it was changed in the first place.i will look at the tree
