### ISSUE TITLE
Ichorcloth armor

### ISSUE THREAD

**Issue by CalenMC** [RTRGitHub/RTRRedux#50]
When you disable the functionality of boots, all pieces seem to stop working.

It may have something to do with me having a certain combination of enchants, but now all of the special functionalities stopped working, including flight.

And there's no way I can get the functionality back. Maybe by getting a new set of armor from creative, but I'll have to test that.
(creative plx?)

**Comment by CalenMC** [comment]
I suspect the main culprit is Slow Fall 3 on boots kicking in, and the game somehow thinking I have flight still. I tried drinking milk to cancel any buffs/debuffs, but that has no effect on this issue.

**Comment by CalenMC** [comment]
Just got creative thanks to donkey. Replacing the armor didn't fix the issue. I still can't fly with my TC armor.

**Comment by CalenMC** [comment]
Stuff I tried to fix it so far:
- restart client
- kill myself several times
- drink milk
- replace the armor from creative
  None of it worked.

Only thing I can think of now is deleting my player cache file on the server, after which I'll need creative for a bit to unlock all thaumcraft research again, and most of the AM2 spells too.
And some way to get up to level 47 in AM2 again.

Can you guys think of a less drastic solution?

**Comment by CalenMC** [comment]
Oh, just realized, maybe a server reset would fix it too. Haven't tried that yet.

**Comment by CalenMC** [comment]
Server restart didn't fix it either.

**Comment by CalenMC** [comment]
I got Lyzzie to try the armor set too, she couldn't fly with it either. Did some config change?

**Comment by CalenMC** [comment]
I tried recreating what I did in singleplayer, but flight still works there after all the stuff I did that seems to have broken it in multiplayer.

Therefor I assume it's a server (config?) thing.

**Comment by kenny608uk** [comment]
Possibly, I'll take a look soon might be a bug/plugin issue though the latter is unlikely
