### ISSUE TITLE
Too much data on my character.

### ISSUE THREAD

**Issue by Kyle-A-Cooley** [RTRGitHub/RTRRedux#500]
also, i still cant log on. because of my ME drives crashing me

**Comment by Solidflip** [comment]
Hey phallicies, what we needed was a log from you to see why you were crashing, thats why i said put it on the github. 

However i believe from what rae said you have an NBT overflow issue, If you could meet me in ts i can see if i can fix it with minimal loss to your inv.

**Comment by Kyle-A-Cooley** [comment]
Yeah, my work schedule got harder for me to get on at night, i do have an NBT overflow issue resulting from a resonant cache in my inventory that has 4k ME drives in it.

**Comment by Solidflip** [comment]
issue dealth with, moved the items over with nbtedit
