### ISSUE TITLE
Steam boiler

### ISSUE THREAD

**Issue by xXlucidXx** [RTRGitHub/RTRRedux#501]
The steam boiler from minefactory reloaded is not craft able nor does it give us a recipe

**Comment by Kyle-A-Cooley** [comment]
the steam boiler is probably too easy to make for steam so it was disabled in infinity evolved config files. like a lot of other power options sadly

**Comment by xXlucidXx** [comment]
True but it dosent seem cheap with the normal recipe

**Comment by Souperhero** [comment]
Disabled in base FTB Infinity Evolved Expert mode, likely due to being used in creating infinite free energy via BR turbines, after the initial setup.

Should remain disabled as intended.

Issue closed...
