### ISSUE TITLE
Real Industrial Radio

### ISSUE THREAD

**Issue by CalenMC** [RTRGitHub/RTRRedux#51]
This radio station thingy is broken. It says "unknown error" when I try playing it.

**Comment by kenny608uk** [comment]
I have no idea what this is lol, do you mean the tuning crystal or is it from another mod?

**Comment by CalenMC** [comment]
Yeah, when I put in the tuning crystal "Real Industrial Radio" (ID 15254:8) it gives an error instead of playing music.
Sorry, I thought the first bit was enough information. Forgot I had to call it a tuning crystal to make it clear what it was.
