### ISSUE TITLE
books

### ISSUE THREAD

**Issue by SniperPro55** [RTRGitHub/RTRRedux#510]
hard crash when trying to set a specific book inside the typesetting table when trying to copy a big writing book from bibliocraft

**Comment by dragonaslin** [comment]
are you trying to copy queens book?

**Comment by SniperPro55** [comment]
Yea she was wanting copies and the typesetting table didn't like trying to set the book :p

**Comment by dragonaslin** [comment]
he normal book is bugged right now and will have to wait for a message back from the mod author
