### ISSUE TITLE
Forestry Backpacks not taking items.

### ISSUE THREAD

**Issue by Kurtlemop** [RTRGitHub/RTRRedux#511]
Forestry backpacks can't hold any of the typical items that people would use them for. A google search resulted in a known config file problem where the items oredic info is missing, so the backpack doesn't know to accept those items. I fixed it on my side, but the bags are still rejecting items. I'm assuming that is happening because the server-side config files haven't been updated and are still missing that information. Here is a link to the pastebin where i found the information that should be in there. [http://pastebin.com/SfP8RWMw](url)

**Comment by dragonaslin** [comment]
your link comes up with an error 404

**Comment by Kurtlemop** [comment]
Something happened with the link when i input it, if you copy and past the link, it works

**Comment by dragonaslin** [comment]
the backpacks are all messed up and have been for a while ill have to message mod author and will get back with you.
