### ISSUE TITLE
Beegonia Recipe

### ISSUE THREAD

**Issue by Artaine** [RTRGitHub/RTRRedux#512]
The NEI recipe for the Botania Beegonia does not work properly. After adding the indicated ingredients to the petal apothecary, a check mark appears (which indicates the recipe is recognized), and the apothecary requests a seed. After adding the seed the flower creation particle effect goes off but no flower is generated.

**Comment by dragonaslin** [comment]
had to change recipe to the updated one that the mod author needed. fixed now
