### ISSUE TITLE
Player chunk Loading

### ISSUE THREAD

**Issue by Souperhero** [RTRGitHub/RTRRedux#513]
To assist with some server lag, it may be in our best interest to decrease the MCPlayer chunk loading from what it's currently at (something like 11x11) to 3x3 or 5x5.

I would do it, but I have no idea where it is in the configs. If anyone else knows, go for it. =D

**Comment by dragonaslin** [comment]
you can change the render distance but dont think it will work the way you want it to

**Comment by Souperhero** [comment]
No it did, I went ahead and changed it from 10 to 5. 

TPS never dipped below 16tps
