### ISSUE TITLE
TTKami

### ISSUE THREAD

**Issue by AccordNoir** [RTRGitHub/RTRRedux#514]
I have done all needed research to unlock TTKami items in the Thaumonomicon.
The Ichor research is even lit up to where i can get the research for it, but everytime i click on it it says i lack the knowledge to understand this research.
The only research still available in the book is the elemental fire's which have been disabled so they should not count against it.
Below is what happens when i try to click the research.
[http://prntscr.com/crwy73](url)

**Comment by Direcub10** [comment]
even if they are disabled, they still need to be researched of they appear in the book
