### ISSUE TITLE
keep inventory needs set to false

### ISSUE THREAD

**Issue by Raezar** [RTRGitHub/RTRRedux#516]

**Comment by Raezar** [comment]
keep inventory is set to true, so we are keeping inventory when dying and also getting graves

**Comment by Souperhero** [comment]
Contacted their github.

I will attempt to see if the configs in open blocks comingle with it.

already set game property to keepInventory = false.

**Comment by Souperhero** [comment]
checked MCclans and Project Inventories. Not them
Attempting to remove all greifprevention files..its not GP

**Comment by Solidflip** [comment]
Issue is with sponge. I took all the mods/plugins out and it still persisted. I alerted them on their IRC and created an issue on their github.

**Comment by Solidflip** [comment]
Until we get something back from sponge this issue is moot. Ive singled out the dupe issue was with the gravestone mod. To remove the dupe i removed the mod. People can still connect. Issue is hopefully fixed in the next pack release.
