### ISSUE TITLE
[Question] Is it time for a Map Reset?

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#52]
Its been almost 4 months since the map went live. We've added/removed mods, and changed the pack a lot over this time. 

Do you think its time for a full map reset? 

/discuss

-Cess

**Comment by kenny608uk** [comment]
We're adding a whole new world so those who feel like this can if they like, start fresh with new ATG terrain and ore gen

**Comment by UnsungCesspool** [comment]
Would machines and automation be allowed there, assuming your base in the main world is not really loaded?
