### ISSUE TITLE
Can't login afther server maintenance

### ISSUE THREAD

**Issue by Nathie1000** [RTRGitHub/RTRRedux#523]
As of the server maintenance last week (18-10-2016) i can no longer log in, whilst other people
can.
The pre-login screen displays the following message: "The server is undergoing maintenance. Do not attept to login."
If i do attempt to login i get the following message: 
"Failed to connect to the  server 
This server  requires FML/Forge  to be installed. contact your server admin for more  details."

The log of the login attempt can be found here: http://pastebin.com/qrcWp0pV
I do not know where the "missing mods" comes from since they work just fine in SSP.

I have tried to login directly via the  following ip: 142.4.200.221
I can ping this address without problem.

My friend seems to have the same problem, we're both from the Netherlands.

I have  checked the obvious suolutions:
- I have the correct mod pack installed.
- I have reinstalled the (correct) mod pack.
- Resetting local caches.
- Restarting my pc. (Not sure what that would have solved, but hey)

**Comment by dragonaslin** [comment]
this is not all of the crash report plz send more

**Comment by Solidflip** [comment]
yea you have the incorrect modpack. That many incorrect mods can only mean wrong pack.

Remember we are running Avant 3 now

**Comment by Nathie1000** [comment]
Ok i somehow missed the announcement that the modpack was changed.
This issue can be closed.

**Comment by Solidflip** [comment]
np dude
