### ISSUE TITLE
McMMO Fist bug

### ISSUE THREAD

**Issue by AccordNoir** [RTRGitHub/RTRRedux#524]
It seems occasionally when activating McMMO's fist activation, you lose the ability to move items around in your inventory, it can also cause you to lose items if you try to shift click items while this is happening. The only way to stop is to reactivate the "fist mode", and this seems to only sometimes do it.

**Comment by Souperhero** [comment]
changed from false to

```
"saitama_punch" {
    blocked=true
```

**Comment by Souperhero** [comment]
Someone will have to look into it, as far as disabling it.

For now just wait for _your hand to lower_ 

Do not disable plugin

**Comment by Solidflip** [comment]
Removed plugin due to dupes
