### ISSUE TITLE
claims

### ISSUE THREAD

**Issue by SniperPro55** [RTRGitHub/RTRRedux#525]
need perms for /trust to add basemates

**Comment by Souperhero** [comment]
Added to default group

griefprevention.claim.create
griefprevention.claim.visualize-claims
griefprevention.claim.command.abandon
griefprevention.claim.command.give-book
griefprevention.claim.command.basic-mode
griefprevention.claim.command.set-name
griefprevention.claim.command.set-farewell
griefprevention.claim.command.set-greeting
griefprevention.claim.command.buy-blocks     /griefprevention:buyclaimblocks
griefprevention.claim.command.sell-blocks     /griefprevention:sellclaimblocks
griefprevention.claim.command.trust   /trust
griefprevention.claim.command.untrust
