### ISSUE TITLE
The Agricultural Revolution food seeds

### ISSUE THREAD

**Issue by Raezar** [RTRGitHub/RTRRedux#528]
when you plant them, it doesn't take the seeds from your inventory

**Comment by Solidflip** [comment]
it took my diamond sprout.... which seed do you mean? Might be a lag thing too

**Comment by Raezar** [comment]
are you doing agricultural expansion? Cause there aren't any diamond seeds in The Agricultural Revolution.

**Comment by Solidflip** [comment]
issue should be resolved in the next update. Since its food though....eh
