### ISSUE TITLE
Items in Inventory are stuck and duplicate

### ISSUE THREAD

**Issue by Lunarjman89** [RTRGitHub/RTRRedux#529]
After about an hour of play, items in my inventory and hot bar became "stuck" to where they were. However when I clicked on the chest icon to empty into a nearby chest and after clicking an item on my hot bar the items reappear in my inventory and remained, duplicated, in the chest.

**Comment by MonoToast** [comment]
same here

**Comment by Solidflip** [comment]
Please test again. I believe i have fixed this. If not let me know.
