### ISSUE TITLE
PSI - Skill Screen Bug

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#530]
I can't access the skill tree from PSI due to a bug.
If u created ur first PSI Dust and press C you are still in the Starting Screen and can't level up.

I looked into the GitHub of PSI and there is a bug related to the version we are using.
Should be fixed in the next version of the modpack.

For now "/psi-learn tutorial1 EndEnemy" would help me a lot :D

u could also place a Command_Block with "/psi-learn tutorial1 @p" to help people out for now

**Comment by Solidflip** [comment]
i ran the command but it bugs out with sponge. Until the modpack updates there isnt anything i can do. Im sorry

**Comment by Solidflip** [comment]
so apparently you need to re-log. Command block added to spawn
