### ISSUE TITLE
[Actually Additions] All-In-One-Tool (AIOT) allows ore harvesting regardless of tool level

### ISSUE THREAD

**Issue by altoidsyn** [RTRGitHub/RTRRedux#532]
I made a stone AIOT and it was able to harvest modded ores from IE and Mekanism regardless of the required level (Lead requires diamond level, but was harvested). I tested on Redstone Ore and it mined at standard pick speed, but did not drop an item.

**Comment by dragonaslin** [comment]
are you sure because the highest this pack goes is cobalt... even manyllin says cobalt

**Comment by Solidflip** [comment]
this is fine for me. I use the atomic disassembler for this very reason. i HATE the level system. If this was hard mode or whatever i would fix. For now consider it a feature.
