### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#534]
im using the avant 3 pack and the error is java.net.connectexception: connection timed out: no further information

**Comment by dragonaslin** [comment]
make sure you are giving it enough ram. its in the options and then general

**Comment by Solidflip** [comment]
Gonna need a log on this one. Enable the console through whatever launcher you use then send the console log in a pastebin

**Comment by Direcub10** [comment]
http://pastebin.com/2TGhNRqu

**Comment by Solidflip** [comment]
could you do the whole crash log? you know the drill =P

**Comment by Direcub10** [comment]
.....its not crashing though

**Comment by Solidflip** [comment]
the console log then

**Comment by Direcub10** [comment]
http://pastebin.com/9JKY3FGg

**Comment by frogger35** [comment]
it says you are connecting to 142.4.200.221:25 do you have the server address saved as 142.4.200.221:25565?

**Comment by Camtoe112** [comment]
No need for the port, that's the default mine craft port. It will automatically input that, unless you put it as otherwise. Try removing the 25565 all together.

**Comment by frogger35** [comment]
can confirm our theories. Tried to connect to 142.4.200.221.25 and got [Client thread/INFO]: Connecting to 142.4.200.221, 25. This is the same thing in dire's error log. Which means, Dire you are connecting to the right IP with the wrong port. Your two options are to either delete the port so you are only connecting to 142.4.200.221 or change the port so you are connecting to 142.4.200.221:25565. Either one will work.

**Comment by Direcub10** [comment]
i have no idea where to begin with doing that

**Comment by Solidflip** [comment]
1.go to MultiPlayer
2. Click Add server
3. Re-type the address 142.4.200.221
4. log in
