### ISSUE TITLE
Atomic Reconstructor does not convert items

### ISSUE THREAD

**Issue by dierks-m** [RTRGitHub/RTRRedux#537]
I was trying to convert Nether Quartz into Prismarine Shards with the Atomic Reconstructor - blocks work fine, though items do not. Does not matter if in claim or not

**Comment by dragonaslin** [comment]
ya i saw that last night and havent found a fix yet

**Comment by dragonaslin** [comment]
they changed the way you do it i guess. its in the book

**Comment by dragonaslin** [comment]
ok, i guess he item your changing has to be siting in front of a block when the lazer hits it
