### ISSUE TITLE
Inventory Deleted after logging out

### ISSUE THREAD

**Issue by Lunarjman89** [RTRGitHub/RTRRedux#539]
After logging out for about four hours and logging back in my inventory was cleared of every item including armor but nothing in the baubles inventory. I had been experiencing lag and issues with persisting sound from removed mekanism machines and had moved a y level of 41.

**Comment by Solidflip** [comment]
did you switch dimensions or something? Or did you get an error message?

**Comment by Solidflip** [comment]
https://github.com/RTRGitHub/RTRRedux/issues/540

think i may have a fix... let me know if it happens again

**Comment by Solidflip** [comment]
3 days without incident.... ima go ahead and say my fix worked
