### ISSUE TITLE
GraviChestPlate

### ISSUE THREAD

**Issue by CalenMC** [RTRGitHub/RTRRedux#54]
So I was walking around, fought a legendary mob (cave spider with 216 hp). Walked around for another minute.

An in that 5 minute window, somehow my gravichestplate disappeared. But Sticky and Disarm were supposedly disabled. That spider didn't have either of those (had ender, blastoff, something).

So. Who stole my GraviChestPlate?

**Comment by kenny608uk** [comment]
Did you put an enchant on it ?

**Comment by CalenMC** [comment]
Yes, a whole bunch of them.
Protection 4, Soulbound 1, Magic Resistance 5.
Perhaps more, not sure.

**Comment by CalenMC** [comment]
The rest of my quantum armor is enchanted too and isn't missing.

**Comment by kenny608uk** [comment]
Known problem with gravisuite, occurred in 1.5 too

**Comment by CalenMC** [comment]
Cool. Know any hack for minecraft that gives you flight? Cause that's the second time my way of flying refuses to work properly.

**Comment by CalenMC** [comment]
Actually, ignore that last comment. Slightly irritated now.

Not sure how I'll work around it this time.
