### ISSUE TITLE
Ranks 

### ISSUE THREAD

**Issue by Raezar** [RTRGitHub/RTRRedux#542]
Ranks keep resetting here is an exam
http://prntscr.com/cx01h9ple
http://prntscr.com/cx01wt

**Comment by Souperhero** [comment]
I need a list of players that this is happening to. Assuming it's happening to select players, and not everyone. After that, I will record their times and reset their info in the file.

or a better description of the problem.

**Comment by frogger35** [comment]
So the rank system in this server changes the rank of people to the incorrect rank. A person will be total time on server be like 72 hours. The ranking system then goes OH so and so has been on for 5 minutes so he/she/it/attack helicopter/ is like rank 5 minutes. Not the OH so and so has been of for 72 hours so he/she/it/attack helicopter/ is like rank 72 hours.

Also it's select like EndEnemy doesn't get his reset but I a poor little inoccent attack helipcopter frog based lizard woman thing get serf. plebian. plebarian. and all the other ranks under what i should actually be.

I hope you understand what I Have written.

Thanks

p.s 

p.p.s

p.p.p.s Hi :dagger:

**Comment by dierks-m** [comment]
I can confirm this - it also is happening to me (ChrisP_Chicken). Funnily not as often as it apparently does to other players, yet it does still happen occasionally.

**Comment by dierks-m** [comment]
Additionally - I don't know if I am the only one who this is happening to, but the room for the ranks at spawn is horribly messed up for me:

http://i.imgur.com/KmEnmDo.png

**Comment by frogger35** [comment]
ranks at spawn aren't messed up for me. If you click on one it shows you the imgur link it is associated to. When you do that can you go to that imgur link in your browser?. If you can't that explains the error. If you can then idk.

**Comment by frogger35** [comment]
Ranks are broken again. They are spamming how long a player has been on and it's incorrect. Players also have the wrong title. Like endenemy has servant and he is suppose to have artisan or higher

**Comment by Camtoe112** [comment]
It was reported to plugin author. I'll disable ranks for now to relieve you of spam.

**Comment by Souperhero** [comment]
Closing for now. Plugin author has not responded in over a week.
