### ISSUE TITLE
Bagginses - solved(?)

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#544]
Tried crafting the bag from this mod using 4 string  4 wool and a chest.hard crash to desktop whenever the crafting recipe is generated in the table. Happened in Tinkers table and normal crafting table will post my crashlog when I get back to mycomputadora

**Comment by frogger35** [comment]
a mod told me this is a WIP thing so that's why it's crashing me.

**Comment by Solidflip** [comment]
log would still be nice

**Comment by frogger35** [comment]
here you dun diddly go 
http://pastebin.com/q9sh5ZdQ

**Comment by Solidflip** [comment]
looks like mintweakers tooltip thing......weird. Has it happened since then?
