### ISSUE TITLE
rightclicking on a module when holding a placeable block, the block is placed and the module opens

### ISSUE THREAD

**Issue by Xalorous** [RTRGitHub/RTRRedux#549]
posted for tracking

**Comment by Solidflip** [comment]
Do what?

I have no idea what you are talking about Xal. What mod? what blocks? what module?

**Comment by Solidflip** [comment]
guess its not an issue?

**Comment by Xalorous** [comment]
Actually this one still happens.  Not sure if it's 1.10.2 issue, or Avant 3
issue.
