### ISSUE TITLE
occasionally, clicking along lower edge of screen (JEI input box), switches to the desktop

### ISSUE THREAD

**Issue by Xalorous** [RTRGitHub/RTRRedux#550]
Windows 10
Current Java
Current curse/modpack

**Comment by Solidflip** [comment]
so this happens when you click IN the JEI box? or below it on the edge of the window?

**Comment by Solidflip** [comment]
guess this is a non-issue now?

**Comment by Xalorous** [comment]
This is resolved by restarting Windows.  It's a Windows 10 glitch, where
the Windows toolbar responds through the full screen app (usually games).

**Comment by Solidflip** [comment]
ahh well sorry i couldnt help =P

**Comment by Xalorous** [comment]
I didn't think it belonged on our git, but folks insisted.

**Comment by Camtoe112** [comment]
It's here if someone experiences the same issue. It's an archive.
