### ISSUE TITLE
Some Chisel Blocks Don't Change to the right blocks.

### ISSUE THREAD

**Issue by Queenofchaos** [RTRGitHub/RTRRedux#553]
Diorite and Andesite can not be changed into their block types e.g Diorite Disordered Tiles or Andesite Braid. The only thing you can get from the Diorite and Andesite are the stone blocks.

![2016-10-25_15 59 38](https://cloud.githubusercontent.com/assets/22422189/19704183/6799f672-9acc-11e6-9daa-d304b6eca72e.png)

![2016-10-25_15 59 47](https://cloud.githubusercontent.com/assets/22422189/19704182/679771d6-9acc-11e6-8c3b-0f0c286658f2.png)

![2016-10-25_16 04 09](https://cloud.githubusercontent.com/assets/22422189/19704312/dbdd7bbc-9acc-11e6-981e-9e00ad94a5dc.png)

**Comment by Solidflip** [comment]
this is probably an ore-dict issue. Ill see if the mod has a fix

**Comment by Solidflip** [comment]
Youll need to use the iChisel.

http://image.prntscr.com/image/d6f58f62ef1045a18d464119189f122d.png

that will work
