### ISSUE TITLE
PvP Plugin voiding items

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#554]
If u drop an item after sombody hit you it is getting voided.
Chat: "You can't drop items while in a PvP-Fight"

Anyways, is it possible to change this? 
I lost my Boomerang to this when showing it to a friend.

Or if you accidently hit Q in a fight your OP-sword gets destroyed. I don't think this is intended. 

<3 End

**Comment by Souperhero** [comment]
Plugin was removed.
