### ISSUE TITLE
Daitye crashes everytime he tries to join the server

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#555]
Player "daitye" can't connect with the server without crashing.
He picked up a spawner in a Roguelike Dungeon with a "Wooden Chest Transporter" and crashed.
He can still connect with a account of a friend.
Possibly a corrupted player data.

**Comment by Solidflip** [comment]
cant find a uuid for that name. I need his exact name buddy

**Comment by Solidflip** [comment]
Come see me in ts if this is still an issue.
