### ISSUE TITLE
Yellorite Ore

### ISSUE THREAD

**Issue by codemeister101** [RTRGitHub/RTRRedux#556]
I was wondering if the yellorite ore was supposed to spawn in the over world only or if it the mod it self isn't allowing it to spawn in the other dimensions. I can't find any Yellorite ore in the mining world or the deep dark I even used the digital miner to see if I can find anything. It isn't picking any up. So far the only place it spawning is in the overworld.

Thanks!

Cody,

**Comment by Camtoe112** [comment]
Potential world around could be the dimensional miner or the mining laser setup.

**Comment by Solidflip** [comment]
cant replace ore in the overworld at this time, use the mining laser for now
