### ISSUE TITLE
Lightning Bugs

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#557]
Lights arent updating correctly for different players.

Issue 1: -> Clientside Issue?
Most modded lights are dark after you load the chunk. 
They need an Block Update to work.
Vanilla Lights seems to be okay.

Issue 2: -> Serverside Issue?
Its really hard to get an area dark for a mobfarm.
It shows that it still can see the sun even if it can't. All sides and roof of the room are covered wit vanilla Cobblestone.
Workaround:
- place blocks in the lighted area
- reload the chunk (!)
- destroy the blocks you just placed
- repeat it like two or three times
- your mobfarm is now spawning much faster

**Comment by Solidflip** [comment]
this is an issue with sponge for now, ill look into getting it resolved but may require an update. For now id use the workaround
