### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by EndEnemy** [RTRGitHub/RTRRedux#558]
After playing a long time on the server i just want to share how i am experiencing the lag.

When I play alone with ChrisP_Chicken aka. Wieselkotze we normally get a really smooth server, even until the next restart.
We both have no automatic mining, just two mobfarms that may create some small lag.
Tonight it was a bit different, 2 h after restart we get really strong lag all 10 seconds.

If players with bigger bases join the server its getting really fast really bad.

**Comment by Solidflip** [comment]
We are on it
