### ISSUE TITLE
deep dark

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#559]
Created a deep dark portal every time I use it. It teleports me to the deep dark then teleports me back to the overworld

**Comment by frogger35** [comment]
Seems to be client side. I am lagging to much when teleporting to the deep dark. Seems I sit on the portal to long. Any way to change the timers on the portal or setup a warp?

**Comment by Solidflip** [comment]
uh. try it tonight, if it doesnt work i can set a warp

**Comment by frogger35** [comment]
it works now 
<3

**Comment by Solidflip** [comment]
perfect =)
