### ISSUE TITLE
people can fly

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#560]
Something messed up with permissions. People have the ability to fly on joinning the server. Ray reset my player to survival and that fixed the issue

**Comment by Solidflip** [comment]
is this anyone but you currently?

**Comment by frogger35** [comment]
currently I don't know who can. I just know people had reported it. It was changed for me on day one. I would talk to ray

**Comment by Camtoe112** [comment]
She's been changing people's gamemode to survival on their first login.

**Comment by dragonaslin** [comment]
its a bug and will have to be dealt with as people get on like stated
