### ISSUE TITLE
FTB Utilities 

### ISSUE THREAD

**Issue by codemeister101** [RTRGitHub/RTRRedux#562]
I just wanted to report the FTB Utilities is not working properly. I can claim land with no problem, but the add friend list (TeamGUI) is not showing names to add.    The two mods I add by Soild say so was FTBUtilities-1.10.2-3.1.1
FTBLib-1.10.2-3.1.1
Also the player I am trying to add has it installed as well.

![2016-10-30_12 28 11](https://cloud.githubusercontent.com/assets/23063822/19838395/601084d8-9e9c-11e6-854c-5a0ad13b3183.png)

![2016-10-30_12 27 45](https://cloud.githubusercontent.com/assets/23063822/19838394/601030f0-9e9c-11e6-85ca-4979138853ae.png)

![2016-10-30_12 27 49](https://cloud.githubusercontent.com/assets/23063822/19838396/6014ffae-9e9c-11e6-9eeb-be79ce01b7ee.png)

**Comment by Souperhero** [comment]
I literally have no idea. Not to sound unhelpful, but because it's not an original mod from the original pack, the Modpack authors won't offer support. This is one of many unfortunate issues that arise when including outside mods into a mod pack.

**Comment by dragonaslin** [comment]
you are supposed o use grief prevention

**Comment by Solidflip** [comment]
Use "/ftb team create <name>" to create a team. Then use "/ftb team invite <user>" to invite people into it.

any questions seek me out in ts
