### ISSUE TITLE
glass shards crash

### ISSUE THREAD

**Issue by Xalorous** [RTRGitHub/RTRRedux#563]
Recipe says 4x glass shards in 2x2 makes something (name doesn't show in JEI) that can be smelted and made to glass.  I shift clicked in 14 recipes worth.  THen when I tried to craft them, before I could clikc I crashed.  Then I logged back on and opened the crafting table and it crashed again.

Gist of crash report.  <script src="https://gist.github.com/Xalorous/20d147d32980d5ba63b90f190426a540.js"></script>

I did use the launcher 'create a report' option the second time.

**Comment by Solidflip** [comment]
http://pastebin.com/P0PtC9ZF in a regular crafting table

http://pastebin.com/9dZZsT8g in the cloud crafting table from the mod

**Comment by Solidflip** [comment]
issue reported to mod author. Until then dont craft the glass, just use regular glass methods.
