### ISSUE TITLE
mekanism pressurized tube not connecting electrolytic separator to basic purification factory

### ISSUE THREAD

**Issue by Xalorous** [RTRGitHub/RTRRedux#564]
putting them side by side works, but then you can only use one separator, and speeding up factory eventually requires more than one separator.

**Comment by Solidflip** [comment]
Workaround: Export the gas to a gas tank, then move that to the chamber.
http://image.prntscr.com/image/ac464a73b99d48a1b1ee4315f6b16ff5.png
