### ISSUE TITLE
Unknown crashing (possible partical issue)

### ISSUE THREAD

**Issue by Lunarjman89** [RTRGitHub/RTRRedux#568]
After playing for a few hours I experienced a crash which led to about three consecutive crashes until an admin warped me away from my base. Here are the pastebin crash reports

http://pastebin.com/X9ND0CDM

http://pastebin.com/YqA7FiMh

**Comment by dragonaslin** [comment]
whats all in the area that its happening in?

**Comment by Lunarjman89** [comment]
There is one of the large dungeons, a nether and aroma portal, mekanism machines connected with elite power cables, two windmills, one is mekanism the other is immersive engineering. Both windmills are connected via wires from IE to an IE LV capacitor, which is connected to a mekanism capacitor via ender IO cables. I also have IE crates, storage drawers, an IE coke oven, some drums with fluids, a factory door, and two IE tanks, one with hydrogen the other with oxygen, and a Tinkers' smeltery.

**Comment by dragonaslin** [comment]
next time your on i will come over and have a look
