### ISSUE TITLE
Hydroangeas Issue

### ISSUE THREAD

**Issue by Lunarjman89** [RTRGitHub/RTRRedux#570]
When I place hydroangeas down and there is an extra utilities chunk loader nearby it causes an issue where mana spreaders will act as if there are hydroangeas still producing mana dispite them being decayed. It can also cause an issue where there are dead bushes constantly breaking and replacing themselves, even destroying blocks placed on that block, including bedrock and even a chunk reset. Once the server restarted the issues had fixed themselves, but appears to be repeatable, by accident.

**Comment by dragonaslin** [comment]
i will be on tommorow and will look into it sry for the wait
