### ISSUE TITLE
Enderio

### ISSUE THREAD

**Issue by SniperPro55** [RTRGitHub/RTRRedux#573]
Drops from mob farm were originally being deleted but now from the video i'm not sure what to make of whats going on with enderio item transfer besides maybe phantom blocks but not sure how to deal with that.
https://youtu.be/TIU3Z0yKlbE

**Comment by dragonaslin** [comment]
that is definitly weird. do you have a vacuum chest near by? ender io is very buggy this pack and will look into it for you. sry for late responce.

**Comment by SniperPro55** [comment]
There was a vacuum chest in the exact spot that the items were going but the items were still being deleted if there was no item conduits to take out the items. Still wierd that shown in a later part of the video that items seemed to transfer if there was conduits running from the vacuum chest halfway to another chest but where the conduit was not run all the way or set redstone-wise where it wasn't supposed to work. I'm not sure if the server thinks that the previously placed blocks are still there or what, but there have been other occurrences of conduits disappearing but leaving invisible outlines of blocks in the same space that have to be broken(no drops) before another conduit can be placed back. If this specific event isn't fixable I guess I can just try to then quarantine the specific area and move the setup but in a way I'm kind of glad to be reassured that the enderio stuff isn't just us

**Comment by dragonaslin** [comment]
updated pack. is it better

**Comment by SniperPro55** [comment]
Yes everything is working much better thank you :)
