### ISSUE TITLE
Drum of the gathering Crashes server

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#575]
Whenever mana hits the drum to activate it the server closes. I can confirm because i was the only one on the server at the time and it closed exactly as the drum would have sheared my sheep. Cant find anything else on the internet referencing this

**Comment by xXlucidXx** [comment]
This also when ever someone loads the area that the drum is in, it will crash the server.

**Comment by dragonaslin** [comment]
drum has been banned till mod author fixes
