### ISSUE TITLE
Sparks wont connect to eachother

### ISSUE THREAD

**Issue by Direcub10** [RTRGitHub/RTRRedux#576]
(If you dont know what im talk about ask dragonaslin) when ever i place down a  spark on a mana pool it will only connect to about 3 sparks seemingly at random. they are supposed to connect to all of them to allow mana transfer. without them work correctly its near impossible to store large amounts of mana or make terrasteel. Might be due to the lag. Will check again after flip gets on and tries to fix it.

**Comment by dragonaslin** [comment]
still looking
