### ISSUE TITLE
Trouble with server

### ISSUE THREAD

**Issue by Tobiah10** [RTRGitHub/RTRRedux#577]
hello again. we are having trouble logging on to the server again. the player Antartik can no longer log on without crashing the server. im sorry to bother you again.

**Comment by Camtoe112** [comment]
Send us your client side crash log in pastebin.com please

**Comment by Camtoe112** [comment]
If possible, have your friends send theirs too.

**Comment by Tobiah10** [comment]
where would i find that?

**Comment by Camtoe112** [comment]
Whereever your mine craft is, crash-log folder. Most recent crash or whichever applies.

**Comment by Tobiah10** [comment]
okay thank you ill look for it

**Comment by Tobiah10** [comment]
i cant seem to find the crash log im looking through the folders now

**Comment by Tobiah10** [comment]
all i have is a log folder full of text documents

**Comment by Ryuujinsama** [comment]
C:\ftb\FTBInfinityLite110\minecraft\crash-reports

should be the directory you need to navigate to

**Comment by Raezar** [comment]
after getting your crash report for the ftb infinity file, go to paste bin, copy in crash report and select new issue. then put copy of the link in here please.

**Comment by Souperhero** [comment]
http://pastebin.com/H6iPHvgj

Someone go ahead and world edit this out.

Block type: ID #506 (tile.BloodMagic.demonPylon // WayofTime.bloodmagic.block.BlockDemonPylon)

//pos1 572,69,2580
//pos2 579,65,2586

//replace 506 stone

**Comment by Souperhero** [comment]
Antarctiks player data has been reset. Please let me know when its successfully cleared out

**Comment by Raezar** [comment]
fixed
