### ISSUE TITLE
Ghost Vacuum Chest

### ISSUE THREAD

**Issue by MitchellMarx** [RTRGitHub/RTRRedux#578]
I removed a vacuum chest from a room in my base (-580,547,61) (x,z,y) but when i broke the block it disappeared.  It seems to have vacuumed into itself and created some sort of item black hole.  I have dropped many stacks of cobblestone and believe that ghost chest is now full of cobblestone, but it will still steal items that it has stolen but not filled a full stack, things like vector plates, diamond spikes,   I have tried filling and mining the area manually and with the rftools quarry but the problem persists.  I would greatly appreciate any help.

**Comment by dragonaslin** [comment]
fixed it self but let me know if it happens again.
