### ISSUE TITLE
Minecraft Server: World Border

### ISSUE THREAD

**Issue by ManeEvent** [RTRGitHub/RTRRedux#579]
The overworld border is at -4600. I was unaware of that, I only knew there was a border somewhere. After a couple days of playing I was told to move away from the spawn area and I proceeded to hop into the Nether and fly as far as I can to set up a new base somewhere untouched. Since I didn't hit a border anywhere in the Nether I assumed there would not be a problem. I made another Nether portal hopped in it and instantly died. I was timed out right after and everyone was complaining about lag so I assumed it was that sort of issue and tried to get back to my stuff, I had all my best equipment on me, and was died again. Through a long process of asking other people on the server to help me retrieve my stuff, another person "MeanRaids" lost his stuff and we figured out the Nether teleports you past the Overworld border so every time we walked into a portal past a certain point we died and lost our stuff. I don't know what to do about the border, but if you could help me get my stuff back that would be great. As I said, I had my best stuff on me. 
- XManeEventX

**Comment by dragonaslin** [comment]
fixed

**Comment by ManeEvent** [comment]
How?

**Comment by dragonaslin** [comment]
I changed the world boarder in the nether so that it won't spawn you outside world boarder in overworld

**Comment by dragonaslin** [comment]
If there is another person that needs his stuff then I will be on tonight and have him be on too plz
