### ISSUE TITLE
Minecraft Server: World Border 2.0

### ISSUE THREAD

**Issue by ManeEvent** [RTRGitHub/RTRRedux#580]
My issue was closed and an admin commented "fixed", but nothing has happened. I left a comment after and there has been no response

**Comment by dragonaslin** [comment]
I didn't see the comment and set the world boarder so it wouldn't happen agan and your stuff was reinburced so I wrote fixed

**Comment by ManeEvent** [comment]
Reimbursed where?

**Comment by dragonaslin** [comment]
Weren't you in ts last night and asked for your stuff

**Comment by dragonaslin** [comment]
I thought it was you sry I will be on tonight to reinburced you

**Comment by ManeEvent** [comment]
Okay. That was MeanRaids or Colors on TS, he was the person who helped me. Thank you

**Comment by Raezar** [comment]
replaced mane's items.  warned about world border issue. issue closed
