### ISSUE TITLE
Mod rejections Cannot connect

### ISSUE THREAD

**Issue by adrlmrtz** [RTRGitHub/RTRRedux#582]
Did the server update to a new version? I tried connecting but get this result:
Mod rejections [FMLMod:compactsolars{1.10.2-5.0.8.331},
FMLMod:gravestone{1.5.10}

etc. There is a long list but you get the idea. 
Is there a server website or post somewhere with the most up to date version or where you announce an update before it is done so we can keep up to date? 

Thank you!!! :)

**Comment by dragonaslin** [comment]
ya been happening to a lot of people, need to reinstall the pack completely its looks like something goes wrong when you try to just update.

**Comment by adrlmrtz** [comment]
Ah I will try that, thank you!
Edit: That worked, thanks!

**Comment by dragonaslin** [comment]
were you able to log in?

**Comment by adrlmrtz** [comment]
Yes, thank you!:) I love this server!

On Jan 15, 2017 9:12 AM, "dragonaslin" <notifications@github.com> wrote:

were you able to log in?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RTRGitHub/RTRRedux/issues/582#issuecomment-272701245>,
or mute the thread

**Comment by Solidflip** [comment]
issue is resolved
