### ISSUE TITLE
Can't create home. 

### ISSUE THREAD

**Issue by Dasms** [RTRGitHub/RTRRedux#584]
"/home" isn't working /sethome yields a home but /homes shows no homes and I'm unable to teleport to the set location.

**Comment by Solidflip** [comment]
When you ran /sethome did the game say anything about an old existing home? Usually you have to delete your old home before setting a new one called "home"

run /deleteHome home
then /sethome

see if that helps

also you can use /homeset

**Comment by AccordNoir** [comment]
Somehow the command got changed. /homeset is actually the /sethome command
