### ISSUE TITLE
Quantum Quarry not mining

### ISSUE THREAD

**Issue by Chris0395** [RTRGitHub/RTRRedux#585]
There is an issue with the quantum quarries where they will try and mine out chunks that other quarries have already mined. The block mined count keeps going up but nothing is outputted. The seems to be resetting the dimension they work in (Dim: -999 I think).

**Comment by dragonaslin** [comment]
do you have the right filters on it because it pulls from a imaginary realm so it shouldnt just not work?

**Comment by Chris0395** [comment]
I don't have any filters on it.

**Comment by dragonaslin** [comment]
That is why. If your online ask ryu or another mod to show you
