### ISSUE TITLE
Mekanism Cables

### ISSUE THREAD

**Issue by Orbitus2001** [RTRGitHub/RTRRedux#587]
I tried to use Mekanism cables for power transfer and it wouldn't transfer power out of the coal generator for Actually Additions.  I put a power cube on it from calculator and used the cables out of that, wouldn't work.  I then made a basic energy cube from Mekanism and it wouldn't send energy from that either.  Made a configurator and put the cables on pull mode, wouldn't send energy that way either.  So either the cables don't work or something is up with them.  Ended up using basic conduits from Ender IO.

**Comment by AccordNoir** [comment]
This is a known bug in mekanism right now. Currently just have to wait in the mod developer to update and possibly fix it.
