### ISSUE TITLE
Flux Networks

### ISSUE THREAD

**Issue by Orbitus2001** [RTRGitHub/RTRRedux#589]
Last night, I went to make some of the Flux Networks wireless stuff.  But the recipe for the black flux dust that is the basic requirement for the pack isn't craftable.  The mod wiki says the way to craft it is by smelting redstone dust in some sort of furnace, but it doesn't work.  Is the mod disabled for a reason or just not working properly?

**Comment by AccordNoir** [comment]
It's not disabled, that we know of. We will have to look at it next time one of us is online.

**Comment by AccordNoir** [comment]
It has been confirmed that you csn throw Redstone into  fire and it will turn into Flux. Also if you throw it on the ground and ignite it with flint and steel it will work.
