### ISSUE TITLE
SpawnerCraft not dropping mob essense.

### ISSUE THREAD

**Issue by adrlmrtz** [RTRGitHub/RTRRedux#590]
Hey after hitting a lot of different mobs with the mob fishing rod and nothing dropping I looked this up. https://github.com/CAD97/SpawnerCraft/issues/5

Apparently it's been an issue before, do you know if this is the case on the server?

EDIT: Also the CRASH OF THE TIMBERMAN Blood magic ritual crashes the server. :(
Also how do I donate?

**Comment by dragonaslin** [comment]
i will look into the issue but from what i see, the bug has not been fixed yet. and i know about the blood magic ritual but there is no config dissable for that one. to donate you can donate on the rtr web site or the green money symbol on the top right of our teamspeak

**Comment by adrlmrtz** [comment]
Thanks Dragonaslin!
