### ISSUE TITLE
Solderer

### ISSUE THREAD

**Issue by frogger35** [RTRGitHub/RTRRedux#591]
The solderer is a blacklisted item for some reason. How are we to craft refined storage? Can we get a list of banned/blacklisted items somewhere? Kinda sucks to make something then the server is like "Oops didn't tell you but shit's banned yo! I'ma take that! Thanks!" (Frog's point of view of cruddy items being taken away by server)

This was the error [04:00:57] [Client thread/INFO]: [CHAT] Solderer is blacklisted. You may not hold this item.

**Comment by AccordNoir** [comment]
Refined storage caused a lot of crashes with buggy items. And with ae2 it's  not really needed. Also there is a ban list at spawn

**Comment by frogger35** [comment]
Wow I must have passed this list over. Thank for letting me know! Completely did not see this thing xD. Even though it's where I got this link from.
