### ISSUE TITLE
Server updated!

### ISSUE THREAD

**Issue by adrlmrtz** [RTRGitHub/RTRRedux#593]
Hey guys, thanks for updating the server to a new pack! Just one question, is there a world save of bevo's pack available for download? I was away for a week due to work and came back to a new modpack. I would like to continue building where I left off, but does this new pack mean starting from scratch? 

Thanks anyway! 
Shadowengineer

**Comment by dragonaslin** [comment]
i believe we have it somewhere and will zip it up for you when i get a chance
