### ISSUE TITLE
PSI Cad Assembler

### ISSUE THREAD

**Issue by SniperPro55** [RTRGitHub/RTRRedux#595]
the recipe for the @psi cad assembler used to be http://i.imgur.com/cNYXK3r.png in 1.1.0 of the beyond modpack while it was reverted to the normal recipe http://prntscr.com/eqzslm in the 1.2.1 version and cannot be pulled out of the crafting table

**Comment by SniperPro55** [comment]
the spell programmer has the same issue with not being able to be pulled out of the crafting table

**Comment by SniperPro55** [comment]
the recipes work fine in singleplayer though

**Comment by dragonaslin** [comment]
minetweaker changed them
