### ISSUE TITLE
Veinminer

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#6]
When the veinminer configs were changed, specific blocks can only be broken with their respected tools, it made veinminer unable to be used with non-vanilla tools. So far. TiC and Metallurgy tools will not work with Veinminer since the config change.

**Comment by kenny608uk** [comment]
That's something that will take time to fix since we need to write down every ID it's expected to recognise as a pickaxe and add it to the config manually

**Comment by UnsungCesspool** [comment]
The big difficult one will be adding all the metallurgy tools one at a time. The good thing with TiC, is they all fall under the same ID for that type.

**Comment by Abouttabs** [comment]
will do writeup of IDs today..

**Comment by Abouttabs** [comment]
Thanks to Cess that is all done :-D

**Comment by UnsungCesspool** [comment]
With the modpack update, we lost all the veinminer config changes we had.
