### ISSUE TITLE
AE2 Terminal

### ISSUE THREAD

**Issue by Rah9742** [RTRGitHub/RTRRedux#604]
All my ae2 machine and drives have been removed from my claimed base and I am not sure why.

**Comment by dragonaslin** [comment]
will look into it

**Comment by dragonaslin** [comment]
what are our cords?

**Comment by dragonaslin** [comment]
who are you based with and friends with

**Comment by Rah9742** [comment]
Yeh me and ThePvPExorcist. In the aether at
x: 1526
y: 34
z: 1764

**Comment by dragonaslin** [comment]
Unfortunately there is no back up for that so we will have to get with you and try to refund. Just so you know the aether is subject to wipes. Just so your aware. Base there at own risk

**Comment by Rah9742** [comment]
Oh okay, when would be a good time to get the stuff back?

**Comment by dragonaslin** [comment]
Anytime a mod or admin is on we will try to get you the big things back but won't be able to give everything back. One of us is on every night

**Comment by Ryuujinsama** [comment]
Taken care of him, refunded the items.
