### ISSUE TITLE
Gravestone didn't spawn in the end due to chunk claiming

### ISSUE THREAD

**Issue by altoidsyn** [RTRGitHub/RTRRedux#611]
So, I died in the end because the second I spawned, I was looking at a stupid Enderman. When I died, the 'You can't do that here' message popped up, and no grave appeared. Would a moderator or administrator be willing to recover my stuff for me? 

The death was at 3:43:53AM PST 8/24/17 at 102, 49, 5. If not, just let me know. I don't think I had anything super important, but it's such a pain to re-obtain items in Skyfactory early on. 

Thank you!

**Comment by altoidsyn** [comment]
Make that two. I'm not sure what protection is applied to the End, but it's a little annoying. :P

4:20:39AM PST 08/24/17 at 19, 49, 3

Thank you!

**Comment by Ryuujinsama** [comment]
if the grave didnt spawn unfortunately there isnt a way to give back the stuff from the grave but if you know what the stuff was you lost lemme know on TS and i can get it back to you.
