### ISSUE TITLE
Chickens...

### ISSUE THREAD

**Issue by Xalorous** [RTRGitHub/RTRRedux#612]
Two chickens are normally found in the Nether.  Since it's void, can we please get recipes added to make:

Soul Sand
Nether Quartz

Not having those chickens breaks the breeding trees.

**Comment by Ryuujinsama** [comment]
when you get on lemme know and i'll hop on and make a kit for the chickens cant add recipes easily

**Comment by Ryuujinsama** [comment]
Taken Care of
