### ISSUE TITLE
Connection Lost - Mod Rejections

### ISSUE THREAD

**Issue by vlstratt** [RTRGitHub/RTRRedux#613]
I was originally playing on FTB Sky Factory 3 3.0.14 even after 3.0.15 came out because 3.0.15 had mod rejections. However, when logging on today, I found that 3.0.14 and 3.0.15 both come up with Connection Lost - and then a long list of mod rejections. It works with other servers, just not minecraft.righttorebel.net. Is this an issue with the server or with my download?

**Comment by AccordNoir** [comment]
The pack got changed to the simple life 2. Version 1.3.5 I will make sure we update the forums and everything today

**Comment by Ryuujinsama** [comment]
if you have anymore issues post another ticket here or join us at ts.righttorebel.net have a great day!
