### ISSUE TITLE
Currently Uncraftable

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#62]
In NEI, if you click on both the watering can and the magnum torch, it only gives you info on the item, and not its recipie. If you try to craft said item in a crafting table by using the old recipies it doesn't work.

Only tested with watering can, as im not "rich" enough to test the magnum torch.

**Comment by Abouttabs** [comment]
It does work it just doesn't show up, it is a simple matter of miroring configs to the client
