### ISSUE TITLE
IDs to add to Veinminer -WIP-

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#63]
Underground Biome BLOCK IDs:

535,535:1,535:2,535:3,535:4,535:5,535:6,535:7,536.536:1,536:2,536:3,536:4,536:5,536:6,536:7,537,537:1,537:2,537:3,537:4,537:5,537:6,537:7,538,538:1,538:2,538:3,538:4,538:5,538:6,538:7,539,539:1,539:2,539:3,539:4,539:5,539:6,539:7,540,540:1,540:2,540:3,540:4,540:5,540:6,540:7,541,541:1,541:2,541:3,541:4,541:5,541:6,541:7,542,542:1,542:2,542:3,542:4,542:5,542:6,542:7,543,543:1,543:2,543:3,543:4,543:5,543:6,543:7,544,544:1,544:2,544:3,544:4,544:5,544:6,544:7,546,546:1,546:2,546:3,546:4,546:5,546:6,546:7

**Comment by UnsungCesspool** [comment]
Chisel Block IDS up to, but not including Marble (First page)

79:1,79:2,79:3,79:4,79:5,79:6,79:7,79:8,79:9,79:10,79:11,79:12,79:13,79:14,79:15,2730:1,2730:2,2730:3,2730:4,2730:5,2730:6,2730:7,2730:8,2730:9,2730:10,2730:11,2730:12,2731:1,2731:2,2731:3,2731:4,2731:5,2731:6,2731:7,2731:8,2731:9,2731:10,2731:11,2732:1,2732:2,2732:3,2732:4,2732:5,2732:6,2732:7,2732:8,2732:9,2732:10,2732:11,2732:12,2732:13,2732:14,2733:1,2733:2,2733:3,2733:4,2733:5,2733:6,2733:7,2733:8,2733:9,2733:10,2733:11,2733:12,2733:13,2733:14,2733:15,2734:1,2734:2,2734:3,2734:4,2734:5,2734:6,2734:7,2734:8,2735,2735:1,2735:2,2735:3,2735:4,2735:5,2735:6,2735:7,2735:8,2735:9,2735:10,2735:11,2735:12,2735:13,2735:14,2735:15,2736,2736:1,2736:2,2736:3,2736:4,2736:5,2736:6,2736:7,2736:8,2736:9,2736:10,2736:11,2736:12,2736:13,2736:14,2736:15,2737,2737:1,2737:2,2737:3,2737:4,2737:5,2737:6,2737:7,2737:8,2737:9,2737:10,2737:11,2737:12,2737:13,2737:14,2737:15,2738,2738:8,2739,2739:8,2740,2740:8,2741,2741:8,2742,2742:8,2743,2743:8,2744,2744:8,2745,2745:8

**Comment by UnsungCesspool** [comment]
Chisel Block IDS, Page 1, From Marble up to and including Redstone:

2746,2746:1,2746:2,2746:3,2746:4,2746:5,2746:6,2746:7,2746:8,2746:9,2746:10,2746:11,2746:12,2746:13,2746:14,2746:15,2747,2747:1,2747:2,2747:3,2747:4,2747:5,2747:6,2747:7,2747:8,2747:9,2747:10,2747:11,2747:12,2747:13,2747:14,2747:15,2748,2748:1,2748:2,2748:3,2748:4,2748:5,2748:6,2748:7,2748:8,2748:9,2748:10,2748:11,2748:12,2748:13,2748:14,2748:15,2749,2749:1,2749:2,2749:3,2749:4,2749:5,2749:6,2749:7,2749:8,2749:9,2749:10,2749:11,2749:12,2749:13,2749:14,2749:15,2750,2750:1,2750:2,2750:3,2750:4,2750:5,2750:6,2750:7,2750:8,2750:9,2750:10,2750:11,2750:12,2750:13,2750:14,2750:15,2751,2751:1,2751:2,2751:3,2751:4,2751:5,2751:6,2751:7,2751:8,2751:9,2751:10,2751:11,2751:12,2751:13,2751:13,2751:14,2751:15,2752,2752:8,2753,2753:8,2754,2754:8,2755,2755:8,2756,2756:8,2757,2757:8,2758,2758:8,2759,2759:8,2760:1,2760:2,2760:3,2760:4,2760:5,2760:6,2760:7,2760:8,2760:9,2760:10,2760:11,2760:12,2760:13,2760:14,2760:15

**Comment by UnsungCesspool** [comment]
eyes hurt from numbers, will continue later.

**Comment by Abouttabs** [comment]
added, thanks a lot cess you rock

**Comment by Volaunis** [comment]
I'd like to add Abyssal stone (457:6) and Quarried stone (457:7)

**Comment by Abouttabs** [comment]
added

**Comment by UnsungCesspool** [comment]
BloodStained blocks 464:11,464:18,464:26,464:34,465:11,465:18,465:26,465:34,468,468:1,468:2,468:3,468:4,468:5,463:7
