### ISSUE TITLE
ManaCreeper/Server crash

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#7]
When mana creepers explode, they crash the server.

**Comment by kenny608uk** [comment]
Did this happen again? I thought it was just infernal ones... I'll downgrade Ars magica tonight then

**Comment by UnsungCesspool** [comment]
Yeah it happened again like several times unfortunately.

**Comment by Abouttabs** [comment]
DIsabled Mana creepers for the time being..

**Comment by Abouttabs** [comment]
okay it is not infernals...
Crashed without them...
