### ISSUE TITLE
rotarycraft sounds

### ISSUE THREAD

**Issue by levi758336** [RTRGitHub/RTRRedux#73]
Can I request a config file change? 

Reika/Rotarycraft.cfg

D:"Machine Volume Multiplier"=1.0

Can we get this reduced to like 0.25? These things are loud, anyone who wants to hear can come visit me.

**Comment by Abouttabs** [comment]
That is client side so you can do it for yourself, also it will be considered to be put as default...

**Comment by levi758336** [comment]
I tried doing it client side, and it didn't do anything, but I'll try again. I assumed the server config was forcing it.
