### ISSUE TITLE
Modular Power suit upgrade cant craft

### ISSUE THREAD

**Issue by Camtoe112** [RTRGitHub/RTRRedux#76]
No recipe for:

Lux Capacitor 2478
Carbon MyoFiber 25026:13
MicroFiber Gel 25026:15
Artificial Muscle 25026:16
Solar Panel 25026:17
Magnet 25026:18
Computer Chip 25026:19

**Comment by UnsungCesspool** [comment]
Artificial Muscle, Microfiber gel, and carbon myofibers i beieve are uncraftable on purpose. I have never seen a use for them.

Lux Capacitors in particular part of adding the upgrade to the power tool/fist.
