### ISSUE TITLE
Thaumcraft Golems

### ISSUE THREAD

**Issue by ghost** [RTRGitHub/RTRRedux#80]
Do not work AT ALL.  They can be placed and assigned a "home" or target but do not function period.

**Comment by ghost** [comment]
A little extra info.  I've tried straw and wood golems with combinations of harvest or gather cores with order upgrades.  I cannot get them to farm even vanilla items.

**Comment by ghost** [comment]
UPDATE:  They worked after relogging a second time?  IDK WTF is going on but it should prob be looked into.  Could've been after server restart.

**Comment by ghost** [comment]
UPDATE:  I did a little diagnosing myself and found that if they are Chunkloaded they will not work.  It is still hit or miss though.

**Comment by Solidflip** [comment]
I havent been able to replicate this issue, the golems seem to be doing their job (albeit in testing it was simple things) When i am on the server flag me down and ill take a look.

If this issue isnt coming up anymore though, let me know as well.
