### ISSUE TITLE
Revitalizing Ring of Shielding Infusion

### ISSUE THREAD

**Issue by ghost** [RTRGitHub/RTRRedux#84]
The infusion will not start.  I triple checked all of the items and aspects needed.  Altar is not recognizing something.

**Comment by Solidflip** [comment]
I found the issue; The infusion works perfectly when you use a Potion of Regeneration that lasts 2:00. Any other iteration fails. The basic potion lasts 45 secs, that is the issue.

Please re-try with the above fix, if the issue persists, let me know.
