### ISSUE TITLE
time outs when interacting with inventories

### ISSUE THREAD

**Issue by Work-work** [RTRGitHub/RTRRedux#92]
Not really playable now, feels like interacting with inventories is causing a derp somewhere that plugs the data stream. jabba barrels, iron chests, mekanism machines, vanilla chests, tinkers work table, ender chest are what I have around my base.

**Comment by Solidflip** [comment]
I will need a bit more info on this to figure it out, it could range from many things. Please log on and let it happen again, then take your log and post it to Pastebin and post that link here. Then i will check it out to narrow down the problem. Also some info about your system couldnt hurt, ie 32bit or 64 etc.

BTW sorry for the delay, long days at work mean less time to hunt down issues =(

**Comment by Solidflip** [comment]
As i have not gotten a log, i assume this issue has fixed itself. If this is not the case please open a new issue
