### ISSUE TITLE
Ender IO energy conduits

### ISSUE THREAD

**Issue by Aulton** [RTRGitHub/RTRRedux#94]
The ender IO power conduits do not transfer power into Thermal Expansion and MFR machines. They interface with them, and transfer energy to the energy cells, but not he machines themselves. The item conduits and the fluid conduits work with the regular machines as well, meaning it's just the energy ones that are not functioning as intended at the moment.

**Comment by Solidflip** [comment]
I believe i know what is causing this, an old API left in the COFH file of Asielib, I will fix this and test if it worked tonight.

**Comment by Volaunis** [comment]
I tested in SP yesterday, and ExUtil power can't input into MFR machines either. It seems it's only MFR's own power cable that can (and energy cells etc).

**Comment by Abouttabs** [comment]
Rf api was changed, I will try to update enderIO..

**Comment by Abouttabs** [comment]
I Feex
