### ISSUE TITLE
Obsidian Stick ID issue.

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#96]
When you craft an Obsidian Stick (Random Things ID: 6420:1), it creates the Obsidian Stick from WR-CBE ID 6942

Crafting reciepe is the same for both....1 obsidian on top of the other.

Suggestion: Change the recipie for the Random Things' Obsidian Stick  to require 3 Obsidian total in a verticle line.

**Comment by Solidflip** [comment]
Fixed with MineTweaker, Items require the same amount of obsidian, and are now shaped
