### ISSUE TITLE
AE3 crafting terminal Issue

### ISSUE THREAD

**Issue by Souperhero** [RTRGitHub/RTRRedux#98]
If a player leaves items in the crafting part of the Crafting terminal for AE3, and then leaves the chunk temporarily, the items auto delete.

**Comment by Souperhero** [comment]
Items lost: 

1087:1 x 4
1087:12 x 1
1121 x 2

Thanks guys.

**Comment by RTRGitHub** [comment]
Hmm, I'll look into this tonight, no new version of AE at the moment so we wouldn't be able to fix anyway, but would  be nice to have it confirmed.

-Kenny
Btw, it's AE2 =D

**Comment by Souperhero** [comment]
Haha woops, my bad! But thanks! Keep me updated.
