### ISSUE TITLE
Platinum Seed Recipie derp

### ISSUE THREAD

**Issue by UnsungCesspool** [RTRGitHub/RTRRedux#99]
Platinum Seeds, ID 6698, currently requires 2 shiny ingots & 2 nickel "crops"(ID 1953) in order to craft. These crops aren't obtainable..

Can we get this recipie changed to require 4 shiny ingots via minetweaker please?

**Comment by UnsungCesspool** [comment]
Brought forward by Panthron...another issue with Magical crops.

Ruby, Sapphire, and Peridot seeds  recipies look to be correct, but your unable to pull the seed out of the crafting window.

**Comment by Solidflip** [comment]
All seeds now work, did some minetweaker
